// WARNING: Under review - generated by LLM.

//! Rust port of the Week 4 Day 9 bounded tool-evidence tests.

#[path = "support/capstone.rs"]
mod capstone;

use std::cell::Cell;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

use serde_json::{Value, json};
use sha2::{Digest, Sha256};
use tiny_llm_agent::protocol::ToolAction;
use tiny_llm_agent::workspace::{ToolPolicy, Workspace};
use tiny_llm_agent::{
    AgentLimits, ArtifactRef, ArtifactStore, BoundedEvidenceWorkspace, ReceiptStore, run_agent,
};

static NEXT_TEMP_DIR: AtomicU64 = AtomicU64::new(1);

struct TestDir(PathBuf);

impl TestDir {
    fn new(label: &str) -> Self {
        let id = NEXT_TEMP_DIR.fetch_add(1, Ordering::Relaxed);
        let path =
            std::env::temp_dir().join(format!("tiny-llm-{label}-{}-{id}", std::process::id()));
        fs::create_dir(&path).expect("create isolated test directory");
        Self(path)
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for TestDir {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn policy(root: &Path, max_file_bytes: i64) -> ToolPolicy {
    ToolPolicy::new(
        root.to_path_buf(),
        max_file_bytes,
        ToolPolicy::DEFAULT_MAX_LIST_ENTRIES,
        false,
        vec![],
        ToolPolicy::DEFAULT_MAX_WRITE_BYTES,
        ToolPolicy::DEFAULT_COMMAND_TIMEOUT_SECONDS,
    )
    .expect("valid test policy")
}

fn action(tool: &str, arguments: Value) -> ToolAction {
    ToolAction {
        tool: tool.to_owned(),
        arguments: arguments
            .as_object()
            .expect("tool arguments must be an object")
            .clone(),
    }
}

fn read_action(path: &str) -> ToolAction {
    action("read_file", json!({"path": path}))
}

fn payload(observation: &str, prefix: &str) -> Value {
    let encoded = observation
        .strip_prefix(prefix)
        .unwrap_or_else(|| panic!("observation did not start with {prefix:?}: {observation:?}"));
    serde_json::from_str(encoded).expect("observation payload is valid JSON")
}

fn bounded_workspace(
    temp: &TestDir,
    label: &str,
    content: &str,
    max_inline_bytes: i64,
    preview_bytes: i64,
    max_range_bytes: i64,
) -> BoundedEvidenceWorkspace {
    let workspace_root = temp.path().join(format!("{label}-workspace"));
    let artifact_root = temp.path().join(format!("{label}-artifacts"));
    fs::create_dir(&workspace_root).expect("create workspace root");
    fs::create_dir(&artifact_root).expect("create artifact root");
    fs::write(workspace_root.join("build.log"), content.as_bytes()).expect("write build log");
    let workspace = Workspace::new(
        policy(&workspace_root, 32_000),
        None,
        ReceiptStore::new(None).expect("receipt store"),
    );
    let artifacts = ArtifactStore::new(artifact_root).expect("artifact store");
    BoundedEvidenceWorkspace::new(
        workspace,
        artifacts,
        max_inline_bytes,
        preview_bytes,
        max_range_bytes,
    )
    .expect("bounded evidence workspace")
}

fn default_bounded(temp: &TestDir, label: &str, content: &str) -> BoundedEvidenceWorkspace {
    bounded_workspace(
        temp,
        label,
        content,
        BoundedEvidenceWorkspace::DEFAULT_MAX_INLINE_BYTES,
        BoundedEvidenceWorkspace::DEFAULT_PREVIEW_BYTES,
        BoundedEvidenceWorkspace::DEFAULT_MAX_RANGE_BYTES,
    )
}

fn sha256(data: &[u8]) -> String {
    format!("{:x}", Sha256::digest(data))
}

#[test]
fn test_task_0_supplied_capstone_composes_the_completed_active_package() {
    // Child mode exercises the same Rust learner package in another process.
    if let Some(output) = std::env::var_os("TINY_LLM_CAPSTONE_RECORD") {
        let record = capstone::run_capstone();
        fs::write(
            output,
            format!("{}\n", serde_json::to_string(&record).unwrap()),
        )
        .unwrap();
        return;
    }
    let first = capstone::run_capstone();
    assert_eq!(first, capstone::run_capstone());
    let keys = first
        .as_object()
        .unwrap()
        .keys()
        .map(String::as_str)
        .collect::<Vec<_>>();
    assert_eq!(keys, ["artifact", "branches", "compaction", "selection"]);
    let compact = &first["compaction"];
    assert!(compact["tokens_before"].as_i64().unwrap() > compact["tokens_after"].as_i64().unwrap());
    assert!(compact["saved_tokens"].as_i64().unwrap() > 0);
    assert_eq!(compact["receipt_ids"].as_array().unwrap().len(), 2);
    assert_eq!(
        compact["checkpoint_status"]["last_action"],
        r#"{"path":"build.log","tool":"read_file"}"#
    );
    let branches = first["branches"].as_array().unwrap();
    assert_eq!(branches.len(), 2);
    assert_eq!(branches[0]["name"], "validate-only");
    assert_eq!(branches[1]["name"], "try-extra-edit");
    assert_eq!(branches[0]["evaluation"]["passed"], true);
    assert_eq!(branches[1]["evaluation"]["passed"], false);
    for branch in branches {
        let reused = branch["reused_tokens"].as_i64().unwrap();
        assert!(reused > 0);
        assert_eq!(branch["avoided_prefill_tokens"], reused);
        assert_eq!(branch["layer_offsets"], json!([reused, reused]));
    }
    let selection = &first["selection"];
    assert_eq!(selection["selected_name"], "validate-only");
    assert_eq!(selection["app_py_sha256"], sha256(b"answer = 2\n"));
    assert_eq!(
        selection["modified_files"],
        json!({"base":["app.py"],"selected_branch":[]})
    );
    let base_ids = selection["base_receipt_ids"].as_array().unwrap();
    let selected_ids = selection["selected_receipt_ids"].as_array().unwrap();
    assert_eq!(base_ids.len(), 2);
    assert_eq!(selected_ids.len(), 3);
    assert_eq!(&selected_ids[..2], base_ids);
    let artifact = &first["artifact"];
    assert_eq!(
        artifact["artifact_id"],
        format!("artifact-{}", artifact["sha256"].as_str().unwrap())
    );
    assert!(
        artifact["full_byte_count"].as_u64().unwrap()
            > artifact["model_visible_observation_byte_count"]
                .as_u64()
                .unwrap()
    );
    assert_eq!(artifact["range_text"], "ERROR code=E42 dependency mismatch");
    assert_eq!(
        artifact["range_byte_count"].as_u64().unwrap(),
        artifact["range_text"].as_str().unwrap().len() as u64
    );
    assert_eq!(
        artifact["range_end"].as_u64().unwrap() - artifact["range_start"].as_u64().unwrap(),
        artifact["range_byte_count"].as_u64().unwrap()
    );

    let temporary = tempfile::tempdir().unwrap();
    let executable = std::env::current_exe().unwrap();
    let mut records = Vec::new();
    for name in ["first-executable-path", "second-executable-path"] {
        let alias = temporary.path().join(name);
        std::os::unix::fs::symlink(&executable, &alias).unwrap();
        let record_path = temporary.path().join(format!("{name}.json"));
        let output = std::process::Command::new(&alias)
            .args([
                "--exact",
                "test_task_0_supplied_capstone_composes_the_completed_active_package",
            ])
            .env("TINY_LLM_CAPSTONE_RECORD", &record_path)
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "{}\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
        assert!(output.stderr.is_empty());
        let record = fs::read(&record_path).unwrap();
        assert!(record.ends_with(b"\n"));
        assert_eq!(serde_json::from_slice::<Value>(&record).unwrap(), first);
        for forbidden in [
            &executable,
            &alias,
            &temporary.path().to_path_buf(),
            &PathBuf::from(env!("CARGO_MANIFEST_DIR")),
        ] {
            assert!(!String::from_utf8_lossy(&record).contains(forbidden.to_str().unwrap()));
        }
        records.push(record);
    }
    assert_eq!(records[0], records[1]);
    assert_eq!(sha256(&records[0]), sha256(&records[1]));
}

#[test]
fn test_task_1_artifact_store_preserves_exact_bytes_and_identity() {
    let temp = TestDir::new("day9-artifact-store");
    let artifact_root = temp.path().join("artifacts");
    fs::create_dir(&artifact_root).expect("create artifact root");
    let mut store = ArtifactStore::new(artifact_root.clone()).expect("artifact store");
    let result = format!("α\n{}", "build output\n".repeat(40));
    let data = result.as_bytes();

    let record = store.put(&result).expect("store result");

    let digest = sha256(data);
    assert_eq!(
        record,
        ArtifactRef::new(
            format!("artifact-{digest}"),
            data.len() as i64,
            digest.clone(),
        )
        .expect("valid artifact ref")
    );
    assert_eq!(
        fs::read(artifact_root.join(&record.artifact_id)).expect("read artifact"),
        data
    );
    assert_eq!(
        store
            .read_range(&record.artifact_id, 2, 17)
            .expect("read byte range"),
        data[2..17]
    );
    assert_eq!(store.put(&result).expect("idempotent put"), record);

    let error = ArtifactRef::new(
        "artifact-UPPER".to_owned(),
        data.len() as i64,
        digest.clone(),
    )
    .unwrap_err();
    assert!(error.to_string().contains("artifact id"));
    let error = ArtifactRef::new(record.artifact_id.clone(), -1, digest.clone()).unwrap_err();
    assert!(error.to_string().contains("byte count"));
    let error = ArtifactRef::new(
        record.artifact_id.clone(),
        data.len() as i64,
        "not-a-digest".to_owned(),
    )
    .unwrap_err();
    assert!(error.to_string().contains("digest"));
    let other_digest = sha256(b"other");
    let error = ArtifactRef::new(record.artifact_id, data.len() as i64, other_digest).unwrap_err();
    assert!(error.to_string().contains("must match"));
}

#[test]
fn test_task_2_oversized_result_becomes_bounded_verifiable_observation() {
    let temp = TestDir::new("day9-externalize");
    let content = format!("HEAD----{}----TAIL", "x".repeat(3_000));
    let mut bounded = bounded_workspace(&temp, "ascii", &content, 512, 8, 24);

    let observation = bounded
        .execute(&read_action("build.log"), None)
        .expect("externalize oversized result");
    let observed = payload(&observation, "Tool result externalized:\n");

    let data = content.as_bytes();
    let digest = sha256(data);
    let artifact_id = format!("artifact-{digest}");
    let expected_path = bounded
        .artifacts
        .range_path(&artifact_id, 0, 24)
        .expect("range path");
    assert_eq!(
        observed,
        json!({
            "artifact_id": artifact_id,
            "byte_count": data.len(),
            "head_preview": "HEAD----",
            "head_range": [0, 8],
            "omitted_range": [8, data.len() - 8],
            "range_request": {"path": expected_path, "tool": "read_file"},
            "sha256": digest,
            "tail_preview": "----TAIL",
            "tail_range": [data.len() - 8, data.len()],
        })
    );
    assert!(observation.len() <= bounded.max_inline_bytes as usize);
    assert!(observation.len() < content.len());
    assert_eq!(
        fs::read(
            bounded
                .artifacts
                .root
                .join(observed["artifact_id"].as_str().unwrap())
        )
        .expect("read stored artifact"),
        data
    );

    let unicode_content = format!("αβγ{}δεζ", "x".repeat(1_000));
    let mut unicode = bounded_workspace(&temp, "unicode", &unicode_content, 512, 5, 24);
    let rendered = unicode
        .execute(&read_action("build.log"), None)
        .expect("externalize unicode result");
    let observed = payload(&rendered, "Tool result externalized:\n");
    assert!(
        !observed["head_preview"]
            .as_str()
            .unwrap()
            .contains('\u{fffd}')
    );
    assert!(
        !observed["tail_preview"]
            .as_str()
            .unwrap()
            .contains('\u{fffd}')
    );
    assert!(rendered.len() <= unicode.max_inline_bytes as usize);
}

#[test]
fn test_task_2_externalization_uses_utf8_bytes_at_the_exact_inline_boundary() {
    let temp = TestDir::new("day9-inline-boundary");
    let mut inline = default_bounded(&temp, "inline", &"a".repeat(512));
    assert_eq!(
        inline
            .execute(&read_action("build.log"), None)
            .expect("read inline result"),
        "a".repeat(512)
    );

    let content = "é".repeat(512);
    let mut multibyte = default_bounded(&temp, "multibyte", &content);
    let result = multibyte
        .execute(&read_action("build.log"), None)
        .expect("externalize multibyte result");
    let observed = payload(&result, "Tool result externalized:\n");
    assert_eq!(observed["byte_count"], 1_024);
    assert_eq!(content.len(), 1_024);
}

#[test]
fn test_task_2_inline_cap_plus_one_byte_is_externalized() {
    let temp = TestDir::new("day9-cap-plus-one");
    let mut bounded = default_bounded(&temp, "cap", &"a".repeat(513));
    let result = bounded
        .execute(&read_action("build.log"), None)
        .expect("externalize cap plus one");
    assert!(result.starts_with("Tool result externalized:\n"));
}

#[test]
fn test_task_2_four_byte_unicode_bounds_the_whole_encoded_observation() {
    let temp = TestDir::new("day9-four-byte-bound");
    let mut bounded = bounded_workspace(&temp, "emoji", &"🙂".repeat(300), 512, 80, 512);
    let result = bounded
        .execute(&read_action("build.log"), None)
        .expect("externalize emoji result");
    assert!(
        result.len() <= 512,
        "bound is measured in encoded UTF-8 bytes"
    );
}

#[test]
fn test_task_2_four_byte_unicode_preview_ranges_are_byte_accurate() {
    let temp = TestDir::new("day9-four-byte-ranges");
    let content = "🙂".repeat(300);
    let mut bounded = bounded_workspace(&temp, "emoji", &content, 512, 80, 512);
    let result = bounded
        .execute(&read_action("build.log"), None)
        .expect("externalize emoji result");
    let observed = payload(&result, "Tool result externalized:\n");

    let head_end = observed["head_range"][1].as_u64().unwrap() as usize;
    let tail_start = observed["tail_range"][0].as_u64().unwrap() as usize;
    assert_eq!(head_end, observed["head_preview"].as_str().unwrap().len());
    assert_eq!(
        tail_start,
        content.len() - observed["tail_preview"].as_str().unwrap().len()
    );
    assert_eq!(observed["omitted_range"], json!([head_end, tail_start]));
}

#[test]
fn test_task_3_explicit_virtual_read_returns_only_the_bound_range() {
    let temp = TestDir::new("day9-explicit-range");
    let content = "0123456789".repeat(100);
    let mut bounded = bounded_workspace(&temp, "range", &content, 512, 5, 32);
    let first = bounded
        .execute(&read_action("build.log"), None)
        .expect("externalize result");
    let identity = payload(&first, "Tool result externalized:\n");
    let path = bounded
        .artifacts
        .range_path(identity["artifact_id"].as_str().unwrap(), 117, 139)
        .expect("range path");

    let result = bounded
        .execute(&read_action(&path), None)
        .expect("read range");
    let observed = payload(&result, "Artifact range:\n");

    assert_eq!(
        observed,
        json!({
            "artifact_id": identity["artifact_id"],
            "byte_count": 22,
            "data": &content[117..139],
            "end": 139,
            "sha256": identity["sha256"],
            "start": 117,
            "total_byte_count": content.len(),
        })
    );
    assert!(!result.contains(&content[..117]));
    assert!(!result.contains(&content[139..]));
}

#[test]
fn test_task_3_selected_unicode_byte_count_is_not_a_character_count() {
    let temp = TestDir::new("day9-unicode-count");
    let content = "€".repeat(300);
    let mut bounded = default_bounded(&temp, "unicode", &content);
    let first = bounded
        .execute(&read_action("build.log"), None)
        .expect("externalize result");
    let identity = payload(&first, "Tool result externalized:\n");
    let path = bounded
        .artifacts
        .range_path(identity["artifact_id"].as_str().unwrap(), 0, 510)
        .expect("range path");
    let result = bounded
        .execute(&read_action(&path), None)
        .expect("read unicode range");
    let observed = payload(&result, "Artifact range:\n");
    assert_eq!(observed["byte_count"], 510);
    assert_eq!(observed["data"].as_str().unwrap().chars().count(), 170);
}

#[test]
fn test_task_3_advertised_unicode_range_is_aligned_and_runnable() {
    let temp = TestDir::new("day9-advertised-unicode");
    let content = "€".repeat(300);
    let mut bounded = default_bounded(&temp, "unicode", &content);
    let first = bounded
        .execute(&read_action("build.log"), None)
        .expect("externalize result");
    let identity = payload(&first, "Tool result externalized:\n");
    let advertised = identity["range_request"]["path"].as_str().unwrap();
    assert!(advertised.ends_with("/bytes/0-510"));
    let result = bounded
        .execute(&read_action(advertised), None)
        .expect("execute advertised range");
    let observed = payload(&result, "Artifact range:\n");
    assert_eq!(observed["start"], 0);
    assert_eq!(observed["end"], 510);
    assert_eq!(observed["data"], "€".repeat(170));
}

#[test]
fn test_task_3_range_cap_must_hold_one_max_width_utf8_character() {
    for max_range_bytes in [1, 2, 3] {
        let temp = TestDir::new(&format!("day9-small-range-{max_range_bytes}"));
        let workspace_root = temp.path().join("workspace");
        let artifact_root = temp.path().join("artifacts");
        fs::create_dir(&workspace_root).unwrap();
        fs::create_dir(&artifact_root).unwrap();
        fs::write(workspace_root.join("build.log"), "🙂".repeat(130)).unwrap();
        let workspace = Workspace::new(
            policy(&workspace_root, 32_000),
            None,
            ReceiptStore::new(None).unwrap(),
        );
        let artifacts = ArtifactStore::new(artifact_root).unwrap();
        let error = BoundedEvidenceWorkspace::new(workspace, artifacts, 512, 64, max_range_bytes)
            .err()
            .expect("range cap below four must fail");
        assert!(
            error
                .to_string()
                .contains("max_range_bytes must be at least 4")
        );
    }
}

#[test]
fn test_task_3_four_byte_range_cap_is_advertised_and_runnable() {
    let temp = TestDir::new("day9-four-byte-cap");
    let mut bounded = bounded_workspace(&temp, "emoji", &"🙂".repeat(130), 512, 64, 4);
    let first = bounded
        .execute(&read_action("build.log"), None)
        .expect("externalize result");
    let identity = payload(&first, "Tool result externalized:\n");
    let advertised = identity["range_request"]["path"].as_str().unwrap();
    assert!(advertised.ends_with("/bytes/0-4"));
    let result = bounded
        .execute(&read_action(advertised), None)
        .expect("read one emoji");
    let observed = payload(&result, "Artifact range:\n");
    assert_eq!(observed["start"], 0);
    assert_eq!(observed["end"], 4);
    assert_eq!(observed["byte_count"], 4);
    assert_eq!(observed["data"], "🙂");
}

#[test]
fn test_task_3_four_byte_cap_still_rejects_a_supplied_misaligned_range() {
    let temp = TestDir::new("day9-misaligned-four-byte");
    let mut bounded = bounded_workspace(&temp, "emoji", &"🙂".repeat(130), 512, 64, 4);
    let record = bounded
        .artifacts
        .put(&"🙂".repeat(130))
        .expect("store artifact");
    let misaligned = bounded
        .artifacts
        .range_path(&record.artifact_id, 0, 3)
        .expect("range path");
    let result = bounded
        .execute(&read_action(&misaligned), None)
        .expect("misalignment is model-visible");
    assert_eq!(result, "error: artifact range does not align to UTF-8 text");
}

#[test]
fn test_task_4_range_failures_are_ordinary_and_do_not_fall_through() {
    for (index, (path_template, message)) in [
        (".tool-artifacts/not-an-id/bytes/0-4", "path is malformed"),
        ("{artifact}/bytes/-1-2", "path is malformed"),
        ("{artifact}/bytes/9-2", "0 <= start < end"),
        ("{artifact}/bytes/0-99", "exceeds 16 bytes"),
        ("{artifact}/bytes/0-16", "stored byte count"),
    ]
    .into_iter()
    .enumerate()
    {
        let temp = TestDir::new(&format!("day9-range-failure-{index}"));
        let mut bounded = bounded_workspace(&temp, "range", "short", 512, 4, 16);
        let record = bounded.artifacts.put("short").expect("store artifact");
        let artifact_prefix = format!(".tool-artifacts/{}", record.artifact_id);
        let path = path_template.replace("{artifact}", &artifact_prefix);
        let learner_path = bounded.workspace.policy.root.join(&path);
        fs::create_dir_all(learner_path.parent().expect("path parent"))
            .expect("create fall-through path");
        fs::write(&learner_path, b"learner-secret").expect("write fall-through secret");

        let result = bounded
            .execute(&read_action(&path), None)
            .expect("range failure is model-visible");
        assert!(result.starts_with("error: "));
        assert!(result.contains(message), "{path}: {result}");
        assert!(!result.contains("short"));
        assert!(!result.contains("learner-secret"));
    }
}

#[test]
fn test_task_4_oversized_decimal_bounds_are_ordinary_and_do_not_fall_through() {
    for (index, template) in ["{digits}-1", "0-{digits}"].into_iter().enumerate() {
        let temp = TestDir::new(&format!("day9-oversized-decimal-{index}"));
        let mut bounded = default_bounded(&temp, "range", "short");
        let record = bounded.artifacts.put("short").expect("store artifact");
        let digits = "9".repeat(5_000);
        let bound = template.replace("{digits}", &digits);
        let path = format!(".tool-artifacts/{}/bytes/{bound}", record.artifact_id);
        let result = bounded
            .execute(&read_action(&path), None)
            .expect("oversized bound is model-visible");
        assert_eq!(result, "error: artifact range path is malformed");
    }
}

#[test]
fn test_task_4_unknown_store_and_tampering_do_not_leak_artifacts() {
    let temp = TestDir::new("day9-store-isolation");
    let mut bounded = bounded_workspace(&temp, "original", "classified diagnostic", 512, 4, 16);
    let record = bounded
        .artifacts
        .put("classified diagnostic")
        .expect("store classified artifact");
    let path = bounded
        .artifacts
        .range_path(&record.artifact_id, 0, 10)
        .expect("range path");

    let unrelated_root = temp.path().join("unrelated-artifacts");
    fs::create_dir(&unrelated_root).expect("create unrelated artifact root");
    let unrelated_workspace = Workspace::new(
        policy(&bounded.workspace.policy.root, 32_000),
        None,
        ReceiptStore::new(None).unwrap(),
    );
    let mut unrelated = BoundedEvidenceWorkspace::new(
        unrelated_workspace,
        ArtifactStore::new(unrelated_root).unwrap(),
        512,
        4,
        16,
    )
    .unwrap();
    let missing = unrelated
        .execute(&read_action(&path), None)
        .expect("unknown artifact is model-visible");
    assert_eq!(missing, "error: artifact is not available in this store");
    assert!(!missing.contains(&record.artifact_id));
    assert!(!missing.contains("classified"));

    let unicode_record = bounded.artifacts.put("αβγ").expect("store unicode");
    let split_path = bounded
        .artifacts
        .range_path(&unicode_record.artifact_id, 1, 3)
        .expect("range path");
    let split = bounded
        .execute(&read_action(&split_path), None)
        .expect("misalignment is model-visible");
    assert_eq!(split, "error: artifact range does not align to UTF-8 text");

    fs::write(
        bounded.artifacts.root.join(&record.artifact_id),
        b"tampered",
    )
    .expect("tamper artifact");
    let tampered = bounded
        .execute(&read_action(&path), None)
        .expect("tampering is model-visible");
    assert_eq!(
        tampered,
        "error: artifact digest does not match its recorded identity"
    );
    assert!(!tampered.contains("classified"));
}

#[test]
fn test_task_4_range_cap_plus_one_is_rejected() {
    let temp = TestDir::new("day9-range-cap-plus-one");
    let mut bounded = bounded_workspace(&temp, "range", &"a".repeat(100), 512, 4, 16);
    let record = bounded
        .artifacts
        .put(&"a".repeat(100))
        .expect("store artifact");
    let path = bounded
        .artifacts
        .range_path(&record.artifact_id, 0, 17)
        .expect("range path");
    let result = bounded
        .execute(&read_action(&path), None)
        .expect("cap failure is model-visible");
    assert_eq!(result, "error: artifact range exceeds 16 bytes");
}

#[test]
fn test_task_5_existing_agent_loop_retrieves_evidence_then_continues() {
    let temp = TestDir::new("day9-agent-loop");
    let diagnostic = "ERROR code=E42 dependency mismatch";
    let content = format!(
        "head\n{}{}\n{}\ntail",
        "x".repeat(500),
        diagnostic,
        "y".repeat(500)
    );
    let mut bounded = bounded_workspace(&temp, "loop", &content, 512, 8, 64);
    let digest = sha256(content.as_bytes());
    let artifact_id = format!("artifact-{digest}");
    let start = content.find(diagnostic).expect("diagnostic offset");
    let end = start + diagnostic.len();
    let range_path = bounded
        .artifacts
        .range_path(&artifact_id, start as i64, end as i64)
        .expect("range path");
    let responses = [
        r#"{"tool":"read_file","path":"build.log"}"#.to_owned(),
        json!({"tool": "read_file", "path": range_path}).to_string(),
        r#"{"final":"The requested range contains diagnostic E42."}"#.to_owned(),
    ];
    let response_index = Cell::new(0usize);
    let mut generate = |_messages: &[tiny_llm_agent::generation::Message]| {
        let index = response_index.get();
        response_index.set(index + 1);
        responses[index].clone()
    };
    let limits = AgentLimits::new(
        3,
        AgentLimits::DEFAULT_MAX_CONTEXT_CHARS,
        AgentLimits::DEFAULT_MAX_INVALID_ACTIONS,
        AgentLimits::DEFAULT_MAX_IDENTICAL_ACTIONS,
    )
    .expect("agent limits");

    let run = run_agent(
        Some("Inspect the large build log and retrieve the diagnostic range."),
        &mut generate,
        &mut bounded,
        Some(&limits),
        None,
    )
    .expect("agent run");

    assert!(run.completed);
    assert_eq!(
        run.final_.as_deref(),
        Some("The requested range contains diagnostic E42.")
    );
    assert_eq!(run.events.len(), 3);
    assert!(
        !run.events[0]
            .result
            .as_deref()
            .unwrap()
            .contains(diagnostic)
    );
    let range = payload(
        run.events[1].result.as_deref().unwrap(),
        "Artifact range:\n",
    );
    assert_eq!(range["artifact_id"], artifact_id);
    assert_eq!(range["start"], start);
    assert_eq!(range["end"], end);
    assert_eq!(range["data"], diagnostic);
    assert_eq!(
        fs::read(bounded.artifacts.root.join(&artifact_id)).expect("read full artifact"),
        content.as_bytes()
    );
}

#[test]
fn test_task_6_small_and_error_results_remain_inline_and_state_is_delegated() {
    let temp = TestDir::new("day9-inline-delegation");
    let mut bounded = bounded_workspace(&temp, "small", "small result\n", 512, 8, 16);
    let result = bounded
        .execute(&read_action("build.log"), None)
        .expect("read small result");
    assert_eq!(result, "small result\n");
    assert!(std::ptr::eq(bounded.policy(), &bounded.workspace.policy));
    assert_eq!(
        bounded.available_tools(),
        bounded.workspace.available_tools()
    );
    assert!(bounded.modified_files().is_empty());
    assert_eq!(
        fs::read_dir(&bounded.artifacts.root)
            .expect("list artifact root")
            .count(),
        0
    );

    // Rust's concrete Workspace cannot be monkeypatched. An unknown, very long
    // tool name produces the same oversized `error:` delegation case.
    let long_tool = format!("missing-{}", "x".repeat(1_000));
    let long_error = bounded
        .execute(&action(&long_tool, json!({})), None)
        .expect("workspace error is model-visible");
    assert!(long_error.starts_with("error:"));
    assert!(long_error.len() > 512);
    assert_eq!(
        fs::read_dir(&bounded.artifacts.root)
            .expect("list artifact root")
            .count(),
        0
    );

    let invalid_workspace_root = temp.path().join("invalid-workspace");
    let invalid_artifact_root = temp.path().join("invalid-artifacts");
    fs::create_dir(&invalid_workspace_root).unwrap();
    fs::create_dir(&invalid_artifact_root).unwrap();
    let workspace = Workspace::new(
        policy(&invalid_workspace_root, 32_000),
        None,
        ReceiptStore::new(None).unwrap(),
    );
    let artifacts = ArtifactStore::new(invalid_artifact_root).unwrap();
    let error = BoundedEvidenceWorkspace::new(workspace, artifacts, 511, 64, 512)
        .err()
        .expect("inline cap below minimum must fail");
    assert!(error.to_string().contains("at least 512"));

    let preview_workspace_root = temp.path().join("preview-workspace");
    let preview_artifact_root = temp.path().join("preview-artifacts");
    fs::create_dir(&preview_workspace_root).unwrap();
    fs::create_dir(&preview_artifact_root).unwrap();
    let workspace = Workspace::new(
        policy(&preview_workspace_root, 32_000),
        None,
        ReceiptStore::new(None).unwrap(),
    );
    let artifacts = ArtifactStore::new(preview_artifact_root).unwrap();
    let error = BoundedEvidenceWorkspace::new(workspace, artifacts, 512, 513, 512)
        .err()
        .expect("preview over inline cap must fail");
    assert!(error.to_string().contains("must not exceed"));
}
