// WARNING: Under review - generated by LLM.

//! Rust equivalents of `tests_refsol/test_week_4_day_3.py`.

#[path = "./support/utils.rs"]
mod test_utils;

use std::cell::RefCell;
use std::collections::VecDeque;
use std::fs;
use std::rc::Rc;

use serde_json::{Value, json};

use tiny_llm_agent::generation::Message;
use tiny_llm_agent::workspace::ConfirmResult;
use tiny_llm_agent::{EffectReceipt, ReceiptStore, ToolAction, ToolPolicy, Workspace, run_agent};

#[test]
fn test_task_1_policy_enables_only_explicit_effects() {
    let temporary = test_utils::TestDir::new("day3");
    let command = test_utils::string_vec(&["/bin/sh", "-c", "printf 'ok\\n'"]);
    let read_only = test_utils::read_only_workspace(temporary.path());
    let enabled = Workspace::new(
        test_utils::policy(temporary.path(), true, vec![command]),
        None,
        test_utils::memory_store(),
    );

    assert_eq!(
        read_only.available_tools(),
        &["list_files".to_owned(), "read_file".to_owned()]
            .into_iter()
            .collect()
    );
    assert_eq!(
        enabled.available_tools(),
        &[
            "list_files".to_owned(),
            "read_file".to_owned(),
            "write_file".to_owned(),
            "edit_file".to_owned(),
            "run_command".to_owned(),
        ]
        .into_iter()
        .collect()
    );

    let max_write_error = ToolPolicy::new(
        temporary.path().to_path_buf(),
        ToolPolicy::DEFAULT_MAX_FILE_BYTES,
        ToolPolicy::DEFAULT_MAX_LIST_ENTRIES,
        false,
        Vec::new(),
        0,
        ToolPolicy::DEFAULT_COMMAND_TIMEOUT_SECONDS,
    )
    .unwrap_err();
    assert!(max_write_error.to_string().contains("positive"));

    for invalid_timeout in [0.0, -1.0, f64::NAN, f64::INFINITY, f64::NEG_INFINITY] {
        let error = ToolPolicy::new(
            temporary.path().to_path_buf(),
            ToolPolicy::DEFAULT_MAX_FILE_BYTES,
            ToolPolicy::DEFAULT_MAX_LIST_ENTRIES,
            false,
            Vec::new(),
            ToolPolicy::DEFAULT_MAX_WRITE_BYTES,
            invalid_timeout,
        )
        .unwrap_err();
        assert!(error.to_string().contains("finite and positive"));
    }

    let empty_command_error = ToolPolicy::new(
        temporary.path().to_path_buf(),
        ToolPolicy::DEFAULT_MAX_FILE_BYTES,
        ToolPolicy::DEFAULT_MAX_LIST_ENTRIES,
        false,
        vec![vec![String::new()]],
        ToolPolicy::DEFAULT_MAX_WRITE_BYTES,
        ToolPolicy::DEFAULT_COMMAND_TIMEOUT_SECONDS,
    )
    .unwrap_err();
    assert!(empty_command_error.to_string().contains("commands"));

    let nul_command_error = ToolPolicy::new(
        temporary.path().to_path_buf(),
        ToolPolicy::DEFAULT_MAX_FILE_BYTES,
        ToolPolicy::DEFAULT_MAX_LIST_ENTRIES,
        false,
        vec![vec!["validator\0".to_owned()]],
        ToolPolicy::DEFAULT_MAX_WRITE_BYTES,
        ToolPolicy::DEFAULT_COMMAND_TIMEOUT_SECONDS,
    )
    .unwrap_err();
    assert!(nul_command_error.to_string().contains("without NUL"));
}

#[test]
fn test_task_2_mutations_require_read_preflight_and_approval() {
    let temporary = test_utils::TestDir::new("day3");
    let source = temporary.path().join("app.py");
    fs::write(&source, "answer = 1\n").unwrap();
    let mut read_only = test_utils::read_only_workspace(temporary.path());
    assert_eq!(
        read_only.execute(&test_utils::read_file_action("app.py"), None),
        "answer = 1\n"
    );
    let error = read_only.execute(&test_utils::edit_file_action("app.py", "1", "2"), None);
    assert_eq!(error, "error: tool is not enabled: edit_file");
    assert_eq!(fs::read_to_string(&source).unwrap(), "answer = 1\n");

    let approvals = Rc::new(RefCell::new(Vec::<ToolAction>::new()));
    let approvals_for_callback = Rc::clone(&approvals);
    let mut workspace = Workspace::new(
        test_utils::policy(temporary.path(), true, Vec::new()),
        Some(Box::new(move |action| {
            approvals_for_callback.borrow_mut().push(action.clone());
            ConfirmResult::Approved(false)
        })),
        test_utils::memory_store(),
    );
    let edit = test_utils::tool_action(
        "edit_file",
        json!({"path": "app.py", "old": "1", "new": "2"}),
    );

    assert!(
        workspace
            .execute(&edit, None)
            .contains("read the existing file")
    );
    assert!(approvals.borrow().is_empty());
    assert_eq!(
        workspace.execute(&test_utils::read_file_action("app.py"), None),
        "answer = 1\n"
    );
    assert!(workspace.execute(&edit, None).contains("operator denied"));
    assert_eq!(approvals.borrow().len(), 1);
    assert_eq!(fs::read_to_string(&source).unwrap(), "answer = 1\n");
    assert!(workspace.receipt_store.get("call-1").is_none());
}

#[test]
fn test_task_3_rechecks_stale_bytes_after_approval() {
    let temporary = test_utils::TestDir::new("day3");
    let source = temporary.path().join("app.py");
    fs::write(&source, "answer = 1\n").unwrap();
    let source_for_callback = source.clone();
    let mut workspace = Workspace::new(
        test_utils::policy(temporary.path(), true, Vec::new()),
        Some(Box::new(move |_action| {
            fs::write(&source_for_callback, "answer = 9\n").unwrap();
            ConfirmResult::Approved(true)
        })),
        test_utils::memory_store(),
    );
    assert_eq!(
        workspace.execute(&test_utils::read_file_action("app.py"), None),
        "answer = 1\n"
    );
    let result = workspace.execute(
        &test_utils::tool_action(
            "edit_file",
            json!({"path": "app.py", "old": "1", "new": "2"}),
        ),
        None,
    );

    assert_eq!(result, "error: file changed since it was read");
    assert_eq!(fs::read_to_string(&source).unwrap(), "answer = 9\n");
    assert!(workspace.modified_files().is_empty());
}

#[test]
fn test_task_4_exact_edit_uses_same_directory_replace_and_receipt() {
    use std::os::unix::fs::MetadataExt;

    let temporary = test_utils::TestDir::new("day3");
    let source = temporary.path().join("app.py");
    fs::write(&source, "answer = 1\n").unwrap();
    // A hard link detects in-place rewrites without a production test hook.
    let old_inode = temporary.path().join("original-app.py");
    fs::hard_link(&source, &old_inode).unwrap();
    let store_path = temporary.path().join("receipts.jsonl");
    let store = ReceiptStore::new(Some(store_path.clone())).unwrap();
    let replacement = Rc::new(RefCell::new(None));
    let observed_replacement = Rc::clone(&replacement);
    let target = source.clone();
    let original_link = old_inode.clone();
    let mut workspace = Workspace::new(
        test_utils::policy(temporary.path(), true, Vec::new()),
        Some(Box::new(move |_action| {
            // The current implementation prepares the temporary file before
            // approval. Observe the actual replacement, not just a helper probe.
            let parent = target.parent().unwrap();
            let candidates = fs::read_dir(parent)
                .unwrap()
                .map(|entry| entry.unwrap().path())
                .filter(|path| path != &target && path != &original_link && path != &store_path)
                .collect::<Vec<_>>();
            assert_eq!(
                candidates.len(),
                1,
                "expected one same-directory temporary file"
            );
            let temporary_path = &candidates[0];
            assert_eq!(temporary_path.parent(), target.parent());
            let metadata = fs::metadata(temporary_path).unwrap();
            *observed_replacement.borrow_mut() =
                Some((temporary_path.clone(), metadata.dev(), metadata.ino()));
            ConfirmResult::Approved(true)
        })),
        store,
    );
    let probe = workspace.create_temporary_file(&source).unwrap();
    assert_eq!(probe.path().parent(), source.parent());
    assert!(probe.path().is_file());
    drop(probe);
    assert_eq!(
        workspace.execute(&test_utils::read_file_action("app.py"), None),
        "answer = 1\n"
    );
    let result = workspace.execute(
        &test_utils::tool_action(
            "edit_file",
            json!({"path": "./app.py", "old": "1", "new": "2"}),
        ),
        Some("edit-1"),
    );

    assert_eq!(result, "edited app.py");
    assert_eq!(fs::read_to_string(&source).unwrap(), "answer = 2\n");
    let replacement = replacement.borrow();
    let (temporary_path, device, inode) = replacement.as_ref().expect("replacement was observed");
    let metadata = fs::metadata(&source).unwrap();
    assert_eq!((metadata.dev(), metadata.ino()), (*device, *inode));
    assert!(
        !temporary_path.exists(),
        "rename must consume the temporary path"
    );
    assert_eq!(fs::read(&old_inode).unwrap(), b"answer = 1\n");
    fs::remove_file(&old_inode).unwrap();
    assert_eq!(workspace.modified_files(), vec!["app.py"]);
    assert_eq!(
        workspace
            .receipt_store
            .get("edit-1")
            .unwrap()
            .changed_artifacts,
        vec!["app.py"]
    );

    // Also require that the replacement leaves no temporary files behind.
    let mut names = fs::read_dir(temporary.path())
        .unwrap()
        .map(|entry| entry.unwrap().file_name().to_string_lossy().into_owned())
        .collect::<Vec<_>>();
    names.sort();
    assert_eq!(names, vec!["app.py", "receipts.jsonl"]);
}

#[test]
fn test_task_5_write_creates_new_files_but_observes_existing_files() {
    let temporary = test_utils::TestDir::new("day3");
    let store = test_utils::memory_store();
    let mut workspace = Workspace::new(
        test_utils::policy(temporary.path(), true, Vec::new()),
        Some(Box::new(|_action| ConfirmResult::Approved(true))),
        store,
    );
    let create =
        test_utils::tool_action("write_file", json!({"path": "new.txt", "content": "new\n"}));

    assert_eq!(
        workspace.execute(&create, Some("write-new")),
        "wrote new.txt"
    );
    assert_eq!(
        fs::read_to_string(temporary.path().join("new.txt")).unwrap(),
        "new\n"
    );

    let overwrite = test_utils::tool_action(
        "write_file",
        json!({"path": "new.txt", "content": "replacement\n"}),
    );
    let mut other = Workspace::new(
        test_utils::policy(temporary.path(), true, Vec::new()),
        Some(Box::new(|_action| ConfirmResult::Approved(true))),
        test_utils::memory_store(),
    );
    assert!(
        other
            .execute(&overwrite, None)
            .contains("read the existing file")
    );
    assert_eq!(
        other.execute(&test_utils::read_file_action("new.txt"), None),
        "new\n"
    );
    assert_eq!(other.execute(&overwrite, None), "wrote new.txt");
}

#[test]
fn test_task_6_validation_uses_exact_argv_and_records_output() {
    let temporary = test_utils::TestDir::new("day3");
    let allowed = test_utils::string_vec(&["/bin/sh", "-c", "printf 'focused fail\\n'; exit 3"]);
    let approvals = Rc::new(RefCell::new(Vec::<ToolAction>::new()));
    let approvals_for_callback = Rc::clone(&approvals);
    let store = test_utils::memory_store();
    let mut workspace = Workspace::new(
        test_utils::policy(temporary.path(), false, vec![allowed.clone()]),
        Some(Box::new(move |action| {
            approvals_for_callback.borrow_mut().push(action.clone());
            ConfirmResult::Approved(true)
        })),
        store,
    );

    let denied = workspace.execute(
        &test_utils::tool_action("run_command", json!({"argv": ["echo", "no"]})),
        None,
    );
    let nul_denied = workspace.execute(
        &test_utils::tool_action(
            "run_command",
            json!({"argv": ["/bin/sh", "bad\u{0}argument"]}),
        ),
        None,
    );
    let result = workspace.execute(
        &test_utils::tool_action("run_command", json!({"argv": allowed})),
        Some("validate-1"),
    );
    let receipt = workspace.receipt_store.get("validate-1").unwrap();

    assert_eq!(denied, "error: command is not allowed");
    assert_eq!(
        nul_denied,
        "error: argv must contain non-empty strings without NUL"
    );
    assert_eq!(approvals.borrow().len(), 1);
    assert_eq!(result, "status: 3\noutput:\nfocused fail\n");
    assert_eq!(
        receipt.tool,
        test_utils::tool_action(
            "run_command",
            json!({
                "argv": ["/bin/sh", "-c", "printf 'focused fail\\n'; exit 3"]
            })
        )
    );
    assert_eq!(receipt.exit_state, "error");
    assert_eq!(receipt.result, result);
    assert!(receipt.changed_artifacts.is_empty());
}

#[test]
fn test_task_7_duplicate_call_ids_do_not_repeat_an_effect() {
    let temporary = test_utils::TestDir::new("day3");
    let allowed = test_utils::string_vec(&[
        "/bin/sh",
        "-c",
        "printf x >> command-count; printf 'pass\\n'",
    ]);
    let mut workspace = Workspace::new(
        test_utils::policy(temporary.path(), false, vec![allowed.clone()]),
        Some(Box::new(|_action| ConfirmResult::Approved(true))),
        test_utils::memory_store(),
    );
    let action = test_utils::tool_action("run_command", json!({"argv": allowed}));

    let first = workspace.execute(&action, Some("same-call"));
    let second = workspace.execute(&action, Some("same-call"));

    assert_eq!(first, "status: 0\noutput:\npass\n");
    assert_eq!(second, first);
    assert_eq!(
        fs::read_to_string(temporary.path().join("command-count")).unwrap(),
        "x",
        "an idempotent retry must not execute the command again"
    );
    let conflict = workspace.execute(
        &test_utils::tool_action("run_command", json!({"argv": ["different"]})),
        Some("same-call"),
    );
    assert!(conflict.contains("already used"));
}

#[test]
fn test_task_8_jsonl_receipts_reopen_and_detect_tampering() {
    let temporary = test_utils::TestDir::new("day3");
    let path = temporary.path().join("receipts.jsonl");
    let receipt = EffectReceipt::new(
        "edit-1".to_owned(),
        test_utils::tool_action(
            "edit_file",
            json!({"path": "app.py", "old": "1", "new": "2"}),
        ),
        "ok".to_owned(),
        "edited app.py".to_owned(),
        vec!["app.py".to_owned()],
    )
    .unwrap();
    ReceiptStore::new(Some(path.clone()))
        .unwrap()
        .put(receipt.clone())
        .unwrap();

    assert_eq!(
        ReceiptStore::new(Some(path.clone())).unwrap().get("edit-1"),
        Some(&receipt)
    );
    let line = fs::read_to_string(&path).unwrap();
    let mut payload: Value = serde_json::from_str(&line).unwrap();
    payload
        .as_object_mut()
        .unwrap()
        .insert("result".to_owned(), json!("edited another.py"));
    fs::write(
        &path,
        format!("{}\n", serde_json::to_string(&payload).unwrap()),
    )
    .unwrap();

    let error = ReceiptStore::new(Some(path)).unwrap_err();
    assert!(error.to_string().contains("digest"));
}

#[test]
fn test_task_9_agent_reads_edits_validates_and_finishes() {
    let temporary = test_utils::TestDir::new("day3");
    let source = temporary.path().join("app.py");
    fs::write(&source, "answer = 1\n").unwrap();
    let validation =
        test_utils::string_vec(&["/bin/sh", "-c", "printf 'answer = 2\\n' | cmp -s - app.py"]);
    let approved = Rc::new(RefCell::new(Vec::<String>::new()));
    let approved_for_callback = Rc::clone(&approved);
    let store = ReceiptStore::new(Some(temporary.path().join("receipts.jsonl"))).unwrap();
    let mut workspace = Workspace::new(
        test_utils::policy(temporary.path(), true, vec![validation.clone()]),
        Some(Box::new(move |action| {
            approved_for_callback
                .borrow_mut()
                .push(action.tool().to_owned());
            ConfirmResult::Approved(true)
        })),
        store,
    );
    let command_response = serde_json::to_string(&json!({
        "tool": "run_command",
        "argv": validation,
    }))
    .unwrap();
    let responses = RefCell::new(VecDeque::from([
        r#"{"tool":"read_file","path":"app.py"}"#.to_owned(),
        r#"{"tool":"edit_file","path":"app.py","old":"1","new":"2"}"#.to_owned(),
        command_response,
        r#"{"final":"changed and validated app.py"}"#.to_owned(),
    ]));
    let mut generate = |_messages: &[Message]| {
        responses
            .borrow_mut()
            .pop_front()
            .expect("scripted response queue exhausted")
    };

    let result = run_agent(
        Some("fix app.py"),
        &mut generate,
        &mut workspace,
        None,
        None,
    )
    .unwrap();

    assert!(result.completed);
    assert_eq!(
        result.final_.as_deref(),
        Some("changed and validated app.py")
    );
    assert_eq!(workspace.modified_files(), vec!["app.py"]);
    assert_eq!(approved.borrow().as_slice(), ["edit_file", "run_command"]);
    assert_eq!(
        workspace
            .receipt_store
            .get("call-1")
            .unwrap()
            .changed_artifacts,
        vec!["app.py"]
    );
    assert_eq!(
        workspace.receipt_store.get("call-2").unwrap().tool,
        test_utils::tool_action(
            "run_command",
            json!({
                "argv": [
                    "/bin/sh",
                    "-c",
                    "printf 'answer = 2\\n' | cmp -s - app.py"
                ]
            })
        )
    );
    assert!(
        workspace
            .receipt_store
            .get("call-2")
            .unwrap()
            .changed_artifacts
            .is_empty()
    );
}
