// WARNING: Under review - generated by LLM.

//! Week 4 Day 6 inspect-and-steer course-code tests.

#[path = "./support/utils.rs"]
mod test_utils;

use std::cell::RefCell;
use std::fs;
use std::rc::Rc;

use serde_json::json;

use tiny_llm_agent::generation::{Generate, Message};
use tiny_llm_agent::protocol::AgentError;
use tiny_llm_agent::workspace::{ConfirmResult, ConfirmTool};
use tiny_llm_agent::{
    ModelCheckpoint, ReceiptStore, Workspace, create_checkpoint, inspect_checkpoint,
    resume_with_steering, run_to_checkpoint,
};

struct FakeSteeringModel {
    responses: Vec<String>,
    response_index: usize,
    restored: Option<ModelCheckpoint>,
    calls: Vec<Vec<Message>>,
}

impl FakeSteeringModel {
    fn new(responses: &[&str]) -> Self {
        Self {
            responses: responses
                .iter()
                .map(|response| (*response).to_owned())
                .collect(),
            response_index: 0,
            restored: None,
            calls: vec![],
        }
    }
}

impl Generate for FakeSteeringModel {
    fn generate(&mut self, messages: &[Message]) -> Result<String, AgentError> {
        self.calls.push(messages.to_vec());
        if let Some(restored) = self.restored.take() {
            let prefix = &messages[..restored.conversation_position as usize];
            assert_eq!(
                test_utils::fake_token_ids(prefix),
                restored.cached_token_ids
            );
        }
        let response = self
            .responses
            .get(self.response_index)
            .expect("scripted steering model ran out of responses")
            .clone();
        self.response_index += 1;
        Ok(response)
    }

    fn save_checkpoint(&mut self, messages: &[Message]) -> Result<ModelCheckpoint, AgentError> {
        let tokens = test_utils::fake_token_ids(messages);
        ModelCheckpoint::new(
            messages.len() as i64,
            self.response_index as i64,
            tokens.clone(),
            vec![tokens.len() as i64, tokens.len() as i64],
        )
    }

    fn restore_checkpoint(&mut self, checkpoint: &ModelCheckpoint) -> Result<(), AgentError> {
        self.response_index = checkpoint.response_index as usize;
        self.restored = Some(checkpoint.clone());
        Ok(())
    }
}

#[test]
fn test_task_1_status_reports_only_the_complete_checkpoint_boundary() {
    let directory = test_utils::tempdir().unwrap();
    fs::write(directory.path().join("README.md"), "project evidence\n").unwrap();
    let mut workspace = test_utils::read_only_workspace(directory.path());
    let mut model = FakeSteeringModel::new(&[r#"{"tool":"read_file","path":"README.md"}"#]);
    let checkpoint =
        run_to_checkpoint("inspect the project", &mut model, &mut workspace, 1, None).unwrap();

    let status = inspect_checkpoint(&checkpoint, 160).unwrap();

    assert_eq!(status.task, "inspect the project");
    assert_eq!(
        status.last_action,
        r#"{"path":"README.md","tool":"read_file"}"#
    );
    assert_eq!(status.last_evidence, "project evidence\n");
    assert_eq!(
        status.next_step,
        "resume the model after the completed read_file observation"
    );
}

#[test]
fn test_task_2_status_preview_is_bounded_and_inspection_is_pure() {
    let messages = vec![
        test_utils::message("system", "system"),
        test_utils::message("user", "inspect"),
        test_utils::message("assistant", r#"{"tool":"read_file","path":"a"}"#),
        test_utils::message("user", "Tool result:\nabcdefghij"),
    ];
    let model = ModelCheckpoint::new(4, 1, vec![6, 7, 31, 22], vec![4]).unwrap();
    let checkpoint = create_checkpoint("inspect", &messages, model.clone()).unwrap();

    let status = inspect_checkpoint(&checkpoint, 5).unwrap();

    assert_eq!(status.last_evidence, "abcd…");
    assert_eq!(status.last_evidence.chars().count(), 5);
    assert_eq!(
        checkpoint.messages.last().unwrap(),
        &("user".to_owned(), "Tool result:\nabcdefghij".to_owned())
    );
    assert_eq!(checkpoint.model, model);
    test_utils::assert_error_contains(inspect_checkpoint(&checkpoint, 0), "positive integer");
}

fn checkpoint_with_action(action: &str) -> tiny_llm_agent::AgentCheckpoint {
    let messages = vec![
        test_utils::message("system", "system"),
        test_utils::message("user", "inspect"),
        test_utils::message("assistant", action),
        test_utils::message("user", "Tool result:\nresult"),
    ];
    create_checkpoint(
        "inspect",
        &messages,
        ModelCheckpoint::new(4, 1, vec![6, 7, 8, 19], vec![4]).unwrap(),
    )
    .unwrap()
}

macro_rules! invalid_status_test {
    ($name:ident, $action:expr, $error:expr) => {
        #[test]
        fn $name() {
            let checkpoint = checkpoint_with_action($action);
            test_utils::assert_error_contains(inspect_checkpoint(&checkpoint, 160), $error);
        }
    };
}

invalid_status_test!(
    test_task_3_status_rejects_non_json_tool_action,
    "not json",
    "not valid JSON"
);
invalid_status_test!(
    test_task_3_status_rejects_final_action,
    r#"{"final":"done"}"#,
    "expected a tool action"
);
invalid_status_test!(
    test_task_3_status_rejects_unknown_tool,
    r#"{"tool":"unknown"}"#,
    "unknown tool"
);
invalid_status_test!(
    test_task_3_status_rejects_missing_read_file_path,
    r#"{"tool":"read_file"}"#,
    "missing fields for read_file: path"
);
invalid_status_test!(
    test_task_3_status_rejects_non_string_read_file_path,
    r#"{"tool":"read_file","path":7}"#,
    "path must be a string"
);
invalid_status_test!(
    test_task_3_status_rejects_unexpected_read_file_field,
    r#"{"tool":"read_file","path":"README.md","extra":true}"#,
    "unexpected fields for read_file: extra"
);

#[test]
fn test_task_3_status_rejects_an_incomplete_tool_boundary() {
    let messages = vec![
        test_utils::message("system", "system"),
        test_utils::message("user", "inspect"),
    ];
    let checkpoint = create_checkpoint(
        "inspect",
        &messages,
        ModelCheckpoint::new(2, 0, vec![6, 7], vec![2]).unwrap(),
    )
    .unwrap();

    test_utils::assert_error_contains(
        inspect_checkpoint(&checkpoint, 160),
        "complete tool observation",
    );
}

#[test]
fn test_task_4_steering_is_one_visible_message_in_stable_order() {
    let directory = test_utils::tempdir().unwrap();
    fs::write(directory.path().join("a.txt"), "A\n").unwrap();
    fs::write(directory.path().join("b.txt"), "B\n").unwrap();
    let mut workspace = test_utils::read_only_workspace(directory.path());
    let responses = [
        r#"{"tool":"read_file","path":"a.txt"}"#,
        r#"{"tool":"read_file","path":"b.txt"}"#,
        r#"{"final":"used both files and the operator priority"}"#,
    ];
    let mut initial_model = FakeSteeringModel::new(&responses);
    let checkpoint = run_to_checkpoint(
        "compare the files",
        &mut initial_model,
        &mut workspace,
        1,
        None,
    )
    .unwrap();
    let mut fresh = FakeSteeringModel::new(&responses);

    let result = resume_with_steering(
        &checkpoint,
        "prioritize b.txt",
        &mut fresh,
        &mut workspace,
        None,
    )
    .unwrap();

    assert!(result.completed);
    assert_eq!(
        result.final_.as_deref(),
        Some("used both files and the operator priority")
    );
    for call in &fresh.calls {
        let steering: Vec<_> = call
            .iter()
            .enumerate()
            .filter(|(_, message)| message["content"].starts_with("Operator steering:\n"))
            .collect();
        assert_eq!(steering.len(), 1);
        assert_eq!(
            steering[0].0,
            checkpoint.model.conversation_position as usize
        );
        assert_eq!(steering[0].1["role"], "user");
        assert_eq!(
            steering[0].1["content"],
            "Operator steering:\nprioritize b.txt"
        );
    }
    let last_call = fresh.calls.last().unwrap();
    assert_eq!(
        last_call[last_call.len() - 2]["content"],
        r#"{"tool":"read_file","path":"b.txt"}"#
    );
    assert_eq!(last_call.last().unwrap()["content"], "Tool result:\nB\n");
    assert_eq!(
        checkpoint.messages.last().unwrap(),
        &("user".to_owned(), "Tool result:\nA\n".to_owned())
    );
}

#[test]
fn test_task_5_steered_resume_does_not_replay_the_completed_edit() {
    let directory = test_utils::tempdir().unwrap();
    let source = directory.path().join("app.py");
    let counter = directory.path().join("validation-count.txt");
    fs::write(&source, "answer = 1\n").unwrap();
    let python = std::env::var("PYTHON").unwrap_or_else(|_| "python3".to_owned());
    let validation = vec![
        python,
        "-c".to_owned(),
        concat!(
            "from pathlib import Path; ",
            "p=Path('validation-count.txt'); ",
            "p.write_text(str(int(p.read_text()) + 1) if p.exists() else '1'); ",
            "assert Path('app.py').read_text() == 'answer = 2\\n'"
        )
        .to_owned(),
    ];
    let approvals = Rc::new(RefCell::new(Vec::<String>::new()));
    let captured_approvals = Rc::clone(&approvals);
    let confirm: ConfirmTool = Box::new(move |action| {
        captured_approvals
            .borrow_mut()
            .push(action.tool().to_owned());
        ConfirmResult::Approved(true)
    });
    let receipts = ReceiptStore::new(Some(directory.path().join("receipts.jsonl"))).unwrap();
    let mut workspace = Workspace::new(
        test_utils::policy(directory.path(), true, vec![validation.clone()]),
        Some(confirm),
        receipts.clone(),
    );
    let command_response = json!({"tool": "run_command", "argv": validation}).to_string();
    let responses = [
        r#"{"tool":"read_file","path":"app.py"}"#.to_owned(),
        r#"{"tool":"edit_file","path":"app.py","old":"1","new":"2"}"#.to_owned(),
        command_response,
        r#"{"final":"fixed app.py and validated it as requested"}"#.to_owned(),
    ];
    let response_refs: Vec<&str> = responses.iter().map(String::as_str).collect();
    let mut initial_model = FakeSteeringModel::new(&response_refs);
    let checkpoint = run_to_checkpoint(
        "fix app.py and validate",
        &mut initial_model,
        &mut workspace,
        2,
        None,
    )
    .unwrap();
    assert_eq!(approvals.borrow().as_slice(), &["edit_file".to_owned()]);
    assert_eq!(fs::read_to_string(&source).unwrap(), "answer = 2\n");

    let mut fresh = FakeSteeringModel::new(&response_refs);
    let result = resume_with_steering(
        &checkpoint,
        "validate before answering",
        &mut fresh,
        &mut workspace,
        None,
    )
    .unwrap();

    assert!(result.completed);
    assert_eq!(
        result.final_.as_deref(),
        Some("fixed app.py and validated it as requested")
    );
    assert_eq!(
        approvals.borrow().as_slice(),
        &["edit_file".to_owned(), "run_command".to_owned()]
    );
    assert_eq!(fs::read_to_string(&counter).unwrap(), "1");
    assert_eq!(fs::read_to_string(&source).unwrap(), "answer = 2\n");
    assert_eq!(
        workspace.receipt_store.get("call-1").unwrap().tool,
        "edit_file"
    );
    assert_eq!(
        workspace.receipt_store.get("call-2").unwrap().tool,
        "run_command"
    );
    let visible = &fresh.calls[0];
    assert!(
        visible
            .iter()
            .any(|message| message["content"] == "fix app.py and validate")
    );
    assert!(
        visible
            .iter()
            .any(|message| message["content"].contains("edited app.py"))
    );
    assert_eq!(
        visible[checkpoint.model.conversation_position as usize],
        test_utils::message("user", "Operator steering:\nvalidate before answering")
    );
}

#[test]
fn test_task_6_steering_and_checkpoint_validation_fail_closed() {
    let directory = test_utils::tempdir().unwrap();
    let mut workspace = test_utils::read_only_workspace(directory.path());
    let mut model = FakeSteeringModel::new(&[r#"{"tool":"list_files","path":"."}"#]);
    let checkpoint = run_to_checkpoint("inspect", &mut model, &mut workspace, 1, None).unwrap();

    let mut empty_model = FakeSteeringModel::new(&[]);
    test_utils::assert_error_contains(
        resume_with_steering(&checkpoint, "   ", &mut empty_model, &mut workspace, None),
        "steering",
    );

    let mut invalid = checkpoint.clone();
    invalid.checkpoint_id = "0".repeat(64);
    let mut empty_model = FakeSteeringModel::new(&[]);
    test_utils::assert_error_contains(
        resume_with_steering(&invalid, "continue", &mut empty_model, &mut workspace, None),
        "identity",
    );

    let mut plain_generate = |_messages: &[Message]| r#"{"final":"done"}"#.to_owned();
    test_utils::assert_error_contains(
        resume_with_steering(
            &checkpoint,
            "continue",
            &mut plain_generate,
            &mut workspace,
            None,
        ),
        "checkpoint restore",
    );

    let incomplete_messages = vec![
        test_utils::message("system", "system"),
        test_utils::message("user", "inspect"),
    ];
    let incomplete = create_checkpoint(
        "inspect",
        &incomplete_messages,
        ModelCheckpoint::new(2, 0, vec![6, 7], vec![2]).unwrap(),
    )
    .unwrap();
    let mut untouched = FakeSteeringModel::new(&[]);
    test_utils::assert_error_contains(
        resume_with_steering(
            &incomplete,
            "continue",
            &mut untouched,
            &mut workspace,
            None,
        ),
        "complete tool observation",
    );
    assert!(untouched.restored.is_none());
    assert!(untouched.calls.is_empty());
}
