// WARNING: Under review - generated by LLM.

//! Rust port of the Week 4 Day 8 cached-fork, steering, and selection tests.

#[path = "support/temp.rs"]
mod test_temp;

use std::cell::RefCell;
use std::fs;
use std::path::{Path, PathBuf};
use std::rc::Rc;
use std::sync::atomic::{AtomicU64, Ordering};

use serde_json::json;
use tiny_llm_agent::generation::{
    Generate, GenerationCache, GenerationModel, GenerationTokenizer, Message,
};
use tiny_llm_agent::protocol::{AgentError, ToolAction};
use tiny_llm_agent::workspace::{ConfirmResult, ToolPolicy, Workspace};
use tiny_llm_agent::{
    ApprovalDecision, EvaluationCase, FileExpectation, KvPrefixGenerator, ModelCheckpoint,
    PrefixReuse, ReceiptExpectation, ReceiptStore, ResultExpectation, run_branch,
    run_to_checkpoint, select_branch,
};

static NEXT_TEMP_DIR: AtomicU64 = AtomicU64::new(1);
static NEXT_CACHE_ID: AtomicU64 = AtomicU64::new(1);

struct TestDir(PathBuf);

impl TestDir {
    fn new(label: &str) -> Self {
        let id = NEXT_TEMP_DIR.fetch_add(1, Ordering::Relaxed);
        let path = test_temp::root().join(format!("tiny-llm-{label}-{}-{id}", std::process::id()));
        fs::create_dir(&path).expect("create isolated test directory");
        Self(path)
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for TestDir {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn policy(root: &Path, allow_writes: bool, allowed_commands: Vec<Vec<String>>) -> ToolPolicy {
    ToolPolicy::new(
        root.to_path_buf(),
        ToolPolicy::DEFAULT_MAX_FILE_BYTES,
        ToolPolicy::DEFAULT_MAX_LIST_ENTRIES,
        allow_writes,
        allowed_commands,
        ToolPolicy::DEFAULT_MAX_WRITE_BYTES,
        ToolPolicy::DEFAULT_COMMAND_TIMEOUT_SECONDS,
    )
    .expect("valid test policy")
}

fn action(tool: &str, arguments: serde_json::Value) -> ToolAction {
    ToolAction {
        tool: tool.to_owned(),
        arguments: arguments
            .as_object()
            .expect("tool arguments must be an object")
            .clone(),
    }
}

#[derive(Debug)]
struct ScriptedCheckpointModel {
    responses: Vec<String>,
    response_index: usize,
    calls: Vec<Vec<Message>>,
    reuse: PrefixReuse,
}

#[derive(Debug, Clone)]
struct DenseCacheState {
    key_values: Option<Rc<Vec<i64>>>,
    offset: i64,
}

#[derive(Debug)]
struct DenseCache {
    object_id: u64,
    state: RefCell<DenseCacheState>,
}

impl DenseCache {
    fn empty() -> Self {
        Self {
            object_id: NEXT_CACHE_ID.fetch_add(1, Ordering::Relaxed),
            state: RefCell::new(DenseCacheState {
                key_values: None,
                offset: 0,
            }),
        }
    }

    fn key_values_id(&self) -> Option<usize> {
        self.state
            .borrow()
            .key_values
            .as_ref()
            .map(|values| Rc::as_ptr(values) as usize)
    }

    fn update(&self, tokens: &[i64], layer: i64) {
        let mut state = self.state.borrow_mut();
        let mut values = state
            .key_values
            .as_ref()
            .map_or_else(Vec::new, |values| (**values).clone());
        values.extend(tokens.iter().map(|token| token + layer));
        state.key_values = Some(Rc::new(values));
        state.offset += tokens.len() as i64;
    }
}

impl GenerationCache for DenseCache {
    fn release(&mut self) {
        self.state.get_mut().key_values = None;
    }

    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn offset(&self) -> i64 {
        self.state.borrow().offset
    }

    fn fork_box(&self) -> Result<Box<dyn GenerationCache>, AgentError> {
        Ok(Box::new(Self {
            object_id: NEXT_CACHE_ID.fetch_add(1, Ordering::Relaxed),
            state: RefCell::new(self.state.borrow().clone()),
        }))
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct DenseCall {
    offset: i64,
    size: usize,
    logits_to_keep: Option<usize>,
    cache_objects: Vec<u64>,
    before: Vec<Option<usize>>,
    after: Vec<Option<usize>>,
}

#[derive(Debug, Default)]
struct DenseEosModel {
    calls: Vec<DenseCall>,
}

impl GenerationModel for DenseEosModel {
    fn forward(
        &mut self,
        tokens: &[i64],
        offset: i64,
        caches: &mut [Box<dyn GenerationCache>],
        logits_to_keep: Option<usize>,
    ) -> Result<Vec<f32>, AgentError> {
        let cache_objects = caches
            .iter()
            .map(|cache| {
                cache
                    .as_any()
                    .downcast_ref::<DenseCache>()
                    .expect("dense cache")
                    .object_id
            })
            .collect::<Vec<_>>();
        let before = caches
            .iter()
            .map(|cache| {
                cache
                    .as_any()
                    .downcast_ref::<DenseCache>()
                    .expect("dense cache")
                    .key_values_id()
            })
            .collect::<Vec<_>>();
        for (layer, cache) in caches.iter().enumerate() {
            cache
                .as_any()
                .downcast_ref::<DenseCache>()
                .expect("dense cache")
                .update(tokens, layer as i64);
        }
        let after = caches
            .iter()
            .map(|cache| {
                cache
                    .as_any()
                    .downcast_ref::<DenseCache>()
                    .expect("dense cache")
                    .key_values_id()
            })
            .collect();
        self.calls.push(DenseCall {
            offset,
            size: tokens.len(),
            logits_to_keep,
            cache_objects,
            before,
            after,
        });

        // EOS (token zero) is the unique greedy maximum.
        let mut logits = vec![0.0; 128];
        logits[0] = 1.0;
        Ok(logits)
    }

    fn new_caches(&self) -> Result<Vec<Box<dyn GenerationCache>>, AgentError> {
        Ok(vec![
            Box::new(DenseCache::empty()),
            Box::new(DenseCache::empty()),
        ])
    }
}

#[derive(Debug, Default)]
struct CharacterTokenizer;

impl GenerationTokenizer for CharacterTokenizer {
    fn eos_token_id(&self) -> i64 {
        0
    }

    fn apply_chat_template(
        &mut self,
        messages: &[Message],
        tokenize: bool,
        add_generation_prompt: bool,
        enable_thinking: bool,
    ) -> Result<String, AgentError> {
        assert!(!tokenize);
        assert!(!enable_thinking);
        let mut rendered = String::new();
        for message in messages {
            rendered.push('<');
            rendered.push_str(&message["role"]);
            rendered.push('>');
            rendered.push_str(&message["content"]);
            rendered.push('\n');
        }
        if add_generation_prompt {
            rendered.push_str("<assistant>");
        }
        Ok(rendered)
    }

    fn encode(&mut self, prompt: &str, add_special_tokens: bool) -> Result<Vec<i64>, AgentError> {
        assert!(!add_special_tokens);
        Ok(prompt.chars().map(|character| character as i64).collect())
    }

    fn decode(&mut self, tokens: &[i64]) -> Result<String, AgentError> {
        tokens
            .iter()
            .map(|token| {
                char::from_u32(*token as u32)
                    .ok_or_else(|| AgentError("invalid character token".to_owned()))
            })
            .collect()
    }
}

fn message(role: &str, content: &str) -> Message {
    Message::from([
        ("role".to_owned(), role.to_owned()),
        ("content".to_owned(), content.to_owned()),
    ])
}

impl ScriptedCheckpointModel {
    fn new(responses: impl IntoIterator<Item = impl Into<String>>) -> Self {
        Self {
            responses: responses.into_iter().map(Into::into).collect(),
            response_index: 0,
            calls: Vec::new(),
            reuse: PrefixReuse {
                reused_tokens: 0,
                layer_offsets: vec![],
                avoided_prefill_tokens: 0,
            },
        }
    }

    fn tokens(messages: &[Message]) -> Vec<i64> {
        messages
            .iter()
            .map(|message| message["content"].chars().count() as i64)
            .collect()
    }
}

impl Generate for ScriptedCheckpointModel {
    fn generate(&mut self, messages: &[Message]) -> Result<String, AgentError> {
        self.calls.push(messages.to_vec());
        let response = self
            .responses
            .get(self.response_index)
            .cloned()
            .ok_or_else(|| AgentError("scripted model ran out of responses".to_owned()))?;
        self.response_index += 1;
        Ok(response)
    }

    fn save_checkpoint(&mut self, messages: &[Message]) -> Result<ModelCheckpoint, AgentError> {
        let tokens = Self::tokens(messages);
        ModelCheckpoint::new(
            messages.len() as i64,
            self.response_index as i64,
            tokens.clone(),
            vec![tokens.len() as i64, tokens.len() as i64],
        )
    }

    fn restore_checkpoint(&mut self, checkpoint: &ModelCheckpoint) -> Result<(), AgentError> {
        self.response_index = checkpoint.response_index as usize;
        self.reuse = PrefixReuse {
            reused_tokens: checkpoint.cached_token_ids.len() as i64,
            layer_offsets: checkpoint.layer_offsets.clone(),
            avoided_prefill_tokens: checkpoint.cached_token_ids.len() as i64,
        };
        Ok(())
    }

    fn prefix_reuse(&self) -> Option<(i64, Vec<i64>, i64)> {
        Some((
            self.reuse.reused_tokens,
            self.reuse.layer_offsets.clone(),
            self.reuse.avoided_prefill_tokens,
        ))
    }
}

#[test]
fn test_task_1_structured_denial_requires_and_exposes_one_operator_reason() {
    let temp = TestDir::new("day8-structured-denial");
    fs::write(temp.path().join("app.py"), b"answer = 2\n").expect("seed app.py");
    let receipts =
        ReceiptStore::new(Some(temp.path().join("receipts.jsonl"))).expect("create receipt store");
    let mut workspace = Workspace::new(
        policy(temp.path(), true, vec![]),
        Some(Box::new(|_action| {
            ConfirmResult::Decision(
                ApprovalDecision::new(false, "keep the requested answer at 2".to_owned())
                    .expect("valid structured denial"),
            )
        })),
        receipts,
    );
    workspace.read_file("app.py").expect("observe before edit");

    let result = workspace.execute(
        &action(
            "edit_file",
            json!({"path": "app.py", "old": "2", "new": "3"}),
        ),
        None,
    );
    // .expect("denial remains model-visible");

    assert_eq!(
        result,
        "error: operator denied the tool action: keep the requested answer at 2"
    );
    assert_eq!(result.matches("keep the requested answer at 2").count(), 1);
    assert_eq!(
        fs::read_to_string(temp.path().join("app.py")).expect("read app.py"),
        "answer = 2\n"
    );
    assert!(workspace.receipt_store.get("call-1").is_none());
    let error = ApprovalDecision::new(false, "  ".to_owned()).unwrap_err();
    assert!(error.to_string().contains("nonblank operator reason"));
}

#[test]
fn test_task_1_legacy_boolean_approval_remains_compatible() {
    let temp = TestDir::new("day8-bool-approval");
    fs::write(temp.path().join("app.py"), b"answer = 1\n").expect("seed app.py");
    let mut allowed = Workspace::new(
        policy(temp.path(), true, vec![]),
        Some(Box::new(|_action| ConfirmResult::Approved(true))),
        ReceiptStore::new(None).expect("receipt store"),
    );
    allowed.read_file("app.py").expect("observe before edit");
    assert_eq!(
        allowed.execute(
            &action(
                "edit_file",
                json!({"path": "app.py", "old": "1", "new": "2"}),
            ),
            None,
        ),
        // .expect("execute allowed edit"),
        "edited app.py"
    );

    let mut denied = Workspace::new(
        policy(temp.path(), true, vec![]),
        Some(Box::new(|_action| ConfirmResult::Approved(false))),
        ReceiptStore::new(None).expect("receipt store"),
    );
    denied.read_file("app.py").expect("observe before edit");
    assert_eq!(
        denied.execute(
            &action(
                "edit_file",
                json!({"path": "app.py", "old": "2", "new": "3"}),
            ),
            None,
        ),
        // .expect("execute denied edit"),
        "error: operator denied the tool action"
    );
}

#[test]
fn test_task_2_cached_prefix_is_prefilled_once_and_reused_by_both_forks() {
    let concrete_model = Rc::new(RefCell::new(DenseEosModel::default()));
    let model: Rc<RefCell<dyn GenerationModel>> = concrete_model.clone();
    let tokenizer: Rc<RefCell<dyn GenerationTokenizer>> = Rc::new(RefCell::new(CharacterTokenizer));
    let mut generator = KvPrefixGenerator::new(model, tokenizer, 4, false);
    let messages = vec![
        message("system", "system"),
        message("user", "task"),
        message("assistant", r#"{"tool":"read_file","path":"app.py"}"#),
        message("user", "Tool result:\nanswer = 2\n"),
    ];
    let checkpoint = generator
        .save_checkpoint(&messages)
        .expect("save dense prefix");
    let mut first = generator.fork();
    let mut second = generator.fork();
    first
        .restore_checkpoint(&checkpoint)
        .expect("restore first fork");
    second
        .restore_checkpoint(&checkpoint)
        .expect("restore second fork");

    let mut first_messages = messages.clone();
    first_messages.push(message("user", "Operator steering:\nvalidate"));
    let mut second_messages = messages.clone();
    second_messages.push(message("user", "Operator steering:\ninspect"));
    assert_eq!(first.call(&first_messages).expect("first continuation"), "");
    assert_eq!(
        second.call(&second_messages).expect("second continuation"),
        ""
    );

    let calls = &concrete_model.borrow().calls;
    assert_eq!(calls.len(), 3);
    let prefix_call = &calls[0];
    let first_call = &calls[1];
    let second_call = &calls[2];
    assert_eq!(prefix_call.offset, 0);
    assert_eq!(prefix_call.size, checkpoint.cached_token_ids.len());
    assert_eq!(prefix_call.logits_to_keep, Some(1));
    assert_eq!(first_call.logits_to_keep, Some(1));
    assert_eq!(second_call.logits_to_keep, Some(1));
    assert_eq!(first_call.offset, checkpoint.cached_token_ids.len() as i64);
    assert_eq!(second_call.offset, first_call.offset);
    assert!(
        first_call
            .cache_objects
            .iter()
            .zip(&second_call.cache_objects)
            .all(|(first_cache, second_cache)| first_cache != second_cache)
    );
    assert_eq!(first_call.before, prefix_call.after);
    assert_eq!(second_call.before, prefix_call.after);
    assert_ne!(first_call.after, first_call.before);
    assert_ne!(second_call.after, second_call.before);

    let expected = PrefixReuse {
        reused_tokens: checkpoint.cached_token_ids.len() as i64,
        layer_offsets: checkpoint.layer_offsets.clone(),
        avoided_prefill_tokens: checkpoint.cached_token_ids.len() as i64,
    };
    assert_eq!(first.reuse(), expected);
    assert_eq!(second.reuse(), expected);
    assert_eq!(
        checkpoint.layer_offsets,
        vec![
            checkpoint.cached_token_ids.len() as i64,
            checkpoint.cached_token_ids.len() as i64,
        ]
    );
}

#[test]
fn test_task_3_steered_prompt_must_extend_the_exact_saved_token_prefix() {
    let model: Rc<RefCell<dyn GenerationModel>> = Rc::new(RefCell::new(DenseEosModel::default()));
    let tokenizer: Rc<RefCell<dyn GenerationTokenizer>> = Rc::new(RefCell::new(CharacterTokenizer));
    let mut generator = KvPrefixGenerator::new(model, tokenizer, 2, false);
    let messages = vec![message("system", "system"), message("user", "task")];
    let checkpoint = generator.save_checkpoint(&messages).expect("save prefix");
    let mut branch = generator.fork();

    let foreign_model: Rc<RefCell<dyn GenerationModel>> =
        Rc::new(RefCell::new(DenseEosModel::default()));
    let foreign_tokenizer: Rc<RefCell<dyn GenerationTokenizer>> =
        Rc::new(RefCell::new(CharacterTokenizer));
    let mut foreign_generator = KvPrefixGenerator::new(foreign_model, foreign_tokenizer, 2, false);
    let foreign_checkpoint = foreign_generator
        .save_checkpoint(&[
            message("system", "foreign system"),
            message("user", "foreign task"),
        ])
        .expect("save foreign prefix");

    let error = branch.restore_checkpoint(&foreign_checkpoint).unwrap_err();
    assert!(
        error
            .to_string()
            .contains("does not match the saved KV prefix")
    );
    branch
        .restore_checkpoint(&checkpoint)
        .expect("restore matching prefix");
    let changed = vec![
        message("system", "changed"),
        message("user", "task"),
        message("user", "Operator steering:\ncontinue"),
    ];
    let error = branch.call(&changed).unwrap_err();
    assert!(
        error
            .to_string()
            .contains("does not extend the saved token prefix")
    );
}

fn forkable_effect(temp: &TestDir) -> (PathBuf, tiny_llm_agent::AgentCheckpoint) {
    let base = temp.path().join("base");
    fs::create_dir(&base).expect("create base branch");
    fs::write(base.join("app.py"), b"answer = 1\n").expect("seed app.py");
    let receipts =
        ReceiptStore::new(Some(base.join("receipts.jsonl"))).expect("create receipt store");
    let mut workspace = Workspace::new(
        policy(&base, true, vec![]),
        Some(Box::new(|_action| ConfirmResult::Approved(true))),
        receipts,
    );
    let mut model = ScriptedCheckpointModel::new([
        r#"{"tool":"read_file","path":"app.py"}"#,
        r#"{"tool":"edit_file","path":"app.py","old":"1","new":"2"}"#,
    ]);
    let checkpoint = run_to_checkpoint(
        "set answer = 2 and validate",
        &mut model,
        &mut workspace,
        2,
        None,
    )
    .expect("checkpoint after second tool result");
    (base, checkpoint)
}

fn copy_branch(
    base: &Path,
    destination: &Path,
    command: Vec<String>,
    approval: impl Fn(&ToolAction) -> ConfirmResult + 'static,
) -> (Workspace, ReceiptStore) {
    fs::create_dir(destination).expect("create branch directory");
    fs::copy(base.join("app.py"), destination.join("app.py")).expect("copy app.py");
    fs::copy(
        base.join("receipts.jsonl"),
        destination.join("receipts.jsonl"),
    )
    .expect("copy receipt history");
    let evaluation_receipts = ReceiptStore::new(Some(destination.join("receipts.jsonl")))
        .expect("load evaluation receipts");
    (
        Workspace::new(
            policy(destination, true, vec![command]),
            Some(Box::new(approval)),
            evaluation_receipts.clone(),
        ),
        evaluation_receipts,
    )
}

fn branch_case() -> EvaluationCase {
    EvaluationCase::new(
        "validated".to_owned(),
        vec![
            FileExpectation::new("app.py".to_owned(), "answer = 2\n".to_owned())
                .expect("file expectation"),
        ],
        vec![
            ResultExpectation::new("run_command".to_owned(), "validation passed".to_owned())
                .expect("result expectation"),
        ],
        vec![
            ReceiptExpectation::new(
                "call-1".to_owned(),
                "edit_file".to_owned(),
                "ok".to_owned(),
                "edited app.py".to_owned(),
                vec!["app.py".to_owned()],
            )
            .expect("edit receipt expectation"),
            ReceiptExpectation::new(
                "call-2".to_owned(),
                "run_command".to_owned(),
                "ok".to_owned(),
                "validation passed".to_owned(),
                vec![],
            )
            .expect("command receipt expectation"),
        ],
    )
    .expect("evaluation case")
}

#[test]
fn test_task_4_forks_effects_and_receipts_then_isolates_later_branch_evidence() {
    let temp = TestDir::new("day8-branches");
    let (base, checkpoint) = forkable_effect(&temp);
    let initial_receipts = fs::read(base.join("receipts.jsonl")).expect("base receipts");
    let command = vec![
        "/bin/sh".to_owned(),
        "-c".to_owned(),
        "grep -qx 'answer = 2' app.py && printf 'validation passed\\n'".to_owned(),
    ];
    let (mut validate_workspace, mut validate_receipts) = copy_branch(
        &base,
        &temp.path().join("validate-only"),
        command.clone(),
        |_action| ConfirmResult::Approved(true),
    );
    let (mut denied_workspace, mut denied_receipts) = copy_branch(
        &base,
        &temp.path().join("try-extra-edit"),
        command.clone(),
        |_action| {
            ConfirmResult::Decision(
                ApprovalDecision::new(false, "keep the requested answer at 2".to_owned())
                    .expect("valid denial"),
            )
        },
    );
    assert_eq!(
        fs::read(validate_receipts.path.as_ref().expect("receipt path")).expect("read receipts"),
        initial_receipts
    );
    assert_eq!(
        fs::read(denied_receipts.path.as_ref().expect("receipt path")).expect("read receipts"),
        initial_receipts
    );

    let case = branch_case();
    let command_response = json!({"tool": "run_command", "argv": command}).to_string();
    let mut validate_model = ScriptedCheckpointModel::new([
        "unused read".to_owned(),
        "unused edit".to_owned(),
        command_response,
        r#"{"final":"validated answer = 2"}"#.to_owned(),
    ]);
    let mut denied_model = ScriptedCheckpointModel::new([
        "unused read",
        "unused edit",
        r#"{"tool":"read_file","path":"app.py"}"#,
        r#"{"tool":"edit_file","path":"app.py","old":"2","new":"3"}"#,
        r#"{"final":"the extra edit was denied"}"#,
    ]);

    let passing = run_branch(
        "validate-only",
        "validate without another edit",
        &checkpoint,
        &mut validate_model,
        &mut validate_workspace,
        &mut validate_receipts,
        &case,
        None,
    )
    .expect("run passing branch");
    let failing = run_branch(
        "try-extra-edit",
        "try changing the answer again",
        &checkpoint,
        &mut denied_model,
        &mut denied_workspace,
        &mut denied_receipts,
        &case,
        None,
    )
    .expect("run denied branch");

    assert_eq!(passing.steering, "validate without another edit");
    assert_eq!(failing.steering, "try changing the answer again");
    assert_eq!(
        validate_model.calls[0].last().expect("steering message")["content"],
        "Operator steering:\nvalidate without another edit"
    );
    assert_eq!(
        denied_model.calls[0].last().expect("steering message")["content"],
        "Operator steering:\ntry changing the answer again"
    );
    assert_eq!(passing.reuse, validate_model.reuse);
    assert_eq!(failing.reuse, denied_model.reuse);
    assert!(passing.reuse.reused_tokens > 0);
    assert!(failing.reuse.reused_tokens > 0);
    assert!(passing.report.passed());
    assert!(!failing.report.passed());
    assert_eq!(
        select_branch(&[passing.clone(), failing.clone()], "validate-only")
            .expect("select passing branch"),
        passing
    );
    assert_eq!(
        fs::read_to_string(temp.path().join("validate-only/app.py")).expect("read branch file"),
        "answer = 2\n"
    );
    assert_eq!(
        fs::read_to_string(temp.path().join("try-extra-edit/app.py")).expect("read branch file"),
        "answer = 2\n"
    );
    assert_eq!(
        validate_workspace
            .receipt_store
            .get("call-1")
            .expect("base edit receipt")
            .tool,
        "edit_file"
    );
    assert_eq!(
        validate_workspace
            .receipt_store
            .get("call-2")
            .expect("validation receipt")
            .tool,
        "run_command"
    );
    assert_eq!(
        denied_workspace
            .receipt_store
            .get("call-1")
            .expect("base edit receipt")
            .tool,
        "edit_file"
    );
    assert!(denied_workspace.receipt_store.get("call-2").is_none());
    assert_eq!(
        fs::read(denied_receipts.path.as_ref().expect("receipt path")).expect("read receipts"),
        initial_receipts
    );
    assert!(
        fs::read(validate_receipts.path.as_ref().expect("receipt path"))
            .expect("read receipts")
            .starts_with(&initial_receipts)
    );
    let visible = denied_model
        .calls
        .iter()
        .flatten()
        .map(|message| message["content"].as_str())
        .collect::<Vec<_>>()
        .join("\n");
    assert_eq!(visible.matches("keep the requested answer at 2").count(), 1);
}

#[test]
fn test_task_5_selection_requires_one_named_passing_outcome() {
    let temp = TestDir::new("day8-selection");
    let (base, checkpoint) = forkable_effect(&temp);
    let command = vec!["/bin/sh".to_owned(), "-c".to_owned(), "exit 0".to_owned()];
    let (mut workspace, mut receipts) =
        copy_branch(&base, &temp.path().join("branch"), command, |_action| {
            ConfirmResult::Approved(true)
        });
    let mut model = ScriptedCheckpointModel::new(["unused", "unused", r#"{"final":"done"}"#]);
    let case =
        EvaluationCase::new("missing".to_owned(), vec![], vec![], vec![]).expect("evaluation case");
    let failing = run_branch(
        "candidate",
        "finish",
        &checkpoint,
        &mut model,
        &mut workspace,
        &mut receipts,
        &case,
        None,
    )
    .expect("run failing candidate");

    let error = select_branch(std::slice::from_ref(&failing), "absent").unwrap_err();
    assert!(error.to_string().contains("exactly one"));
    let error = select_branch(&[failing.clone(), failing.clone()], "candidate").unwrap_err();
    assert!(error.to_string().contains("exactly one"));
    let error = select_branch(std::slice::from_ref(&failing), "candidate").unwrap_err();
    assert!(error.to_string().contains("must pass"));
}
