// WARNING: Under review - generated by LLM.

//! Rust equivalents of `tests_refsol/test_week_4_day_3.py`.

#[path = "support/temp.rs"]
mod test_temp;

use std::cell::RefCell;
use std::collections::VecDeque;
use std::fs;
use std::path::{Path, PathBuf};
use std::rc::Rc;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

use serde_json::{Map, Value, json};
use tiny_llm_agent::generation::Message;
use tiny_llm_agent::workspace::ConfirmResult;
use tiny_llm_agent::{EffectReceipt, ReceiptStore, ToolAction, ToolPolicy, Workspace, run_agent};

static NEXT_TEMP_DIRECTORY: AtomicU64 = AtomicU64::new(0);

struct TestDirectory {
    path: PathBuf,
}

impl TestDirectory {
    fn new() -> Self {
        let sequence = NEXT_TEMP_DIRECTORY.fetch_add(1, Ordering::Relaxed);
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system clock must be after the Unix epoch")
            .as_nanos();
        let path = test_temp::root().join(format!(
            "tiny-llm-week4-day3-{}-{nanos}-{sequence}",
            std::process::id()
        ));
        fs::create_dir(&path).expect("create isolated test directory");
        Self { path }
    }

    fn path(&self) -> &Path {
        &self.path
    }
}

impl Drop for TestDirectory {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.path);
    }
}

fn json_arguments(value: Value) -> Map<String, Value> {
    value
        .as_object()
        .expect("test action arguments must be an object")
        .clone()
}

fn tool_action(tool: &str, arguments: Value) -> ToolAction {
    ToolAction {
        tool: tool.to_owned(),
        arguments: json_arguments(arguments),
    }
}

fn make_policy(root: &Path, allow_writes: bool, allowed_commands: Vec<Vec<String>>) -> ToolPolicy {
    ToolPolicy::new(
        root.to_path_buf(),
        ToolPolicy::DEFAULT_MAX_FILE_BYTES,
        ToolPolicy::DEFAULT_MAX_LIST_ENTRIES,
        allow_writes,
        allowed_commands,
        ToolPolicy::DEFAULT_MAX_WRITE_BYTES,
        ToolPolicy::DEFAULT_COMMAND_TIMEOUT_SECONDS,
    )
    .unwrap()
}

fn memory_store() -> ReceiptStore {
    ReceiptStore::new(None).unwrap()
}

fn read_only_workspace(root: &Path) -> Workspace {
    Workspace::new(make_policy(root, false, Vec::new()), None, memory_store())
}

fn string_vec(parts: &[&str]) -> Vec<String> {
    parts.iter().map(|part| (*part).to_owned()).collect()
}

#[test]
fn test_task_1_policy_enables_only_explicit_effects() {
    let temporary = TestDirectory::new();
    let command = string_vec(&["/bin/sh", "-c", "printf 'ok\\n'"]);
    let read_only = read_only_workspace(temporary.path());
    let enabled = Workspace::new(
        make_policy(temporary.path(), true, vec![command]),
        None,
        memory_store(),
    );

    assert_eq!(
        read_only.available_tools(),
        &["list_files".to_owned(), "read_file".to_owned()]
            .into_iter()
            .collect()
    );
    assert_eq!(
        enabled.available_tools(),
        &[
            "list_files".to_owned(),
            "read_file".to_owned(),
            "write_file".to_owned(),
            "edit_file".to_owned(),
            "run_command".to_owned(),
        ]
        .into_iter()
        .collect()
    );

    let max_write_error = ToolPolicy::new(
        temporary.path().to_path_buf(),
        ToolPolicy::DEFAULT_MAX_FILE_BYTES,
        ToolPolicy::DEFAULT_MAX_LIST_ENTRIES,
        false,
        Vec::new(),
        0,
        ToolPolicy::DEFAULT_COMMAND_TIMEOUT_SECONDS,
    )
    .unwrap_err();
    assert!(max_write_error.to_string().contains("positive"));

    for invalid_timeout in [0.0, -1.0, f64::NAN, f64::INFINITY, f64::NEG_INFINITY] {
        let error = ToolPolicy::new(
            temporary.path().to_path_buf(),
            ToolPolicy::DEFAULT_MAX_FILE_BYTES,
            ToolPolicy::DEFAULT_MAX_LIST_ENTRIES,
            false,
            Vec::new(),
            ToolPolicy::DEFAULT_MAX_WRITE_BYTES,
            invalid_timeout,
        )
        .unwrap_err();
        assert!(error.to_string().contains("finite and positive"));
    }

    let empty_command_error = ToolPolicy::new(
        temporary.path().to_path_buf(),
        ToolPolicy::DEFAULT_MAX_FILE_BYTES,
        ToolPolicy::DEFAULT_MAX_LIST_ENTRIES,
        false,
        vec![vec![String::new()]],
        ToolPolicy::DEFAULT_MAX_WRITE_BYTES,
        ToolPolicy::DEFAULT_COMMAND_TIMEOUT_SECONDS,
    )
    .unwrap_err();
    assert!(empty_command_error.to_string().contains("commands"));

    let nul_command_error = ToolPolicy::new(
        temporary.path().to_path_buf(),
        ToolPolicy::DEFAULT_MAX_FILE_BYTES,
        ToolPolicy::DEFAULT_MAX_LIST_ENTRIES,
        false,
        vec![vec!["validator\0".to_owned()]],
        ToolPolicy::DEFAULT_MAX_WRITE_BYTES,
        ToolPolicy::DEFAULT_COMMAND_TIMEOUT_SECONDS,
    )
    .unwrap_err();
    assert!(nul_command_error.to_string().contains("without NUL"));
}

#[test]
fn test_task_2_mutations_require_read_preflight_and_approval() {
    let temporary = TestDirectory::new();
    let source = temporary.path().join("app.py");
    fs::write(&source, "answer = 1\n").unwrap();
    let mut read_only = read_only_workspace(temporary.path());
    read_only.read_file("app.py").unwrap();
    let error = read_only.edit_file("app.py", "1", "2").unwrap_err();
    assert!(error.to_string().contains("writes are not enabled"));
    assert_eq!(fs::read_to_string(&source).unwrap(), "answer = 1\n");

    let approvals = Rc::new(RefCell::new(Vec::<ToolAction>::new()));
    let approvals_for_callback = Rc::clone(&approvals);
    let mut workspace = Workspace::new(
        make_policy(temporary.path(), true, Vec::new()),
        Some(Box::new(move |action| {
            approvals_for_callback.borrow_mut().push(action.clone());
            ConfirmResult::Approved(false)
        })),
        memory_store(),
    );
    let edit = tool_action(
        "edit_file",
        json!({"path": "app.py", "old": "1", "new": "2"}),
    );

    assert!(
        workspace
            .execute(&edit, None)
            .contains("read the existing file")
    );
    assert!(approvals.borrow().is_empty());
    assert_eq!(workspace.read_file("app.py").unwrap(), "answer = 1\n");
    assert!(workspace.execute(&edit, None).contains("operator denied"));
    assert_eq!(approvals.borrow().len(), 1);
    assert_eq!(fs::read_to_string(&source).unwrap(), "answer = 1\n");
    assert!(workspace.receipt_store.get("call-1").is_none());
}

#[test]
fn test_task_3_rechecks_stale_bytes_after_approval() {
    let temporary = TestDirectory::new();
    let source = temporary.path().join("app.py");
    fs::write(&source, "answer = 1\n").unwrap();
    let source_for_callback = source.clone();
    let mut workspace = Workspace::new(
        make_policy(temporary.path(), true, Vec::new()),
        Some(Box::new(move |_action| {
            fs::write(&source_for_callback, "answer = 9\n").unwrap();
            ConfirmResult::Approved(true)
        })),
        memory_store(),
    );
    workspace.read_file("app.py").unwrap();
    let result = workspace.execute(
        &tool_action(
            "edit_file",
            json!({"path": "app.py", "old": "1", "new": "2"}),
        ),
        None,
    );

    assert_eq!(result, "error: file changed since it was read");
    assert_eq!(fs::read_to_string(&source).unwrap(), "answer = 9\n");
    assert!(workspace.modified_files().is_empty());
}

#[test]
fn test_task_4_exact_edit_uses_same_directory_replace_and_receipt() {
    let temporary = TestDirectory::new();
    let source = temporary.path().join("app.py");
    fs::write(&source, "answer = 1\n").unwrap();
    // A hard link detects in-place rewrites without a production test hook.
    let old_inode = temporary.path().join("original-app.py");
    fs::hard_link(&source, &old_inode).unwrap();
    let store_path = temporary.path().join("receipts.jsonl");
    let store = ReceiptStore::new(Some(store_path.clone())).unwrap();
    let mut workspace = Workspace::new(
        make_policy(temporary.path(), true, Vec::new()),
        Some(Box::new(|_action| ConfirmResult::Approved(true))),
        store,
    );
    workspace.read_file("app.py").unwrap();
    let result = workspace.execute(
        &tool_action(
            "edit_file",
            json!({"path": "./app.py", "old": "1", "new": "2"}),
        ),
        Some("edit-1"),
    );

    assert_eq!(result, "edited app.py");
    assert_eq!(fs::read_to_string(&source).unwrap(), "answer = 2\n");
    assert_eq!(fs::read(&old_inode).unwrap(), b"answer = 1\n");
    fs::remove_file(&old_inode).unwrap();
    assert_eq!(workspace.modified_files(), vec!["app.py"]);
    assert_eq!(
        workspace
            .receipt_store
            .get("edit-1")
            .unwrap()
            .changed_artifacts,
        vec!["app.py"]
    );

    // Python monkeypatches `os.replace` to observe both arguments directly.
    // The directory listing checks cleanup. Exact rename source/destination
    // instrumentation requires an injectable filesystem boundary; see README.md.
    let mut names = fs::read_dir(temporary.path())
        .unwrap()
        .map(|entry| entry.unwrap().file_name().to_string_lossy().into_owned())
        .collect::<Vec<_>>();
    names.sort();
    assert_eq!(names, vec!["app.py", "receipts.jsonl"]);
}

#[test]
fn test_task_5_write_creates_new_files_but_observes_existing_files() {
    let temporary = TestDirectory::new();
    let store = memory_store();
    let mut workspace = Workspace::new(
        make_policy(temporary.path(), true, Vec::new()),
        Some(Box::new(|_action| ConfirmResult::Approved(true))),
        store,
    );
    let create = tool_action("write_file", json!({"path": "new.txt", "content": "new\n"}));

    assert_eq!(
        workspace.execute(&create, Some("write-new")),
        "wrote new.txt"
    );
    assert_eq!(
        fs::read_to_string(temporary.path().join("new.txt")).unwrap(),
        "new\n"
    );

    let overwrite = tool_action(
        "write_file",
        json!({"path": "new.txt", "content": "replacement\n"}),
    );
    let mut other = Workspace::new(
        make_policy(temporary.path(), true, Vec::new()),
        Some(Box::new(|_action| ConfirmResult::Approved(true))),
        memory_store(),
    );
    assert!(
        other
            .execute(&overwrite, None)
            .contains("read the existing file")
    );
    other.read_file("new.txt").unwrap();
    assert_eq!(other.execute(&overwrite, None), "wrote new.txt");
}

#[test]
fn test_task_6_validation_uses_exact_argv_and_records_output() {
    let temporary = TestDirectory::new();
    let allowed = string_vec(&["/bin/sh", "-c", "printf 'focused fail\\n'; exit 3"]);
    let approvals = Rc::new(RefCell::new(Vec::<ToolAction>::new()));
    let approvals_for_callback = Rc::clone(&approvals);
    let store = memory_store();
    let mut workspace = Workspace::new(
        make_policy(temporary.path(), false, vec![allowed.clone()]),
        Some(Box::new(move |action| {
            approvals_for_callback.borrow_mut().push(action.clone());
            ConfirmResult::Approved(true)
        })),
        store,
    );

    let denied = workspace.execute(
        &tool_action("run_command", json!({"argv": ["echo", "no"]})),
        None,
    );
    let nul_denied = workspace.execute(
        &tool_action(
            "run_command",
            json!({"argv": ["/bin/sh", "bad\u{0}argument"]}),
        ),
        None,
    );
    let result = workspace.execute(
        &tool_action("run_command", json!({"argv": allowed})),
        Some("validate-1"),
    );
    let receipt = workspace.receipt_store.get("validate-1").unwrap();

    assert_eq!(denied, "error: command is not allowed");
    assert_eq!(
        nul_denied,
        "error: argv must contain non-empty strings without NUL"
    );
    assert_eq!(approvals.borrow().len(), 1);
    assert_eq!(result, "status: 3\noutput:\nfocused fail\n");
    assert_eq!(
        receipt.arguments,
        json_arguments(json!({
            "argv": ["/bin/sh", "-c", "printf 'focused fail\\n'; exit 3"]
        }))
    );
    assert_eq!(receipt.exit_state, "error");
    assert_eq!(receipt.result, result);
    assert!(receipt.changed_artifacts.is_empty());
}

#[test]
fn test_task_7_duplicate_call_ids_do_not_repeat_an_effect() {
    let temporary = TestDirectory::new();
    let allowed = string_vec(&[
        "/bin/sh",
        "-c",
        "printf x >> command-count; printf 'pass\\n'",
    ]);
    let mut workspace = Workspace::new(
        make_policy(temporary.path(), false, vec![allowed.clone()]),
        Some(Box::new(|_action| ConfirmResult::Approved(true))),
        memory_store(),
    );
    let action = tool_action("run_command", json!({"argv": allowed}));

    let first = workspace.execute(&action, Some("same-call"));
    let second = workspace.execute(&action, Some("same-call"));

    assert_eq!(first, "status: 0\noutput:\npass\n");
    assert_eq!(second, first);
    assert_eq!(
        fs::read_to_string(temporary.path().join("command-count")).unwrap(),
        "x",
        "an idempotent retry must not execute the command again"
    );
    let conflict = workspace.execute(
        &tool_action("run_command", json!({"argv": ["different"]})),
        Some("same-call"),
    );
    assert!(conflict.contains("already used"));
}

#[test]
fn test_task_8_jsonl_receipts_reopen_and_detect_tampering() {
    let temporary = TestDirectory::new();
    let path = temporary.path().join("receipts.jsonl");
    let receipt = EffectReceipt::new(
        "edit-1".to_owned(),
        "edit_file".to_owned(),
        json_arguments(json!({"path": "app.py", "old": "1", "new": "2"})),
        "ok".to_owned(),
        "edited app.py".to_owned(),
        vec!["app.py".to_owned()],
    )
    .unwrap();
    ReceiptStore::new(Some(path.clone()))
        .unwrap()
        .put(receipt.clone())
        .unwrap();

    assert_eq!(
        ReceiptStore::new(Some(path.clone())).unwrap().get("edit-1"),
        Some(&receipt)
    );
    let line = fs::read_to_string(&path).unwrap();
    let mut payload: Value = serde_json::from_str(&line).unwrap();
    payload
        .as_object_mut()
        .unwrap()
        .insert("result".to_owned(), json!("edited another.py"));
    fs::write(
        &path,
        format!("{}\n", serde_json::to_string(&payload).unwrap()),
    )
    .unwrap();

    let error = ReceiptStore::new(Some(path)).unwrap_err();
    assert!(error.to_string().contains("digest"));
}

#[test]
fn test_task_9_agent_reads_edits_validates_and_finishes() {
    let temporary = TestDirectory::new();
    let source = temporary.path().join("app.py");
    fs::write(&source, "answer = 1\n").unwrap();
    let validation = string_vec(&["/bin/sh", "-c", "printf 'answer = 2\\n' | cmp -s - app.py"]);
    let approved = Rc::new(RefCell::new(Vec::<String>::new()));
    let approved_for_callback = Rc::clone(&approved);
    let store = ReceiptStore::new(Some(temporary.path().join("receipts.jsonl"))).unwrap();
    let mut workspace = Workspace::new(
        make_policy(temporary.path(), true, vec![validation.clone()]),
        Some(Box::new(move |action| {
            approved_for_callback.borrow_mut().push(action.tool.clone());
            ConfirmResult::Approved(true)
        })),
        store,
    );
    let command_response = serde_json::to_string(&json!({
        "tool": "run_command",
        "argv": validation,
    }))
    .unwrap();
    let responses = RefCell::new(VecDeque::from([
        r#"{"tool":"read_file","path":"app.py"}"#.to_owned(),
        r#"{"tool":"edit_file","path":"app.py","old":"1","new":"2"}"#.to_owned(),
        command_response,
        r#"{"final":"changed and validated app.py"}"#.to_owned(),
    ]));
    let mut generate = |_messages: &[Message]| {
        responses
            .borrow_mut()
            .pop_front()
            .expect("scripted response queue exhausted")
    };

    let result = run_agent(
        Some("fix app.py"),
        &mut generate,
        &mut workspace,
        None,
        None,
    )
    .unwrap();

    assert!(result.completed);
    assert_eq!(
        result.final_.as_deref(),
        Some("changed and validated app.py")
    );
    assert_eq!(workspace.modified_files(), vec!["app.py"]);
    assert_eq!(approved.borrow().as_slice(), ["edit_file", "run_command"]);
    assert_eq!(
        workspace
            .receipt_store
            .get("call-1")
            .unwrap()
            .changed_artifacts,
        vec!["app.py"]
    );
    assert_eq!(
        workspace.receipt_store.get("call-2").unwrap().arguments,
        json_arguments(json!({
            "argv": [
                "/bin/sh",
                "-c",
                "printf 'answer = 2\\n' | cmp -s - app.py"
            ]
        }))
    );
    assert!(
        workspace
            .receipt_store
            .get("call-2")
            .unwrap()
            .changed_artifacts
            .is_empty()
    );
}
