// WARNING: Under review - generated by LLM.

//! Rust equivalents of `tests_refsol/test_week_4_day_1.py`.

#[path = "support/temp.rs"]
mod test_temp;

use std::cell::{Cell, RefCell};
use std::collections::{HashSet, VecDeque};
use std::path::PathBuf;
use std::rc::Rc;

use serde_json::{Map, Value, json};
use tiny_llm_agent::generation::{
    GenerationCache, GenerationModel, GenerationTokenizer, Message, generate_response,
    initial_messages,
};
use tiny_llm_agent::protocol::AgentWorkspace;
use tiny_llm_agent::{AgentError, AgentLimits, ToolAction, ToolPolicy, run_agent};

fn json_arguments(value: Value) -> Map<String, Value> {
    value
        .as_object()
        .expect("test action arguments must be a JSON object")
        .clone()
}

fn tool_action(tool: &str, arguments: Value) -> ToolAction {
    ToolAction {
        tool: tool.to_owned(),
        arguments: json_arguments(arguments),
    }
}

fn message(role: &str, content: &str) -> Message {
    [
        ("role".to_owned(), role.to_owned()),
        ("content".to_owned(), content.to_owned()),
    ]
    .into_iter()
    .collect()
}

fn policy_with_tools(root: &str) -> ToolPolicy {
    ToolPolicy {
        root: PathBuf::from(root),
        max_file_bytes: ToolPolicy::DEFAULT_MAX_FILE_BYTES,
        max_list_entries: ToolPolicy::DEFAULT_MAX_LIST_ENTRIES,
        allow_writes: false,
        allowed_commands: Vec::new(),
        max_write_bytes: ToolPolicy::DEFAULT_MAX_WRITE_BYTES,
        command_timeout_seconds: ToolPolicy::DEFAULT_COMMAND_TIMEOUT_SECONDS,
    }
}

/// Minimal Day 1 tool boundary; later days exercise the real workspace.
struct FakeWorkspace {
    policy: ToolPolicy,
    available_tools: HashSet<String>,
    executed: Vec<ToolAction>,
}

impl FakeWorkspace {
    fn new(root: &str) -> Self {
        Self {
            policy: policy_with_tools(root),
            available_tools: HashSet::from(["read_file".to_owned()]),
            executed: Vec::new(),
        }
    }
}

impl AgentWorkspace for FakeWorkspace {
    fn policy(&self) -> &ToolPolicy {
        &self.policy
    }

    fn available_tools(&self) -> &HashSet<String> {
        &self.available_tools
    }

    fn modified_files(&self) -> Vec<String> {
        Vec::new()
    }

    fn execute(
        &mut self,
        action: &ToolAction,
        _tool_call_id: Option<&str>,
    ) -> String {
        self.executed.push(action.clone());
        "README contents".to_owned()
    }
}

fn scripted_responses(items: &[&str]) -> impl Fn(&[Message]) -> String {
    let queue = RefCell::new(
        items
            .iter()
            .map(|item| (*item).to_owned())
            .collect::<VecDeque<_>>(),
    );
    move |_messages| {
        queue
            .borrow_mut()
            .pop_front()
            .expect("scripted response queue exhausted")
    }
}

fn limits(
    max_steps: i64,
    max_context_chars: i64,
    max_invalid_actions: i64,
    max_identical_actions: i64,
) -> AgentLimits {
    AgentLimits::new(
        max_steps,
        max_context_chars,
        max_invalid_actions,
        max_identical_actions,
    )
    .expect("test limits must be valid")
}

#[test]
fn test_task_1_initial_messages_preserve_the_task() {
    let messages = initial_messages("inspect the project", "system instructions").unwrap();

    assert_eq!(
        messages,
        vec![
            message("system", "system instructions"),
            message("user", "inspect the project"),
        ]
    );
}

#[test]
fn test_task_1_rejects_an_empty_task() {
    let error = initial_messages("   ", "system instructions").unwrap_err();

    assert!(error.to_string().contains("must not be empty"));
}

#[test]
fn test_task_2_executes_a_tool_appends_its_result_and_finishes() {
    let mut workspace = FakeWorkspace::new(test_temp::root().to_str().unwrap());
    let mut generate = scripted_responses(&[
        r#"{"tool":"read_file","path":"README.md"}"#,
        r#"{"final":"inspected README"}"#,
    ]);

    let result = run_agent(
        Some("inspect the project"),
        &mut generate,
        &mut workspace,
        None,
        None,
    )
    .unwrap();

    assert!(result.completed);
    assert_eq!(result.reason, "completed");
    assert_eq!(result.final_.as_deref(), Some("inspected README"));
    assert_eq!(
        workspace.executed,
        vec![tool_action("read_file", json!({"path": "README.md"}))]
    );
}

#[test]
fn test_task_3_returns_invalid_and_unknown_actions_to_the_model() {
    let mut workspace = FakeWorkspace::new(test_temp::root().to_str().unwrap());
    let mut generate = scripted_responses(&[
        "not json",
        r#"{"tool":"run_shell","argv":["rm","-rf","."]}"#,
        r#"{"final":"recovered"}"#,
    ]);

    let result = run_agent(
        Some("inspect the project"),
        &mut generate,
        &mut workspace,
        None,
        None,
    )
    .unwrap();

    assert!(result.completed);
    assert!(workspace.executed.is_empty());
    assert!(
        result.events[..2]
            .iter()
            .all(|event| event.action.is_none())
    );
    assert!(result.events[..2].iter().all(|event| {
        event
            .result
            .as_deref()
            .is_some_and(|result| result.starts_with("error:"))
    }));
}

#[test]
fn test_task_4_stops_at_the_step_budget() {
    let mut workspace = FakeWorkspace::new(test_temp::root().to_str().unwrap());
    let mut generate =
        |_messages: &[Message]| r#"{"tool":"read_file","path":"README.md"}"#.to_owned();
    let run_limits = limits(2, 48_000, 3, 3);

    let result = run_agent(
        Some("inspect the project"),
        &mut generate,
        &mut workspace,
        Some(&run_limits),
        None,
    )
    .unwrap();

    assert!(!result.completed);
    assert_eq!(result.reason, "step_limit");
    assert_eq!(result.events.len(), 2);
    assert_eq!(workspace.executed.len(), 2);
}

#[test]
fn test_task_5_agent_observes_then_finishes() {
    let mut workspace = FakeWorkspace::new(test_temp::root().to_str().unwrap());
    let mut generate = scripted_responses(&[
        r#"{"tool":"read_file","path":"README.md"}"#,
        r#"{"final":"inspected README"}"#,
    ]);

    let result = run_agent(
        Some("inspect the project"),
        &mut generate,
        &mut workspace,
        None,
        None,
    )
    .unwrap();

    assert!(result.completed);
    assert_eq!(result.final_.as_deref(), Some("inspected README"));
    assert_eq!(result.reason, "completed");
    assert_eq!(result.events.len(), 2);
}

#[test]
fn test_task_6_agent_recovers_from_invalid_json() {
    let mut workspace = FakeWorkspace::new(test_temp::root().to_str().unwrap());
    let mut generate = scripted_responses(&["not json", r#"{"final":"recovered"}"#]);

    let result = run_agent(
        Some("inspect the project"),
        &mut generate,
        &mut workspace,
        None,
        None,
    )
    .unwrap();

    assert!(result.completed);
    assert!(
        result.events[0]
            .result
            .as_deref()
            .unwrap()
            .starts_with("error:")
    );
}

#[test]
fn test_task_7_agent_stops_repeated_actions() {
    let mut workspace = FakeWorkspace::new(test_temp::root().to_str().unwrap());
    let mut generate = scripted_responses(&[
        r#"{"tool":"read_file","path":"README.md"}"#,
        r#"{"tool":"read_file","path":"README.md"}"#,
        r#"{"tool":"read_file","path":"README.md"}"#,
    ]);
    let run_limits = limits(5, 48_000, 3, 2);

    let result = run_agent(
        Some("inspect the project"),
        &mut generate,
        &mut workspace,
        Some(&run_limits),
        None,
    )
    .unwrap();

    assert!(!result.completed);
    assert_eq!(result.reason, "repeated_action_limit");
}

fn assert_exact_observation_payload() {
    let mut workspace = FakeWorkspace::new(test_temp::root().to_str().unwrap());
    let seen = RefCell::new(Vec::<Vec<Message>>::new());
    let mut generate = |messages: &[Message]| {
        let mut seen = seen.borrow_mut();
        seen.push(messages.to_vec());
        if seen.len() == 1 {
            r#"{"tool":"read_file","path":"README.md"}"#.to_owned()
        } else {
            r#"{"final":"done"}"#.to_owned()
        }
    };

    let result = run_agent(Some("inspect"), &mut generate, &mut workspace, None, None).unwrap();

    assert!(result.completed);
    assert_eq!(
        seen.borrow()[1].last(),
        Some(&message("user", "Tool result:\nREADME contents")),
        "the exact tool-result payload must reach the next model input"
    );
}

#[test]
fn test_task_8_observation_propagation() {
    assert_exact_observation_payload();
}

#[test]
fn test_task_8_known_but_disabled_tool_is_rejected() {
    let mut workspace = FakeWorkspace::new(test_temp::root().to_str().unwrap());
    let mut generate = scripted_responses(&[
        r#"{"tool":"write_file","path":"x","content":"y"}"#,
        r#"{"final":"recovered"}"#,
    ]);

    let result = run_agent(Some("inspect"), &mut generate, &mut workspace, None, None).unwrap();

    assert!(result.completed);
    assert!(workspace.executed.is_empty());
    let error = result.events[0].result.as_deref().unwrap();
    assert!(error.starts_with("error:"));
    assert!(error.contains("not enabled"));
}

#[test]
fn test_task_9_positive_limit_fails_closed() {
    for values in [
        (0, 48_000, 3, 2),
        (8, 0, 3, 2),
        (8, 48_000, 0, 2),
        (8, 48_000, 3, 0),
    ] {
        let error = AgentLimits::new(values.0, values.1, values.2, values.3).unwrap_err();
        assert!(error.to_string().contains("positive"));
    }
}

#[test]
fn test_task_9_context_limit_stops_the_loop() {
    let mut workspace = FakeWorkspace::new(test_temp::root().to_str().unwrap());
    let mut generate =
        |_messages: &[Message]| r#"{"tool":"read_file","path":"README.md"}"#.to_owned();
    let run_limits = limits(3, 10, 3, 2);

    let result = run_agent(
        Some("inspect"),
        &mut generate,
        &mut workspace,
        Some(&run_limits),
        None,
    )
    .unwrap();

    assert!(!result.completed);
    assert_eq!(result.reason, "context_limit");
}

#[test]
fn test_task_9_invalid_action_limit_stops_the_loop() {
    let mut workspace = FakeWorkspace::new(test_temp::root().to_str().unwrap());
    let mut generate = |_messages: &[Message]| "not json".to_owned();
    let run_limits = limits(5, 48_000, 2, 2);

    let result = run_agent(
        Some("inspect"),
        &mut generate,
        &mut workspace,
        Some(&run_limits),
        None,
    )
    .unwrap();

    assert!(!result.completed);
    assert_eq!(result.reason, "invalid_action_limit");
}

#[derive(Default)]
struct FakeTokenizer {
    template_calls: Vec<(Vec<Message>, bool, bool, bool)>,
    encode_calls: Vec<(String, bool)>,
    decoded: Vec<Vec<i64>>,
}

impl GenerationTokenizer for FakeTokenizer {
    fn eos_token_id(&self) -> i64 {
        0
    }

    fn apply_chat_template(
        &mut self,
        messages: &[Message],
        tokenize: bool,
        add_generation_prompt: bool,
        enable_thinking: bool,
    ) -> Result<String, AgentError> {
        self.template_calls.push((
            messages.to_vec(),
            tokenize,
            add_generation_prompt,
            enable_thinking,
        ));
        Ok("rendered prompt".to_owned())
    }

    fn encode(&mut self, prompt: &str, add_special_tokens: bool) -> Result<Vec<i64>, AgentError> {
        self.encode_calls
            .push((prompt.to_owned(), add_special_tokens));
        Ok(vec![10, 11, 12])
    }

    fn decode(&mut self, tokens: &[i64]) -> Result<String, AgentError> {
        self.decoded.push(tokens.to_vec());
        Ok(format!(
            "decoded:{}",
            tokens
                .iter()
                .map(i64::to_string)
                .collect::<Vec<_>>()
                .join(",")
        ))
    }
}

struct FakeCache {
    id: usize,
    releases: Rc<Cell<usize>>,
}

impl GenerationCache for FakeCache {
    fn release(&mut self) {
        self.releases.set(self.releases.get() + 1);
    }

    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
}

#[derive(Debug, PartialEq, Eq)]
struct ModelCall {
    tokens: Vec<i64>,
    offset: i64,
    cache_ids: Vec<usize>,
}

struct TokenModel {
    tokens: VecDeque<Result<i64, AgentError>>,
    calls: Vec<ModelCall>,
}

impl TokenModel {
    fn new(tokens: impl IntoIterator<Item = i64>) -> Self {
        Self {
            tokens: tokens.into_iter().map(Ok).collect(),
            calls: Vec::new(),
        }
    }

    fn failing(message: &str) -> Self {
        Self {
            tokens: VecDeque::from([Err(AgentError(message.to_owned()))]),
            calls: Vec::new(),
        }
    }
}

impl GenerationModel for TokenModel {
    fn forward(
        &mut self,
        tokens: &[i64],
        offset: i64,
        caches: &mut [Box<dyn GenerationCache>],
        _logits_to_keep: Option<usize>,
    ) -> Result<Vec<f32>, AgentError> {
        let cache_ids = caches
            .iter()
            .map(|cache| {
                cache
                    .as_any()
                    .downcast_ref::<FakeCache>()
                    .expect("test model expects FakeCache")
                    .id
            })
            .collect();
        self.calls.push(ModelCall {
            tokens: tokens.to_vec(),
            offset,
            cache_ids,
        });
        let token = self
            .tokens
            .pop_front()
            .expect("scripted token queue exhausted")?;
        let mut logits = vec![-1.0; 128];
        logits[token as usize] = 1.0;
        Ok(logits)
    }
}

#[test]
fn test_task_10_generation_uses_the_exact_prompt_offsets_eos_and_releases() {
    let messages = vec![message("user", "finish the task")];
    let mut tokenizer = FakeTokenizer::default();
    let mut model = TokenModel::new([65, 66, 0]);
    let release_counts = [Rc::new(Cell::new(0)), Rc::new(Cell::new(0))];
    let mut cache_factory = || {
        release_counts
            .iter()
            .enumerate()
            .map(|(id, releases)| {
                Box::new(FakeCache {
                    id,
                    releases: Rc::clone(releases),
                }) as Box<dyn GenerationCache>
            })
            .collect()
    };

    let result = generate_response(
        &mut model,
        &mut tokenizer,
        &messages,
        &mut cache_factory,
        5,
        true,
    )
    .unwrap();

    assert_eq!(result, "decoded:65,66");
    assert_eq!(
        tokenizer.template_calls,
        vec![(messages, false, true, true)]
    );
    assert_eq!(
        tokenizer.encode_calls,
        vec![("rendered prompt".to_owned(), false)]
    );
    assert_eq!(tokenizer.decoded, vec![vec![65, 66]]);
    assert_eq!(
        model.calls,
        vec![
            ModelCall {
                tokens: vec![10, 11, 12],
                offset: 0,
                cache_ids: vec![0, 1],
            },
            ModelCall {
                tokens: vec![65],
                offset: 3,
                cache_ids: vec![0, 1],
            },
            ModelCall {
                tokens: vec![66],
                offset: 4,
                cache_ids: vec![0, 1],
            },
        ]
    );
    assert_eq!(release_counts.map(|releases| releases.get()), [1, 1]);
}

#[test]
fn test_task_10_generation_is_bounded_and_uses_one_fresh_cache_per_call() {
    let mut tokenizer = FakeTokenizer::default();
    let cache_factory_calls = Rc::new(Cell::new(0));
    let next_cache_id = Rc::new(Cell::new(0));
    let releases = Rc::new(RefCell::new(Vec::<Rc<Cell<usize>>>::new()));
    let mut cache_factory = || {
        cache_factory_calls.set(cache_factory_calls.get() + 1);
        let release = Rc::new(Cell::new(0));
        releases.borrow_mut().push(Rc::clone(&release));
        let id = next_cache_id.get();
        next_cache_id.set(id + 1);
        vec![Box::new(FakeCache {
            id,
            releases: release,
        }) as Box<dyn GenerationCache>]
    };

    let error = generate_response(
        &mut TokenModel::new([7]),
        &mut tokenizer,
        &[],
        &mut cache_factory,
        0,
        false,
    )
    .unwrap_err();
    assert!(error.to_string().contains("max_tokens must be positive"));
    assert_eq!(cache_factory_calls.get(), 0);

    let first = generate_response(
        &mut TokenModel::new([7, 8, 9]),
        &mut tokenizer,
        &[],
        &mut cache_factory,
        2,
        false,
    )
    .unwrap();
    let second = generate_response(
        &mut TokenModel::new([9]),
        &mut tokenizer,
        &[],
        &mut cache_factory,
        1,
        false,
    )
    .unwrap();

    assert_eq!(first, "decoded:7,8");
    assert_eq!(second, "decoded:9");
    assert_eq!(cache_factory_calls.get(), 2);
    assert_eq!(
        releases
            .borrow()
            .iter()
            .map(|release| release.get())
            .collect::<Vec<_>>(),
        vec![1, 1]
    );
}

#[test]
fn test_task_10_generation_releases_every_cache_when_the_model_fails() {
    let mut tokenizer = FakeTokenizer::default();
    let mut model = TokenModel::failing("model failed");
    let release_counts = [Rc::new(Cell::new(0)), Rc::new(Cell::new(0))];
    let mut cache_factory = || {
        release_counts
            .iter()
            .enumerate()
            .map(|(id, releases)| {
                Box::new(FakeCache {
                    id,
                    releases: Rc::clone(releases),
                }) as Box<dyn GenerationCache>
            })
            .collect()
    };

    let error = generate_response(
        &mut model,
        &mut tokenizer,
        &[],
        &mut cache_factory,
        1,
        false,
    )
    .unwrap_err();

    assert!(error.to_string().contains("model failed"));
    assert_eq!(release_counts.map(|releases| releases.get()), [1, 1]);
}
