// WARNING: Under review - generated by LLM.

//! Rust equivalents of `tests_refsol/test_week_4_day_2.py`.

#[path = "support/temp.rs"]
mod test_temp;

use std::cell::RefCell;
use std::collections::VecDeque;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

use serde_json::{Map, Value, json};
use tiny_llm_agent::generation::Message;
use tiny_llm_agent::protocol::AgentAction;
use tiny_llm_agent::{
    ReceiptStore, ToolAction, ToolPolicy, Workspace, build_system_prompt, parse_action, run_agent,
};

static NEXT_TEMP_DIRECTORY: AtomicU64 = AtomicU64::new(0);

struct TestDirectory {
    path: PathBuf,
}

impl TestDirectory {
    fn new() -> Self {
        let sequence = NEXT_TEMP_DIRECTORY.fetch_add(1, Ordering::Relaxed);
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system clock must be after the Unix epoch")
            .as_nanos();
        let path = test_temp::root().join(format!(
            "tiny-llm-week4-day2-{}-{nanos}-{sequence}",
            std::process::id()
        ));
        fs::create_dir(&path).expect("create isolated test directory");
        Self { path }
    }

    fn path(&self) -> &Path {
        &self.path
    }
}

impl Drop for TestDirectory {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.path);
    }
}

fn policy(root: &Path, max_file_bytes: i64, max_list_entries: i64) -> ToolPolicy {
    ToolPolicy::new(
        root.to_path_buf(),
        max_file_bytes,
        max_list_entries,
        false,
        Vec::new(),
        ToolPolicy::DEFAULT_MAX_WRITE_BYTES,
        ToolPolicy::DEFAULT_COMMAND_TIMEOUT_SECONDS,
    )
    .unwrap()
}

fn make_workspace(root: &Path) -> Workspace {
    make_bounded_workspace(
        root,
        ToolPolicy::DEFAULT_MAX_FILE_BYTES,
        ToolPolicy::DEFAULT_MAX_LIST_ENTRIES,
    )
}

fn make_bounded_workspace(root: &Path, max_file_bytes: i64, max_list_entries: i64) -> Workspace {
    Workspace::new(
        policy(root, max_file_bytes, max_list_entries),
        None,
        ReceiptStore::new(None).unwrap(),
    )
}

fn json_arguments(value: Value) -> Map<String, Value> {
    value
        .as_object()
        .expect("test action arguments must be an object")
        .clone()
}

fn tool_action(tool: &str, arguments: Value) -> ToolAction {
    ToolAction {
        tool: tool.to_owned(),
        arguments: json_arguments(arguments),
    }
}

fn message(role: &str, content: &str) -> Message {
    [
        ("role".to_owned(), role.to_owned()),
        ("content".to_owned(), content.to_owned()),
    ]
    .into_iter()
    .collect()
}

#[test]
fn test_task_1_policy_requires_a_directory_and_positive_limits() {
    let temporary = TestDirectory::new();
    let root = temporary.path().join("workspace");
    fs::create_dir(&root).unwrap();

    let normalized = ToolPolicy::new(
        root.join("."),
        ToolPolicy::DEFAULT_MAX_FILE_BYTES,
        ToolPolicy::DEFAULT_MAX_LIST_ENTRIES,
        false,
        Vec::new(),
        ToolPolicy::DEFAULT_MAX_WRITE_BYTES,
        ToolPolicy::DEFAULT_COMMAND_TIMEOUT_SECONDS,
    )
    .unwrap();
    assert_eq!(normalized.root, fs::canonicalize(&root).unwrap());

    let missing = ToolPolicy::new(
        temporary.path().join("missing"),
        ToolPolicy::DEFAULT_MAX_FILE_BYTES,
        ToolPolicy::DEFAULT_MAX_LIST_ENTRIES,
        false,
        Vec::new(),
        ToolPolicy::DEFAULT_MAX_WRITE_BYTES,
        ToolPolicy::DEFAULT_COMMAND_TIMEOUT_SECONDS,
    )
    .unwrap_err();
    assert!(missing.to_string().contains("exist"));

    let non_positive = ToolPolicy::new(
        root.clone(),
        0,
        ToolPolicy::DEFAULT_MAX_LIST_ENTRIES,
        false,
        Vec::new(),
        ToolPolicy::DEFAULT_MAX_WRITE_BYTES,
        ToolPolicy::DEFAULT_COMMAND_TIMEOUT_SECONDS,
    )
    .unwrap_err();
    assert!(non_positive.to_string().contains("positive"));

    let non_positive_entries = ToolPolicy::new(
        root,
        ToolPolicy::DEFAULT_MAX_FILE_BYTES,
        0,
        false,
        Vec::new(),
        ToolPolicy::DEFAULT_MAX_WRITE_BYTES,
        ToolPolicy::DEFAULT_COMMAND_TIMEOUT_SECONDS,
    )
    .unwrap_err();
    assert!(non_positive_entries.to_string().contains("positive"));

    // Python also rejects `max_list_entries=True`; Rust's `i64` parameter
    // makes that invalid state unrepresentable at compile time.
}

#[test]
fn test_task_2_lists_and_reads_workspace_files() {
    let temporary = TestDirectory::new();
    let root = temporary.path().join("workspace");
    fs::create_dir(&root).unwrap();
    fs::write(root.join("README.md"), "hello agent\n").unwrap();
    fs::create_dir(root.join("src")).unwrap();
    fs::write(root.join("src/main.py"), "print('hi')\n").unwrap();
    let mut workspace = make_workspace(&root);

    assert_eq!(
        workspace.available_tools(),
        &["list_files".to_owned(), "read_file".to_owned()]
            .into_iter()
            .collect()
    );
    assert_eq!(
        workspace.list_files(".").unwrap(),
        "file README.md\ndir src"
    );
    assert_eq!(workspace.list_files("src").unwrap(), "file src/main.py");
    assert_eq!(workspace.read_file("README.md").unwrap(), "hello agent\n");
}

#[test]
fn test_task_3_rejects_escapes_secrets_and_symlinks() {
    use std::os::unix::fs::symlink;

    let temporary = TestDirectory::new();
    let root = temporary.path().join("workspace");
    fs::create_dir(&root).unwrap();
    let outside = temporary.path().join("outside.txt");
    fs::write(&outside, "outside").unwrap();
    fs::write(root.join("visible.txt"), "visible").unwrap();
    fs::write(root.join(".env"), "TOKEN=secret").unwrap();
    fs::create_dir(root.join(".git")).unwrap();
    symlink(&outside, root.join("outside-link")).unwrap();
    let mut workspace = make_workspace(&root);

    for raw in [
        "../outside.txt".to_owned(),
        outside.to_string_lossy().into_owned(),
        ".env".to_owned(),
        ".git".to_owned(),
        "outside-link".to_owned(),
    ] {
        assert!(
            workspace.resolve_path(&raw, true).is_err(),
            "expected path to be rejected: {raw:?}"
        );
    }
    assert_eq!(workspace.list_files(".").unwrap(), "file visible.txt");
}

#[test]
fn test_task_4_bounds_directory_and_file_observations() {
    let temporary = TestDirectory::new();
    let root = temporary.path().join("workspace");
    fs::create_dir(&root).unwrap();
    for name in ["a.txt", "b.txt", "c.txt"] {
        fs::write(root.join(name), name).unwrap();
    }
    fs::write(root.join("large.txt"), "too large").unwrap();
    let mut workspace = make_bounded_workspace(&root, 5, 2);

    assert_eq!(
        workspace
            .list_files(".")
            .unwrap()
            .lines()
            .collect::<Vec<_>>(),
        vec!["file a.txt", "file b.txt"]
    );
    let error = workspace.read_file("large.txt").unwrap_err();
    assert!(error.to_string().contains("exceeds 5 bytes"));
}

#[test]
fn test_task_5_rejects_directories_and_non_utf8_files() {
    let temporary = TestDirectory::new();
    let root = temporary.path().join("workspace");
    fs::create_dir(&root).unwrap();
    fs::create_dir(root.join("folder")).unwrap();
    fs::write(root.join("binary.bin"), [0xff]).unwrap();
    let mut workspace = make_workspace(&root);

    let directory_error = workspace.read_file("folder").unwrap_err();
    assert!(directory_error.to_string().contains("regular file"));
    let encoding_error = workspace.read_file("binary.bin").unwrap_err();
    assert!(encoding_error.to_string().contains("UTF-8"));
}

#[test]
fn test_task_6_dispatch_returns_recoverable_observations() {
    let temporary = TestDirectory::new();
    let root = temporary.path().join("workspace");
    fs::create_dir(&root).unwrap();
    fs::write(root.join("README.md"), "hello").unwrap();
    let mut workspace = make_workspace(&root);

    assert_eq!(
        workspace.execute(
            &tool_action("read_file", json!({"path": "README.md"})),
            None,
        ),
        "hello"
    );
    let missing = workspace.execute(
        &tool_action("read_file", json!({"path": "missing.md"})),
        None,
    );
    let disabled = workspace.execute(
        &tool_action("write_file", json!({"path": "x", "content": "y"})),
        None,
    );
    assert!(missing.starts_with("error:"));
    assert_eq!(disabled, "error: tool is not enabled: write_file");
}

#[test]
fn test_task_7_prompt_and_parser_expose_only_read_tools() {
    let temporary = TestDirectory::new();
    let workspace = make_workspace(temporary.path());
    let prompt = build_system_prompt(&workspace);

    assert!(prompt.contains(r#""tool":"list_files""#));
    assert!(prompt.contains(r#""tool":"read_file""#));
    assert!(!prompt.contains(r#""tool":"write_file""#));

    let available = workspace.available_tools();
    assert_eq!(
        parse_action(r#"{"tool":"list_files"}"#, Some(available)).unwrap(),
        AgentAction::Tool(tool_action("list_files", json!({})))
    );
    let error = parse_action(
        r#"{"tool":"write_file","path":"x","content":"y"}"#,
        Some(available),
    )
    .unwrap_err();
    assert!(error.to_string().contains("not enabled"));
}

#[test]
fn test_task_8_agent_lists_reads_observes_and_finishes() {
    let temporary = TestDirectory::new();
    fs::write(temporary.path().join("README.md"), "hello from README").unwrap();
    let mut workspace = make_workspace(temporary.path());
    let responses = RefCell::new(VecDeque::from([
        r#"{"tool":"list_files"}"#.to_owned(),
        r#"{"tool":"read_file","path":"README.md"}"#.to_owned(),
        r#"{"final":"README says hello"}"#.to_owned(),
    ]));
    let seen_messages = RefCell::new(Vec::<Vec<Message>>::new());
    let mut generate = |messages: &[Message]| {
        seen_messages.borrow_mut().push(messages.to_vec());
        responses
            .borrow_mut()
            .pop_front()
            .expect("scripted response queue exhausted")
    };

    let result = run_agent(
        Some("inspect the project"),
        &mut generate,
        &mut workspace,
        None,
        None,
    )
    .unwrap();

    assert!(result.completed);
    assert_eq!(result.final_.as_deref(), Some("README says hello"));
    let action_tools = result.events[..2]
        .iter()
        .map(|event| match event.action.as_ref() {
            Some(AgentAction::Tool(action)) => action.tool.as_str(),
            other => panic!("expected a tool action, got {other:?}"),
        })
        .collect::<Vec<_>>();
    assert_eq!(action_tools, vec!["list_files", "read_file"]);
    assert_eq!(result.events[0].result.as_deref(), Some("file README.md"));
    assert_eq!(
        result.events[1].result.as_deref(),
        Some("hello from README")
    );
    assert_eq!(
        seen_messages.borrow()[2].last(),
        Some(&message("user", "Tool result:\nhello from README"))
    );
}
