// WARNING: Under review - generated by LLM.

//! Week 4 Day 4 checkpoint-and-resume course-code tests.

#[path = "./support/utils.rs"]
mod test_utils;

use std::cell::RefCell;
use std::collections::HashMap;
use std::fs;
use std::rc::Rc;

use serde_json::json;
use test_utils::tempdir;
use tiny_llm_agent::generation::{Generate, Message};
use tiny_llm_agent::protocol::AgentError;
use tiny_llm_agent::workspace::{ConfirmResult, ConfirmTool};
use tiny_llm_agent::{
    AgentCheckpoint, ModelCheckpoint, ReceiptStore, Workspace, create_checkpoint, resume_agent,
    run_to_checkpoint,
};

struct FakeCheckpointModel {
    responses: Vec<String>,
    response_index: usize,
    restored: Option<ModelCheckpoint>,
}

impl FakeCheckpointModel {
    fn new(responses: &[&str]) -> Self {
        Self {
            responses: responses
                .iter()
                .map(|response| (*response).to_owned())
                .collect(),
            response_index: 0,
            restored: None,
        }
    }
}

impl Generate for FakeCheckpointModel {
    fn generate(&mut self, messages: &[Message]) -> Result<String, AgentError> {
        if let Some(restored) = self.restored.take() {
            assert_eq!(
                test_utils::fake_token_ids(messages),
                restored.cached_token_ids
            );
            assert_eq!(messages.len() as i64, restored.conversation_position);
        }
        let response = self
            .responses
            .get(self.response_index)
            .expect("scripted checkpoint model ran out of responses")
            .clone();
        self.response_index += 1;
        Ok(response)
    }

    fn save_checkpoint(&mut self, messages: &[Message]) -> Result<ModelCheckpoint, AgentError> {
        let tokens = test_utils::fake_token_ids(messages);
        ModelCheckpoint::new(
            messages.len() as i64,
            self.response_index as i64,
            tokens.clone(),
            vec![tokens.len() as i64, tokens.len() as i64],
        )
    }

    fn restore_checkpoint(&mut self, checkpoint: &ModelCheckpoint) -> Result<(), AgentError> {
        self.response_index = checkpoint.response_index as usize;
        self.restored = Some(checkpoint.clone());
        Ok(())
    }
}

#[test]
fn test_task_1_model_checkpoint_has_one_aligned_fake_cache_snapshot() {
    let checkpoint = ModelCheckpoint::new(4, 2, vec![11, 12, 13], vec![3, 3]).unwrap();

    assert_eq!(checkpoint.conversation_position, 4);
    assert_eq!(checkpoint.response_index, 2);
    test_utils::assert_error_contains(ModelCheckpoint::new(-1, 0, vec![], vec![0]), "positions");
    test_utils::assert_error_contains(ModelCheckpoint::new(1, 0, vec![-1], vec![1]), "token ids");
    test_utils::assert_error_contains(
        ModelCheckpoint::new(1, 0, vec![1], vec![0, 1]),
        "layer offsets",
    );
}

#[test]
fn test_task_2_agent_checkpoint_binds_task_messages_and_model_state() {
    let mut messages = vec![
        HashMap::from([
            ("role".to_owned(), "system".to_owned()),
            ("content".to_owned(), "system".to_owned()),
        ]),
        HashMap::from([
            ("role".to_owned(), "user".to_owned()),
            ("content".to_owned(), "inspect".to_owned()),
        ]),
    ];
    let model = ModelCheckpoint::new(2, 0, vec![6, 7], vec![2]).unwrap();
    let checkpoint = create_checkpoint("inspect", &messages, model.clone()).unwrap();

    checkpoint.validate().unwrap();
    messages[1].insert("content".to_owned(), "changed outside".to_owned());
    assert_eq!(
        checkpoint.messages.last().unwrap(),
        &("user".to_owned(), "inspect".to_owned())
    );

    let mismatched_model = ModelCheckpoint {
        conversation_position: 3,
        ..model
    };
    test_utils::assert_error_contains(
        create_checkpoint("inspect", &messages, mismatched_model),
        "conversation",
    );

    let mut changed = checkpoint.clone();
    changed.task = "different".to_owned();
    test_utils::assert_error_contains(changed.validate(), "identity");

    let mut changed = checkpoint.clone();
    changed.messages[1] = ("user".to_owned(), "respect".to_owned());
    assert_eq!(changed.messages[1].1.len(), checkpoint.messages[1].1.len());
    test_utils::assert_error_contains(changed.validate(), "identity");

    let mut changed = checkpoint.clone();
    changed.model.response_index = 1;
    test_utils::assert_error_contains(changed.validate(), "identity");

    let mut changed = checkpoint.clone();
    changed.model.cached_token_ids = vec![6, 8];
    test_utils::assert_error_contains(changed.validate(), "identity");

    let mut changed = checkpoint.clone();
    changed.model.layer_offsets = vec![2, 2];
    test_utils::assert_error_contains(changed.validate(), "identity");

    // A tuple of the wrong arity cannot be represented by the Rust field type;
    // an invalid role exercises the corresponding malformed-message check.
    let mut changed = checkpoint;
    changed.messages = vec![("invalid".to_owned(), "message".to_owned())];
    changed.model.conversation_position = 1;
    test_utils::assert_error_contains(changed.validate(), "messages");
}

#[test]
fn test_task_3_checkpoint_is_saved_after_the_complete_tool_observation() {
    let directory = tempdir().unwrap();
    fs::write(directory.path().join("README.md"), "hello\n").unwrap();
    let mut workspace = test_utils::read_only_workspace(directory.path());
    let mut model = FakeCheckpointModel::new(&[r#"{"tool":"read_file","path":"README.md"}"#]);

    let checkpoint = run_to_checkpoint("inspect", &mut model, &mut workspace, 1, None).unwrap();

    assert_eq!(checkpoint.model.response_index, 1);
    assert_eq!(
        checkpoint.model.conversation_position,
        checkpoint.messages.len() as i64
    );
    assert_eq!(checkpoint.messages.len(), 4);
    assert_eq!(
        checkpoint.messages[checkpoint.messages.len() - 2],
        (
            "assistant".to_owned(),
            r#"{"tool":"read_file","path":"README.md"}"#.to_owned()
        )
    );
    assert_eq!(
        checkpoint.messages.last().unwrap(),
        &("user".to_owned(), "Tool result:\nhello\n".to_owned())
    );
}

#[test]
fn test_task_4_checkpoint_api_fails_clearly_before_a_boundary() {
    let directory = tempdir().unwrap();
    let mut workspace = test_utils::read_only_workspace(directory.path());

    let mut empty = FakeCheckpointModel::new(&[]);
    test_utils::assert_error_contains(
        run_to_checkpoint("inspect", &mut empty, &mut workspace, 0, None),
        "positive integer",
    );

    let mut final_only = FakeCheckpointModel::new(&[r#"{"final":"done"}"#]);
    test_utils::assert_error_contains(
        run_to_checkpoint("inspect", &mut final_only, &mut workspace, 1, None),
        "ended before checkpoint",
    );

    let mut plain_generate =
        |_messages: &[Message]| r#"{"tool":"list_files","path":"."}"#.to_owned();
    test_utils::assert_error_contains(
        run_to_checkpoint("inspect", &mut plain_generate, &mut workspace, 1, None),
        "does not support checkpoints",
    );
}

#[test]
fn test_task_5_resume_requires_valid_content_and_a_restorable_model() {
    let directory = tempdir().unwrap();
    let mut workspace = test_utils::read_only_workspace(directory.path());
    let mut model = FakeCheckpointModel::new(&[r#"{"tool":"list_files","path":"."}"#]);
    let checkpoint = run_to_checkpoint("inspect", &mut model, &mut workspace, 1, None).unwrap();

    let mut invalid = checkpoint.clone();
    invalid.checkpoint_id = "0".repeat(64);
    let mut fresh = FakeCheckpointModel::new(&[]);
    test_utils::assert_error_contains(
        resume_agent(&invalid, &mut fresh, &mut workspace, None),
        "identity",
    );

    let mut plain_generate = |_messages: &[Message]| r#"{"final":"done"}"#.to_owned();
    test_utils::assert_error_contains(
        resume_agent(&checkpoint, &mut plain_generate, &mut workspace, None),
        "checkpoint restore",
    );
}

#[test]
fn test_task_6_fresh_model_restores_the_exact_next_response() {
    let directory = tempdir().unwrap();
    let mut workspace = test_utils::read_only_workspace(directory.path());
    let responses = [
        r#"{"tool":"list_files","path":"."}"#,
        r#"{"final":"resumed after listing"}"#,
    ];
    let mut initial_model = FakeCheckpointModel::new(&responses);
    let checkpoint =
        run_to_checkpoint("inspect", &mut initial_model, &mut workspace, 1, None).unwrap();
    let mut fresh_model = FakeCheckpointModel::new(&responses);

    let result = resume_agent(&checkpoint, &mut fresh_model, &mut workspace, None).unwrap();

    assert!(result.completed);
    assert_eq!(result.final_.as_deref(), Some("resumed after listing"));
    assert_eq!(fresh_model.response_index, 2);
}

#[test]
fn test_task_7_edit_checkpoint_resume_validates_without_replaying_effect() {
    let directory = tempdir().unwrap();
    let source = directory.path().join("app.py");
    fs::write(&source, "answer = 1\n").unwrap();
    let python = std::env::var("PYTHON").unwrap_or_else(|_| "python3".to_owned());
    let validation = vec![
        python,
        "-c".to_owned(),
        "from pathlib import Path; assert Path('app.py').read_text() == 'answer = 2\\n'".to_owned(),
    ];
    let approvals = Rc::new(RefCell::new(Vec::<String>::new()));
    let captured_approvals = Rc::clone(&approvals);
    let confirm: ConfirmTool = Box::new(move |action| {
        captured_approvals
            .borrow_mut()
            .push(action.tool().to_owned());
        ConfirmResult::Approved(true)
    });
    let receipts_path = directory.path().join("receipts.jsonl");
    let receipts = ReceiptStore::new(Some(receipts_path)).unwrap();
    let mut workspace = Workspace::new(
        test_utils::policy(directory.path(), true, vec![validation.clone()]),
        Some(confirm),
        receipts.clone(),
    );
    let command_response = json!({"tool": "run_command", "argv": validation}).to_string();
    let responses = [
        r#"{"tool":"read_file","path":"app.py"}"#.to_owned(),
        r#"{"tool":"edit_file","path":"app.py","old":"1","new":"2"}"#.to_owned(),
        command_response,
        r#"{"final":"changed and validated app.py"}"#.to_owned(),
    ];
    let response_refs: Vec<&str> = responses.iter().map(String::as_str).collect();

    let mut initial_model = FakeCheckpointModel::new(&response_refs);
    let checkpoint =
        run_to_checkpoint("fix app.py", &mut initial_model, &mut workspace, 3, None).unwrap();
    assert_eq!(fs::read_to_string(&source).unwrap(), "answer = 2\n");
    assert_eq!(
        approvals.borrow().as_slice(),
        &["edit_file".to_owned(), "run_command".to_owned()]
    );
    assert_eq!(
        workspace
            .receipt_store
            .get("call-1")
            .unwrap()
            .changed_artifacts,
        vec!["app.py".to_owned()]
    );
    assert!(
        workspace
            .receipt_store
            .get("call-2")
            .unwrap()
            .changed_artifacts
            .is_empty()
    );

    // Exhaustive destructuring keeps the Python test's exact public-field
    // contract at compile time: adding another field requires updating this.
    let AgentCheckpoint {
        checkpoint_id: _,
        task: _,
        messages: _,
        model: _,
    } = checkpoint.clone();

    let mut fresh_model = FakeCheckpointModel::new(&response_refs);
    let result = resume_agent(&checkpoint, &mut fresh_model, &mut workspace, None).unwrap();

    assert!(result.completed);
    assert_eq!(
        result.final_.as_deref(),
        Some("changed and validated app.py")
    );
    assert_eq!(
        approvals.borrow().as_slice(),
        &["edit_file".to_owned(), "run_command".to_owned()]
    );
    assert_eq!(fs::read_to_string(&source).unwrap(), "answer = 2\n");
    assert_eq!(
        workspace.receipt_store.get("call-1").unwrap().tool.tool(),
        "edit_file"
    );
    assert_eq!(
        workspace.receipt_store.get("call-2").unwrap().tool.tool(),
        "run_command"
    );
}
