// WARNING: Under review - generated by LLM.

//! Rust port of the Week 4 Day 7 observable-outcome evaluation tests.

#[path = "./support/utils.rs"]
mod test_utils;

use std::cell::{Cell, RefCell};
use std::fs;
use std::rc::Rc;

use serde_json::json;

use tiny_llm_agent::EffectReceipt;
use tiny_llm_agent::evaluation::ReceiptLookup;
use tiny_llm_agent::protocol::ToolAction;
use tiny_llm_agent::workspace::{ConfirmResult, Workspace};
use tiny_llm_agent::{
    AgentRun, EvaluationCase, FileExpectation, ReceiptExpectation, ReceiptStore, ResultExpectation,
    evaluate_run, run_agent,
};

struct CompletedCase {
    _temp: test_utils::TestDir,
    run: AgentRun,
    workspace: Workspace,
    case: EvaluationCase,
    approvals: Rc<RefCell<Vec<String>>>,
}

fn completed_case(label: &str) -> CompletedCase {
    let temp = test_utils::TestDir::new(label);
    fs::write(temp.path().join("app.py"), b"answer = 1\n").expect("seed app.py");

    let command = vec![
        "/bin/sh".to_owned(),
        "-c".to_owned(),
        "grep -qx 'answer = 2' app.py && printf 'validation passed\\n'".to_owned(),
    ];
    let approvals = Rc::new(RefCell::new(Vec::new()));
    let seen = Rc::clone(&approvals);
    let receipts =
        ReceiptStore::new(Some(temp.path().join("receipts.jsonl"))).expect("create receipt store");
    let mut workspace = Workspace::new(
        test_utils::policy(temp.path(), true, vec![command.clone()]),
        Some(Box::new(move |action| {
            seen.borrow_mut().push(action.tool().to_owned());
            ConfirmResult::Approved(true)
        })),
        receipts,
    );

    let responses = [
        r#"{"tool":"read_file","path":"app.py"}"#.to_owned(),
        r#"{"tool":"edit_file","path":"app.py","old":"1","new":"2"}"#.to_owned(),
        json!({"tool": "run_command", "argv": command}).to_string(),
        r#"{"final":"updated app.py and validated the result"}"#.to_owned(),
    ];
    let response_index = Cell::new(0usize);
    let mut generate = |_messages: &[tiny_llm_agent::generation::Message]| {
        let index = response_index.get();
        response_index.set(index + 1);
        responses[index].clone()
    };
    let run = run_agent(
        Some("set answer = 2 in app.py and validate"),
        &mut generate,
        &mut workspace,
        None,
        None,
    )
    .expect("complete deterministic run");
    let case = EvaluationCase::new(
        "validated".to_owned(),
        vec![test_utils::file_expectation("app.py", "answer = 2\n")],
        vec![
            test_utils::result_expectation("edit_file", "edited app.py"),
            test_utils::result_expectation("run_command", "validation passed"),
        ],
        vec![
            test_utils::receipt_expectation(
                "call-1",
                "edit_file",
                "ok",
                "edited app.py",
                &["app.py"],
            ),
            test_utils::receipt_expectation(
                "call-2",
                "run_command",
                "ok",
                "validation passed",
                &[],
            ),
        ],
    )
    .expect("valid evaluation case");

    CompletedCase {
        _temp: temp,
        run,
        workspace,
        case,
        approvals,
    }
}

#[test]
fn test_task_1_end_to_end_run_passes_declared_observable_facts() {
    let completed = completed_case("day7-task1");

    let report = evaluate_run(
        &completed.run,
        &completed.workspace,
        &completed.workspace.receipt_store,
        &completed.case,
    );

    assert!(report.passed());
    assert_eq!(
        report
            .checks
            .iter()
            .map(|check| check.name.as_str())
            .collect::<Vec<_>>(),
        [
            "final",
            "file:app.py",
            "result:edit_file",
            "result:run_command",
            "receipt:call-1",
            "receipt:call-2",
        ]
    );
    assert_eq!(
        completed.approvals.borrow().as_slice(),
        ["edit_file", "run_command"]
    );
    assert_eq!(
        report.render().lines().collect::<Vec<_>>(),
        [
            "evaluation: PASS",
            "- final: PASS (required final observed)",
            "- file:app.py: PASS (content matches)",
            "- result:edit_file: PASS (required result observed)",
            "- result:run_command: PASS (required result observed)",
            "- receipt:call-1: PASS (receipt facts match)",
            "- receipt:call-2: PASS (receipt facts match)",
        ]
    );
}

#[test]
fn test_task_2_each_wrong_fact_fails_only_its_named_check() {
    for (fact, failed_name) in [
        ("final", "final"),
        ("file", "file:app.py"),
        ("result", "result:run_command"),
        ("receipt", "receipt:call-1"),
    ] {
        let mut completed = completed_case(&format!("day7-wrong-{fact}"));
        match fact {
            "final" => completed.case.final_contains = "not in the final".to_owned(),
            "file" => {
                completed.case.files = vec![test_utils::file_expectation("app.py", "wrong\n")]
            }
            "result" => {
                completed.case.results[1] =
                    test_utils::result_expectation("run_command", "status: 9")
            }
            "receipt" => completed.case.receipts[0].tool = "write_file".to_owned(),
            _ => unreachable!(),
        }

        let report = evaluate_run(
            &completed.run,
            &completed.workspace,
            &completed.workspace.receipt_store,
            &completed.case,
        );
        assert!(!report.passed(), "wrong {fact} unexpectedly passed");
        assert_eq!(test_utils::failed_names(&report), [failed_name]);
    }
}

#[test]
fn test_task_2_incomplete_run_cannot_pass_from_matching_final_text() {
    let completed = completed_case("day7-incomplete");
    let mut incomplete = completed.run.clone();
    incomplete.completed = false;
    incomplete.reason = "step_limit".to_owned();

    let report = evaluate_run(
        &incomplete,
        &completed.workspace,
        &completed.workspace.receipt_store,
        &completed.case,
    );

    assert!(!report.passed());
    assert_eq!(test_utils::failed_names(&report), ["final"]);
}

#[test]
fn test_task_2_file_content_requires_exact_bytes() {
    let completed = completed_case("day7-exact-bytes");
    fs::write(
        completed._temp.path().join("app.py"),
        b"answer = 2\nextra\n",
    )
    .expect("replace evidence");

    let report = evaluate_run(
        &completed.run,
        &completed.workspace,
        &completed.workspace.receipt_store,
        &completed.case,
    );
    assert!(!report.passed());
    assert_eq!(test_utils::failed_names(&report), ["file:app.py"]);
}

#[test]
fn test_task_2_file_content_does_not_normalize_newlines() {
    let completed = completed_case("day7-newlines");
    fs::write(completed._temp.path().join("app.py"), b"answer = 2\r\n").expect("replace evidence");

    let report = evaluate_run(
        &completed.run,
        &completed.workspace,
        &completed.workspace.receipt_store,
        &completed.case,
    );
    assert!(!report.passed());
    assert_eq!(test_utils::failed_names(&report), ["file:app.py"]);
}

#[test]
fn test_task_2_invalid_utf8_is_not_ignored() {
    let completed = completed_case("day7-invalid-utf8");
    fs::write(completed._temp.path().join("app.py"), b"answer = \xff2\n")
        .expect("replace evidence");

    let report = evaluate_run(
        &completed.run,
        &completed.workspace,
        &completed.workspace.receipt_store,
        &completed.case,
    );
    assert!(!report.passed());
    assert_eq!(test_utils::failed_names(&report), ["file:app.py"]);
}

#[test]
fn test_task_2_invalid_utf8_is_not_replaced() {
    let completed = completed_case("day7-invalid-utf8-replacement");
    fs::write(completed._temp.path().join("app.py"), b"answer = \xff2\n")
        .expect("replace evidence");
    let mut replacement_case = completed.case.clone();
    replacement_case.files = vec![test_utils::file_expectation(
        "app.py",
        "answer = \u{fffd}2\n",
    )];

    let report = evaluate_run(
        &completed.run,
        &completed.workspace,
        &completed.workspace.receipt_store,
        &replacement_case,
    );
    assert!(!report.passed());
    assert_eq!(test_utils::failed_names(&report), ["file:app.py"]);
}

#[test]
fn test_task_2_tool_and_result_must_match_the_same_event() {
    let completed = completed_case("day7-same-event");
    let mut split_evidence = completed.run.clone();
    assert_eq!(
        test_utils::action_tool(&split_evidence.events[0]),
        Some("read_file")
    );
    assert_eq!(
        test_utils::action_tool(&split_evidence.events[1]),
        Some("edit_file")
    );
    split_evidence.events[0].result = Some("edited app.py".to_owned());
    split_evidence.events[1].result = Some("edit completed".to_owned());

    let report = evaluate_run(
        &split_evidence,
        &completed.workspace,
        &completed.workspace.receipt_store,
        &completed.case,
    );
    assert!(!report.passed());
    assert_eq!(test_utils::failed_names(&report), ["result:edit_file"]);
}

#[test]
fn test_task_2_each_receipt_fact_is_independently_required() {
    for field_name in ["exit_state", "result_contains", "changed_artifacts"] {
        let completed = completed_case(&format!("day7-receipt-{field_name}"));
        let mut changed_case = completed.case.clone();
        match field_name {
            "exit_state" => changed_case.receipts[0].exit_state = "error".to_owned(),
            "result_contains" => {
                changed_case.receipts[0].result_contains = "not in the receipt".to_owned()
            }
            "changed_artifacts" => {
                changed_case.receipts[0].changed_artifacts = vec!["other.py".to_owned()]
            }
            _ => unreachable!(),
        }

        let report = evaluate_run(
            &completed.run,
            &completed.workspace,
            &completed.workspace.receipt_store,
            &changed_case,
        );
        assert!(!report.passed());
        assert_eq!(test_utils::failed_names(&report), ["receipt:call-1"]);
    }
}

#[test]
fn test_task_3_nonessential_final_phrasing_and_event_order_are_not_graded() {
    let completed = completed_case("day7-nonessential");
    let mut alternate = completed.run.clone();
    alternate.final_ =
        Some("The requested outcome is validated with the recorded evidence.".to_owned());
    alternate.events.reverse();

    let report = evaluate_run(
        &alternate,
        &completed.workspace,
        &completed.workspace.receipt_store,
        &completed.case,
    );
    assert!(report.passed());
}

#[test]
fn test_task_4_missing_unreadable_and_absent_evidence_become_failed_checks() {
    let completed = completed_case("day7-unavailable");
    fs::create_dir(completed._temp.path().join("folder")).expect("create non-file evidence");
    let mut unavailable = completed.case.clone();
    unavailable.files = vec![
        test_utils::file_expectation("missing.txt", "missing"),
        test_utils::file_expectation("folder", "not a file"),
    ];
    let empty_receipts = ReceiptStore::new(None).expect("empty receipt store");

    let report = evaluate_run(
        &completed.run,
        &completed.workspace,
        &empty_receipts,
        &unavailable,
    );

    assert_eq!(
        test_utils::failed_names(&report),
        [
            "file:missing.txt",
            "file:folder",
            "receipt:call-1",
            "receipt:call-2",
        ]
    );
    assert!(report.render().starts_with("evaluation: FAIL\n"));
}

#[test]
fn test_task_5_tampered_receipt_log_becomes_failed_checks() {
    for tamper in ["digest", "utf8"] {
        let completed = completed_case(&format!("day7-tamper-{tamper}"));
        let receipt_path = completed
            .workspace
            .receipt_store
            .path
            .as_ref()
            .expect("persistent receipts");
        if tamper == "digest" {
            let original = fs::read_to_string(receipt_path).expect("read receipts");
            fs::write(
                receipt_path,
                original.replacen("edit_file", "write_file", 1),
            )
            .expect("tamper receipt digest");
        } else {
            fs::write(receipt_path, b"\xff").expect("tamper receipt encoding");
        }

        let report = evaluate_run(
            &completed.run,
            &completed.workspace,
            &completed.workspace.receipt_store,
            &completed.case,
        );
        assert_eq!(
            test_utils::failed_names(&report),
            ["receipt:call-1", "receipt:call-2"]
        );
        assert!(
            report.checks[report.checks.len() - 2..]
                .iter()
                .all(|check| check.detail.contains("receipt evidence unavailable"))
        );
    }
}

#[test]
fn test_task_6_evaluation_is_pure() {
    let completed = completed_case("day7-pure");
    let receipt_path = completed
        .workspace
        .receipt_store
        .path
        .as_ref()
        .expect("persistent receipts");
    let before = (
        fs::read(completed._temp.path().join("app.py")).expect("read app"),
        fs::read(receipt_path).expect("read receipts"),
        completed.workspace.modified_files(),
        completed.approvals.borrow().clone(),
        completed.run.clone(),
    );

    let _ = evaluate_run(
        &completed.run,
        &completed.workspace,
        &completed.workspace.receipt_store,
        &completed.case,
    );

    let after = (
        fs::read(completed._temp.path().join("app.py")).expect("read app"),
        fs::read(receipt_path).expect("read receipts"),
        completed.workspace.modified_files(),
        completed.approvals.borrow().clone(),
        completed.run.clone(),
    );
    assert_eq!(after, before);
}

#[test]
fn test_task_6_file_evidence_does_not_dispatch_the_stateful_read_tool() {
    let mut completed = completed_case("day7-no-stateful-read");
    fs::write(
        completed._temp.path().join("evidence.txt"),
        b"declared evidence\n",
    )
    .expect("write evidence");
    let mut changed_case = completed.case.clone();
    changed_case.files = vec![test_utils::file_expectation(
        "evidence.txt",
        "declared evidence\n",
    )];

    let report = evaluate_run(
        &completed.run,
        &completed.workspace,
        &completed.workspace.receipt_store,
        &changed_case,
    );
    assert!(report.passed());

    // A stateful Workspace::read_file would authorize a subsequent edit.  A
    // failed edit therefore proves evaluation inspected bytes directly.
    let edit = ToolAction::EditFile {
        path: "evidence.txt".into(),
        old: "declared".into(),
        new: "changed".into(),
    };
    let result = completed.workspace.execute(&edit, None);
    // .expect("tool errors remain model-visible");
    assert!(result.contains("read the existing file before changing it"));
}

#[test]
fn test_task_7_invalid_evaluation_specifications_fail_closed() {
    let error = EvaluationCase::new("  ".to_owned(), vec![], vec![], vec![]).unwrap_err();
    assert!(error.to_string().contains("final substring"));

    let error = FileExpectation::new("../escape".to_owned(), "data".to_owned()).unwrap_err();
    assert!(error.to_string().contains("file path"));

    let error = ResultExpectation::new("read_file".to_owned(), "  ".to_owned()).unwrap_err();
    assert!(error.to_string().contains("result substring"));

    let error = ReceiptExpectation::new(
        String::new(),
        "edit_file".to_owned(),
        "ok".to_owned(),
        "edited".to_owned(),
        vec![],
    )
    .unwrap_err();
    assert!(error.to_string().contains("receipt call id"));

    let error = ReceiptExpectation::new(
        "call-1".to_owned(),
        "edit_file".to_owned(),
        "maybe".to_owned(),
        "edited".to_owned(),
        vec![],
    )
    .unwrap_err();
    assert!(error.to_string().contains("exit_state"));

    let error = EvaluationCase::new(
        "done".to_owned(),
        vec![
            test_utils::file_expectation("a/b", "1"),
            test_utils::file_expectation("a//b", "2"),
        ],
        vec![],
        vec![],
    )
    .unwrap_err();
    assert!(error.to_string().contains("file paths must be unique"));

    let error = EvaluationCase::new(
        "done".to_owned(),
        vec![],
        vec![],
        vec![
            test_utils::receipt_expectation("call-1", "edit_file", "ok", "edited", &[]),
            test_utils::receipt_expectation("call-1", "run_command", "ok", "status", &[]),
        ],
    )
    .unwrap_err();
    assert!(
        error
            .to_string()
            .contains("receipt call ids must be unique")
    );

    // Python additionally passes object() values here. Rust's function
    // signature makes non-AgentRun/non-EvaluationCase calls fail at compile time.
}

#[test]
fn test_task_7_receipt_lookup_errors_become_failed_checks() {
    let completed = completed_case("day7-receipt-lookup");
    struct FailingReceiptLookup;

    impl ReceiptLookup for FailingReceiptLookup {
        fn snapshot(&self) -> Result<Box<dyn ReceiptLookup>, tiny_llm_agent::AgentError> {
            Ok(Box::new(FailingReceiptLookup))
        }

        fn get_receipt(
            &self,
            _tool_call_id: &str,
        ) -> Result<Option<EffectReceipt>, tiny_llm_agent::AgentError> {
            Err(tiny_llm_agent::AgentError("lookup broke".to_owned()))
        }
    }

    let report = evaluate_run(
        &completed.run,
        &completed.workspace,
        &FailingReceiptLookup,
        &completed.case,
    );

    assert_eq!(
        test_utils::failed_names(&report),
        ["receipt:call-1", "receipt:call-2"]
    );
    assert!(
        report.checks[report.checks.len() - 2..]
            .iter()
            .all(|check| check.detail.contains("receipt lookup failed"))
    );
}
