// WARNING: Under review - generated by LLM.

//! Week 4, Day 4 learner surface for checkpoint and resume.

use crate::generation::Message;
use crate::protocol::AgentError;

/// Small fake-model snapshot needed for deterministic course resumption.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ModelCheckpoint {
    pub conversation_position: i64,
    pub response_index: i64,
    pub cached_token_ids: Vec<i64>,
    pub layer_offsets: Vec<i64>,
}

impl ModelCheckpoint {
    pub fn new(
        conversation_position: i64,
        response_index: i64,
        cached_token_ids: Vec<i64>,
        layer_offsets: Vec<i64>,
    ) -> Result<Self, AgentError> {
        let checkpoint = Self {
            conversation_position,
            response_index,
            cached_token_ids,
            layer_offsets,
        };
        checkpoint.post_init()?;
        Ok(checkpoint)
    }

    /// Python's ``__post_init__``.
    pub fn post_init(&self) -> Result<(), AgentError> {
        // TODO: validate positions, token ids, and aligned layer offsets.
        todo!()
    }
}

/// Conversation and model state saved after one complete tool observation.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct AgentCheckpoint {
    pub checkpoint_id: String,
    pub task: String,
    pub messages: Vec<(String, String)>,
    pub model: ModelCheckpoint,
}

impl AgentCheckpoint {
    /// Reject a checkpoint whose identity or conversation position changed.
    pub fn validate(&self) -> Result<(), AgentError> {
        todo!()
    }
}

/// Freeze one conversation boundary and bind it to the fake-model state.
pub fn create_checkpoint(
    task: &str,
    messages: &[Message],
    model: ModelCheckpoint,
) -> Result<AgentCheckpoint, AgentError> {
    todo!()
}
