// WARNING: Under review - generated by LLM.

//! Week 4, Day 1: the minimal generation surface (starter).
//!
//! Day 1 needs only the message types, the initial conversation messages, and
//! a single-shot `generate_response` helper.
//!
//! Implement the bodies yourself; use the Day 1 chapter and public tests as the
//! learner contract.

use std::any::Any;
use std::collections::HashMap;

use crate::protocol::AgentError;

/// Python's ``Message = dict[str, str]``.
pub type Message = HashMap<String, String>;

/// A model callable, optionally able to save and restore a conversation prefix.
pub trait Generate {
    fn generate(&mut self, messages: &[Message]) -> Result<String, AgentError>;
    fn save_checkpoint(
        &mut self,
        _messages: &[Message],
    ) -> Result<crate::checkpoint::ModelCheckpoint, AgentError> {
        Err(AgentError("model does not support checkpoints".into()))
    }
    fn restore_checkpoint(
        &mut self,
        _checkpoint: &crate::checkpoint::ModelCheckpoint,
    ) -> Result<(), AgentError> {
        Err(AgentError(
            "model does not support checkpoint restore".into(),
        ))
    }
    fn prefix_reuse(&self) -> Option<(i64, Vec<i64>, i64)> {
        None
    }
}

impl<F: FnMut(&[Message]) -> String> Generate for F {
    fn generate(&mut self, messages: &[Message]) -> Result<String, AgentError> {
        Ok(self(messages))
    }
}

/// Model-owned cache with explicit release and optional dense-prefix forking.
pub trait GenerationCache {
    fn release(&mut self);
    fn as_any(&self) -> &dyn Any;
    fn offset(&self) -> i64 {
        0
    }
    fn fork_box(&self) -> Result<Box<dyn GenerationCache>, AgentError> {
        Err(AgentError("cache does not support prefix forking".into()))
    }
}

/// Last-token logits and cache creation used by greedy generation.
pub trait GenerationModel {
    fn forward(
        &mut self,
        tokens: &[i64],
        offset: i64,
        caches: &mut [Box<dyn GenerationCache>],
        logits_to_keep: Option<usize>,
    ) -> Result<Vec<f32>, AgentError>;
    fn new_caches(&self) -> Result<Vec<Box<dyn GenerationCache>>, AgentError> {
        Err(AgentError("model does not support cache creation".into()))
    }
}

pub trait GenerationTokenizer {
    fn eos_token_id(&self) -> i64;
    fn apply_chat_template(
        &mut self,
        messages: &[Message],
        tokenize: bool,
        add_generation_prompt: bool,
        enable_thinking: bool,
    ) -> Result<String, AgentError>;
    fn encode(&mut self, prompt: &str, add_special_tokens: bool) -> Result<Vec<i64>, AgentError>;
    fn decode(&mut self, tokens: &[i64]) -> Result<String, AgentError>;
}

/// Create the durable beginning of an agent conversation.
pub fn initial_messages(task: &str, system_prompt: &str) -> Result<Vec<Message>, AgentError> {
    // reject an empty task; return system + user messages.
    if task.trim().is_empty() {
        return Err(AgentError("task must not be empty".into()));
    }
    Ok(vec![
        Message::from([
            ("role".into(), "system".into()),
            ("content".into(), system_prompt.into()),
        ]),
        Message::from([
            ("role".into(), "user".into()),
            ("content".into(), task.into()),
        ]),
    ])
}

fn generate_response_inner(
    model: &mut dyn GenerationModel,
    tokenizer: &mut dyn GenerationTokenizer,
    mut tokens: Vec<i64>,
    caches: &mut Vec<Box<dyn GenerationCache>>,
    max_tokens: i64,
) -> Result<String, AgentError> {
    let mut offset = 0;
    let mut tokens_to_decode = vec![];

    for _ in 0..max_tokens {
        let logits = model.forward(&tokens, offset, caches, None)?;
        offset += tokens.len() as i64;
        let next_token = logits
            .iter()
            .enumerate()
            .max_by(|a, b| a.1.partial_cmp(b.1).unwrap())
            .map(|(i, _)| i as i64)
            .unwrap_or(tokenizer.eos_token_id());
        if next_token == tokenizer.eos_token_id() {
            break;
        }
        tokens_to_decode.push(next_token);
        tokens = vec![next_token];
    }

    tokenizer.decode(&tokens_to_decode)
}

/// Decode one action with the course model and a fresh cache.
pub fn generate_response(
    model: &mut dyn GenerationModel,
    tokenizer: &mut dyn GenerationTokenizer,
    messages: &[Message],
    cache_factory: &mut dyn FnMut() -> Vec<Box<dyn GenerationCache>>,
    max_tokens: i64,
    enable_thinking: bool,
) -> Result<String, AgentError> {
    if max_tokens <= 0 {
        return Err(AgentError("max_tokens must be positive".into()));
    }
    let prompt = tokenizer.apply_chat_template(messages, false, true, enable_thinking)?;
    let tokens = tokenizer.encode(&prompt, false)?;

    let mut caches = cache_factory();

    let result = generate_response_inner(model, tokenizer, tokens, &mut caches, max_tokens);

    for cache in caches.iter_mut() {
        cache.release();
    }

    result
}
