// WARNING: Under review - generated by LLM.

//! Week 4, Day 1: the validated agent loop (starter).
//!
//! The loop turns model text into one bounded, schema-checked action or final
//! response.  It stops by budget, returns invalid actions to the model, and
//! guards against repeated identical actions.  This file keeps only the
//! validated Day 1 core.
//!
//! Implement the bodies yourself; use the Day 1 chapter and public tests as the
//! learner contract.

use crate::checkpoint::AgentCheckpoint;
use crate::checkpoint::create_checkpoint;
use crate::generation::{Generate, Message, initial_messages};
use crate::protocol::{AgentAction, AgentError, AgentWorkspace, build_system_prompt, parse_action};

/// Budgets that guarantee the loop eventually stops.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct AgentLimits {
    pub max_steps: i64,
    pub max_context_chars: i64,
    pub max_invalid_actions: i64,
    pub max_identical_actions: i64,
}

impl AgentLimits {
    /// Python defaults: ``max_steps=8``, ``max_context_chars=48_000``,
    /// ``max_invalid_actions=3``, ``max_identical_actions=2``.
    pub const DEFAULT_MAX_STEPS: i64 = 8;
    pub const DEFAULT_MAX_CONTEXT_CHARS: i64 = 48_000;
    pub const DEFAULT_MAX_INVALID_ACTIONS: i64 = 3;
    pub const DEFAULT_MAX_IDENTICAL_ACTIONS: i64 = 2;

    pub fn new(
        max_steps: i64,
        max_context_chars: i64,
        max_invalid_actions: i64,
        max_identical_actions: i64,
    ) -> Result<Self, AgentError> {
        let limits = Self {
            max_steps,
            max_context_chars,
            max_invalid_actions,
            max_identical_actions,
        };
        limits.post_init()?;
        Ok(limits)
    }

    /// Reject budgets that could disable a stop condition.
    fn post_init(&self) -> Result<(), AgentError> {
        // reject any non-positive budget.
        if self.max_steps <= 0 {
            return Err(AgentError("max_steps must be positive".into()));
        }
        if self.max_context_chars <= 0 {
            return Err(AgentError("max_context_chars must be positive".into()));
        }
        if self.max_invalid_actions <= 0 {
            return Err(AgentError("max_invalid_actions must be positive".into()));
        }
        if self.max_identical_actions <= 0 {
            return Err(AgentError("max_identical_actions must be positive".into()));
        }
        Ok(())
    }
}

impl Default for AgentLimits {
    fn default() -> Self {
        Self {
            max_steps: Self::DEFAULT_MAX_STEPS,
            max_context_chars: Self::DEFAULT_MAX_CONTEXT_CHARS,
            max_invalid_actions: Self::DEFAULT_MAX_INVALID_ACTIONS,
            max_identical_actions: Self::DEFAULT_MAX_IDENTICAL_ACTIONS,
        }
    }
}

/// One auditable model/action/tool interaction.
#[derive(Default, Debug, Clone, PartialEq)]
pub struct AgentEvent {
    pub step: i64,
    pub response: String,
    pub action: Option<AgentAction>,
    pub result: Option<String>,
}

/// One bounded run; `completed` means the model returned a valid final.
#[derive(Default, Debug, Clone, PartialEq)]
pub struct AgentRun {
    pub completed: bool,
    pub reason: String,
    pub final_: Option<String>,
    pub events: Vec<AgentEvent>,
    /// Python default: ``()``.
    pub modified_files: Vec<String>,
}

pub(crate) enum RunTaskResult {
    Run(AgentRun),
    CheckPoint(AgentCheckpoint),
}

pub(crate) fn run_task_loop(
    task: &str,
    messages: Option<Vec<Message>>,
    generate: &mut dyn Generate,
    workspace: &mut dyn AgentWorkspace,
    after_tool_calls: Option<i64>,
    limits: Option<&AgentLimits>,
    on_event: Option<&dyn Fn(&AgentEvent)>,
) -> Result<RunTaskResult, AgentError> {
    // reject an empty task; build the system prompt and initial
    // messages; loop up to max_steps; parse each response with
    // parse_action(response, workspace.available_tools); feed invalid
    // actions back as "error: ..." observations; stop on FinalAction,
    // invalid-action limit, identical-action limit, context limit, and step
    // limit.

    let mut messages = match messages {
        Some(messages) => messages,
        None => {
            let system_prompt = build_system_prompt(workspace);
            initial_messages(task, &system_prompt)?
        }
    };

    let mut steps = 0;
    let mut context_chars = 0;
    let mut invalid_actions = 0;
    let mut identical_actions = 0;
    let mut tool_calls = 0;

    let limits = limits.cloned().unwrap_or(AgentLimits::default());

    let mut run = AgentRun {
        completed: false,
        ..AgentRun::default()
    };

    while !run.completed {
        if steps >= limits.max_steps {
            run.reason = "step_limit".into();
            break;
        }
        if context_chars >= limits.max_context_chars {
            run.reason = "context_limit".into();
            break;
        }
        if invalid_actions >= limits.max_invalid_actions {
            run.reason = "invalid_action_limit".into();
            break;
        }
        if identical_actions >= limits.max_identical_actions {
            run.reason = "repeated_action_limit".into();
            break;
        }

        // each step is an agent event
        let mut event = AgentEvent {
            step: steps,
            response: generate.generate(&messages)?,
            ..AgentEvent::default()
        };

        context_chars += event.response.chars().count() as i64;

        match parse_action(&event.response, Some(workspace.available_tools())) {
            Ok(action) => {
                event.action = Some(action);
            }
            Err(e) => {
                invalid_actions += 1;
                event.result = Some(format!("error: {}", e));
            }
        }

        match &event.action {
            Some(AgentAction::Tool(tool_action)) => {
                event.result = Some(workspace.execute(tool_action, None));
                tool_calls += 1;
                // messages = append_tool_result(&messages, &event.response, event.result.as_ref().unwrap());
            }
            Some(AgentAction::Final(final_action)) => {
                run.completed = true;
                run.reason = "completed".into();
                run.final_ = Some(final_action.final_.clone());
                // break;
            }
            _ => {}
        }

        if let Some(on_event) = on_event {
            on_event(&event);
        }

        if let Some(result) = &event.result {
            messages = append_tool_result(&messages, &event.response, result);
        }

        if let Some(after_tool_calls) = after_tool_calls
            && tool_calls == after_tool_calls
        {
            let checkpoint =
                create_checkpoint(task, &messages, generate.save_checkpoint(&messages)?)?;
            return Ok(RunTaskResult::CheckPoint(checkpoint));
        }

        if let Some(prev_action) = run.events.last().and_then(|e| e.action.as_ref())
            && let Some(curr_action) = event.action.as_ref()
            && prev_action == curr_action
        {
            identical_actions += 1;
        } else {
            identical_actions = 0;
        }

        run.events.push(event);

        steps += 1;
    }

    run.modified_files = workspace.modified_files();

    Ok(RunTaskResult::Run(run))
}

pub const TOOL_RESULT_PREFIX: &str = "Tool result:\n";

/// Append one assistant response and its tool observation.
pub(crate) fn append_tool_result(
    messages: &[Message],
    response: &str,
    result: &str,
) -> Vec<Message> {
    // append assistant + "Tool result: ..." user messages.
    let mut ret = vec![];
    ret.extend_from_slice(messages);
    ret.push(Message {
        role: "assistant".into(),
        content: response.into(),
    });
    ret.push(Message {
        role: "user".into(),
        content: format!("{}{}", TOOL_RESULT_PREFIX, result),
    });
    ret
}

/// Run a bounded validated loop over one task.
///
/// `workspace` must expose `available_tools` (a frozenset of tool names),
/// `execute(action)` (returning a result string), and `modified_files`
/// (an iterable of paths).
pub fn run_agent(
    task: Option<&str>,
    generate: &mut dyn Generate,
    workspace: &mut dyn AgentWorkspace,
    limits: Option<&AgentLimits>,
    on_event: Option<&dyn Fn(&AgentEvent)>,
) -> Result<AgentRun, AgentError> {
    let run = match run_task_loop(
        task.unwrap_or(""),
        None,
        generate,
        workspace,
        None,
        limits,
        on_event,
    )? {
        RunTaskResult::Run(run) => run,
        _ => unreachable!(),
    };
    Ok(run)
}

/// Run until a tool observation is complete, then save model and messages.
pub fn run_to_checkpoint(
    task: &str,
    generate: &mut dyn Generate,
    workspace: &mut dyn AgentWorkspace,
    after_tool_calls: i64,
    limits: Option<&AgentLimits>,
) -> Result<AgentCheckpoint, AgentError> {
    if after_tool_calls <= 0 {
        return Err(AgentError(
            "after_tool_calls must be positive integer".into(),
        ));
    }

    let checkpoint = match run_task_loop(
        task,
        None,
        generate,
        workspace,
        Some(after_tool_calls),
        limits,
        None,
    )? {
        RunTaskResult::CheckPoint(checkpoint) => checkpoint,
        _ => {
            return Err(AgentError("task ended before checkpoint".into()));
        }
    };
    Ok(checkpoint)
}

/// Restore a fresh model and continue after the saved tool observation.
pub fn resume_agent(
    checkpoint: &AgentCheckpoint,
    generate: &mut dyn Generate,
    workspace: &mut dyn AgentWorkspace,
    limits: Option<&AgentLimits>,
) -> Result<AgentRun, AgentError> {
    checkpoint.validate()?;
    generate.restore_checkpoint(&checkpoint.model)?;
    let messages = checkpoint.get_messages();
    let run = match run_task_loop("", Some(messages), generate, workspace, None, limits, None)? {
        RunTaskResult::Run(run) => run,
        _ => unreachable!(),
    };
    Ok(run)
}
