// WARNING: Under review - generated by LLM.

//! Port of `src/tiny_llm/agent/protocol.py`.

use std::collections::HashSet;
use std::fmt;
use std::str::FromStr;

use schemars::{JsonSchema, Schema, schema_for};
use serde::{Deserialize, Serialize};

use crate::workspace::ToolPolicy;

/// A recoverable error that can be returned to the model.
///
/// Python models this as a subclass of ``ValueError``; Rust has no exceptions,
/// so every fallible function in this crate returns it inside a ``Result``.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AgentError(pub String);

impl fmt::Display for AgentError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::error::Error for AgentError {}

/// Week 4, Day 1: a model response that finishes the task.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct FinalAction {
    #[serde(rename = "final")]
    pub final_: String,
}

/// A tool request in the model's flat JSON wire format.
///
/// Serde and JSON Schema share the required fields and reject unknown fields.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(tag = "tool", rename_all = "snake_case", deny_unknown_fields)]
pub enum ToolAction {
    ListFiles {
        #[serde(default = "default_list_path")]
        path: String,
    },
    ReadFile {
        path: String,
    },
    WriteFile {
        path: String,
        content: String,
    },
    EditFile {
        path: String,
        old: String,
        new: String,
    },
    RunCommand {
        argv: Vec<String>,
    },
}

fn default_list_path() -> String {
    ".".into()
}

pub const LIST_FILES_TOOL_NAME: &str = "list_files";
pub const READ_FILE_TOOL_NAME: &str = "read_file";
pub const WRITE_FILE_TOOL_NAME: &str = "write_file";
pub const EDIT_FILE_TOOL_NAME: &str = "edit_file";
pub const RUN_COMMAND_TOOL_NAME: &str = "run_command";

impl ToolAction {
    pub fn tool(&self) -> &'static str {
        match self {
            Self::ListFiles { .. } => LIST_FILES_TOOL_NAME,
            Self::ReadFile { .. } => READ_FILE_TOOL_NAME,
            Self::WriteFile { .. } => WRITE_FILE_TOOL_NAME,
            Self::EditFile { .. } => EDIT_FILE_TOOL_NAME,
            Self::RunCommand { .. } => RUN_COMMAND_TOOL_NAME,
        }
    }
}

impl FromStr for ToolAction {
    type Err = serde_json::Error;

    fn from_str(response: &str) -> Result<Self, Self::Err> {
        serde_json::from_str(response)
    }
}

/// Python's ``AgentAction = FinalAction | ToolAction``.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[serde(untagged)]
pub enum AgentAction {
    Final(FinalAction),
    Tool(ToolAction),
}

/// JSON Schema for the same wire format accepted by `parse_action`.
/// Tool availability is a runtime policy checked separately by `parse_action`.
pub fn action_schema() -> Schema {
    schema_for!(AgentAction)
}

/// The duck-typed workspace surface Python passes around as ``Any``.
///
/// ``run_agent`` documents it as ``available_tools`` (a set of tool names),
/// ``execute(action)`` (returning a result string), and ``modified_files`` (an
/// iterable of paths); ``build_system_prompt`` additionally reads ``policy``.
pub trait AgentWorkspace {
    /// The policy whose authorized tools the system prompt describes.
    fn policy(&self) -> &ToolPolicy;

    /// The tools this workspace accepts.
    fn available_tools(&self) -> &HashSet<String>;

    /// The files this workspace changed.
    fn modified_files(&self) -> Vec<String>;

    /// Dispatch one action and return its model-visible result.
    fn execute(&mut self, action: &ToolAction, tool_call_id: Option<&str>) -> String;
}

/// Week 4, Day 1: strictly parse and validate exactly one JSON action.
pub fn parse_action(
    response: &str,
    available_tools: Option<&HashSet<String>>,
) -> Result<AgentAction, AgentError> {
    let action: AgentAction =
        serde_json::from_str(response).map_err(|e| AgentError(format!("invalid action: {e}")))?;

    if let AgentAction::Tool(tool_action) = &action {
        let tool = tool_action.tool();
        if available_tools.is_some_and(|tools| !tools.contains(tool)) {
            return Err(AgentError(format!("not enabled tool: '{tool}'")));
        }
    }
    Ok(action)
}

/// Week 4, Day 1: describe only the tools authorized for this run.
pub fn build_system_prompt(workspace: &dyn AgentWorkspace) -> String {
    let mut lines: Vec<String> = vec![
        "You are a coding agent. Inspect the workspace before editing it.".into(),
        "Reply with exactly one JSON object and no markdown.".into(),
        r#"Finish with: {"final":"brief summary"}"#.into(),
        "Available actions:".into(),
    ];

    let get_example_string_of_tool = |tool_name: &str| -> String {
        let tool_action = match tool_name {
            LIST_FILES_TOOL_NAME => ToolAction::ListFiles { path: ".".into() },
            READ_FILE_TOOL_NAME => ToolAction::ReadFile {
                path: "README.md".into(),
            },
            WRITE_FILE_TOOL_NAME => ToolAction::WriteFile {
                path: "hello.py".into(),
                content: "...".into(),
            },
            EDIT_FILE_TOOL_NAME => ToolAction::EditFile {
                path: "hello.py".into(),
                old: "...".into(),
                new: "...".into(),
            },
            RUN_COMMAND_TOOL_NAME => ToolAction::RunCommand {
                argv: vec!["exact".into(), "arguments".into()],
            },
            _ => {
                unimplemented!()
            }
        };
        serde_json::to_string(&tool_action).expect("build tool example failed !!!")
    };

    let tools = workspace.available_tools();
    for tool in tools {
        lines.push(get_example_string_of_tool(tool));
    }

    if tools.contains(WRITE_FILE_TOOL_NAME) || tools.contains(EDIT_FILE_TOOL_NAME) {
        lines.push("Read an existing file before changing it.".into());
    }
    if tools.contains(RUN_COMMAND_TOOL_NAME) && !workspace.policy().allowed_commands.is_empty() {
        lines.push("The operator allowed only these exact command arrays:".into());
        for cmd in &workspace.policy().allowed_commands {
            lines.push(serde_json::json!(cmd).to_string());
        }
    }
    lines.extend([
        "Paths must be relative to the workspace.".into(),
        "Keep changes small and never invent file contents.".into(),
    ]);

    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::{Value, json};

    fn tool_cases() -> Vec<(Value, ToolAction, Vec<&'static str>)> {
        vec![
            (
                json!({"tool":"list_files","path":"src"}),
                ToolAction::ListFiles { path: "src".into() },
                vec![],
            ),
            (
                json!({"tool":"read_file","path":"README.md"}),
                ToolAction::ReadFile {
                    path: "README.md".into(),
                },
                vec!["path"],
            ),
            (
                json!({"tool":"write_file","path":"a.txt","content":"你好\n"}),
                ToolAction::WriteFile {
                    path: "a.txt".into(),
                    content: "你好\n".into(),
                },
                vec!["path", "content"],
            ),
            (
                json!({"tool":"edit_file","path":"a.txt","old":"a","new":"b"}),
                ToolAction::EditFile {
                    path: "a.txt".into(),
                    old: "a".into(),
                    new: "b".into(),
                },
                vec!["path", "old", "new"],
            ),
            (
                json!({"tool":"run_command","argv":["echo","hello world"]}),
                ToolAction::RunCommand {
                    argv: vec!["echo".into(), "hello world".into()],
                },
                vec!["argv"],
            ),
        ]
    }

    #[test]
    fn every_tool_deserializes_typed_arguments_and_round_trips() {
        for (payload, expected, _) in tool_cases() {
            let response = payload.to_string();
            assert_eq!(response.parse::<ToolAction>().unwrap(), expected);
            assert_eq!(
                serde_json::from_str::<ToolAction>(&response).unwrap(),
                expected
            );
            assert_eq!(serde_json::to_value(&expected).unwrap(), payload);
            assert_eq!(
                parse_action(&response, None).unwrap(),
                AgentAction::Tool(expected.clone())
            );
            assert_eq!(
                serde_json::from_str::<AgentAction>(&response).unwrap(),
                AgentAction::Tool(expected)
            );
        }
        assert_eq!(
            r#"{"tool":"list_files"}"#.parse::<ToolAction>().unwrap(),
            ToolAction::ListFiles { path: ".".into() }
        );
    }

    #[test]
    fn every_required_argument_is_enforced() {
        for (payload, _, required) in tool_cases() {
            for field in required {
                let mut missing = payload.clone();
                missing.as_object_mut().unwrap().remove(field);
                assert!(
                    parse_action(&missing.to_string(), None).is_err(),
                    "{missing}"
                );
                assert!(serde_json::from_value::<ToolAction>(missing).is_err());
            }
        }
    }

    #[test]
    fn every_tool_rejects_extra_and_mistyped_arguments() {
        for (payload, _, _) in tool_cases() {
            let mut extra = payload.clone();
            extra["unexpected"] = json!(true);
            assert!(parse_action(&extra.to_string(), None).is_err(), "{extra}");
            for field in payload
                .as_object()
                .unwrap()
                .keys()
                .filter(|field| *field != "tool")
            {
                for wrong in [Value::Null, json!(42), json!(true), json!({})] {
                    let mut invalid = payload.clone();
                    invalid[field] = wrong;
                    assert!(
                        parse_action(&invalid.to_string(), None).is_err(),
                        "{invalid}"
                    );
                }
            }
        }
        for argv in [
            json!("echo hello"),
            json!(["echo", 42]),
            json!([null]),
            json!([["echo"]]),
        ] {
            assert!(
                parse_action(&json!({"tool":"run_command","argv":argv}).to_string(), None).is_err()
            );
        }
    }

    #[test]
    fn tool_availability_is_checked_after_deserialization() {
        for (payload, expected, _) in tool_cases() {
            let response = payload.to_string();
            let enabled = HashSet::from([expected.tool().to_owned()]);
            assert!(parse_action(&response, Some(&enabled)).is_ok());
            let error = parse_action(&response, Some(&HashSet::new())).unwrap_err();
            assert!(error.0.contains("not enabled"));
        }
    }

    #[test]
    fn malformed_unknown_ambiguous_and_duplicate_actions_are_rejected() {
        for response in [
            "not json",
            "null",
            "[]",
            "42",
            r#""text""#,
            "{}",
            r#"{"tool":null}"#,
            r#"{"tool":42}"#,
            r#"{"tool":"run_shell","argv":[]}"#,
            r#"{"tool":"read_file","arguments":{"path":"a"}}"#,
            r#"{"tool":"read_file","path":"a","path":"b"}"#,
            r#"{"tool":"read_file","tool":"list_files","path":"a"}"#,
            r#"{"tool":"list_files"} {"final":"done"}"#,
            r#"{"final":"done","tool":"read_file","path":"a"}"#,
            r#"{"final":"done","extra":true}"#,
            r#"{"final":"a","final":"b"}"#,
            r#"{"final":null}"#,
        ] {
            assert!(parse_action(response, None).is_err(), "{response}");
        }
    }

    #[test]
    fn final_action_deserializes_and_serializes_with_wire_field_name() {
        let response = r#"{"final":"done"}"#;
        let expected = AgentAction::Final(FinalAction {
            final_: "done".into(),
        });
        assert_eq!(parse_action(response, None).unwrap(), expected);
        assert_eq!(
            serde_json::from_str::<AgentAction>(response).unwrap(),
            expected
        );
        assert_eq!(serde_json::to_string(&expected).unwrap(), response);
    }

    #[test]
    fn schema_covers_each_tool_and_enforces_the_same_fields() {
        let schema = serde_json::to_value(schema_for!(ToolAction)).unwrap();
        let variants = schema["oneOf"].as_array().unwrap();
        assert_eq!(variants.len(), tool_cases().len());
        for (payload, _, fields) in tool_cases() {
            let variant = variants
                .iter()
                .find(|v| v["properties"]["tool"]["const"] == payload["tool"])
                .unwrap();
            assert_eq!(variant["additionalProperties"], false);
            let mut required = vec![json!("tool")];
            required.extend(fields.iter().map(|field| json!(field)));
            let actual = variant["required"].as_array().unwrap();
            assert_eq!(actual.len(), required.len());
            assert!(required.iter().all(|field| actual.contains(field)));
            assert_eq!(
                variant["properties"].as_object().unwrap().len(),
                payload.as_object().unwrap().len()
            );
            for field in payload
                .as_object()
                .unwrap()
                .keys()
                .filter(|field| *field != "tool")
            {
                let property = &variant["properties"][field];
                if field == "argv" {
                    assert_eq!(property["type"], "array");
                    assert_eq!(property["items"]["type"], "string");
                } else {
                    assert_eq!(property["type"], "string");
                }
            }
            if payload["tool"] == "list_files" {
                assert_eq!(variant["properties"]["path"]["default"], ".");
            }
        }
        let action = serde_json::to_value(action_schema()).unwrap();
        assert_eq!(action["anyOf"].as_array().unwrap().len(), 2);
        assert_eq!(
            action["$defs"]["FinalAction"]["additionalProperties"],
            false
        );
    }
}
