// WARNING: Under review - generated by LLM.

//! Week 4, Day 6: inspect and steer one paused checkpoint.

use crate::checkpoint::AgentCheckpoint;
use crate::generation::Generate;
use crate::r#loop::{AgentLimits, AgentRun};
use crate::protocol::{AgentError, AgentWorkspace};

/// Public facts available at one complete-observation pause.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct AgentStatus {
    pub task: String,
    pub last_action: String,
    pub last_evidence: String,
    pub next_step: String,
}

/// Derive a bounded public status from a complete tool observation.
pub fn inspect_checkpoint(
    checkpoint: &AgentCheckpoint,
    evidence_chars: i64,
) -> Result<AgentStatus, AgentError> {
    todo!()
}

/// Append one visible operator message and resume from the saved prefix.
pub fn resume_with_steering(
    checkpoint: &AgentCheckpoint,
    steering: &str,
    generate: &mut dyn Generate,
    workspace: &mut dyn AgentWorkspace,
    limits: Option<&AgentLimits>,
) -> Result<AgentRun, AgentError> {
    todo!()
}
