// WARNING: Under review - generated by LLM.

//! Week 4, Day 3 learner surface for workspace effects.

use std::collections::{BTreeSet, HashMap, HashSet};
use std::fs;
use std::io::ErrorKind;
use std::os::unix::fs::MetadataExt;
use std::path::{Component, Path, PathBuf};

use sha2::Digest;
use sha2::digest::Update;

use crate::protocol::{AgentError, AgentWorkspace, ToolAction};
use crate::protocol::{
    EDIT_FILE_TOOL_NAME, LIST_FILES_TOOL_NAME, READ_FILE_TOOL_NAME, RUN_COMMAND_TOOL_NAME,
    WRITE_FILE_TOOL_NAME,
};
use crate::receipts::ReceiptStore;

fn is_protected(name: &str) -> bool {
    matches!(
        name.to_lowercase().as_str(),
        ".git"
            | ".env"
            | ".ssh"
            | ".aws"
            | "credentials"
            | "id_rsa"
            | "id_ed25519"
            | "id_dsa"
            | "id_ecdsa"
    ) || name.starts_with(".env.")
        || name.ends_with(".key")
        || name.ends_with(".pem")
}

/// One operator approval or a model-visible denial reason.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ApprovalDecision {
    pub approved: bool,
    /// Python default: `""`.
    pub reason: String,
}

impl ApprovalDecision {
    pub fn new(approved: bool, reason: String) -> Result<Self, AgentError> {
        let decision = Self { approved, reason };
        decision.post_init()?;
        Ok(decision)
    }

    /// Python's ``__post_init__``.
    pub fn post_init(&self) -> Result<(), AgentError> {
        // TODO: validate the decision and require a reason for denials.
        todo!()
    }
}

/// Python's ``bool | ApprovalDecision`` confirmation result.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ConfirmResult {
    Approved(bool),
    Decision(ApprovalDecision),
}

/// Python's ``Callable[[ToolAction], bool | ApprovalDecision]``.
pub type ConfirmTool = Box<dyn Fn(&ToolAction) -> ConfirmResult>;

/// Tools and limits authorized for one explicit workspace root.
#[derive(Debug, Clone, PartialEq)]
pub struct ToolPolicy {
    pub root: PathBuf,
    /// Python default: ``False``.
    pub allow_writes: bool,
    /// Python default: ``()``.
    pub allowed_commands: Vec<Vec<String>>,
    /// Python default: ``64 * 1024``.
    pub max_file_bytes: i64,
    /// Python default: ``200``.
    pub max_list_entries: i64,
    /// Python default: ``64 * 1024``.
    pub max_write_bytes: i64,
    /// Python default: ``30.0``.
    pub command_timeout_seconds: f64,
}

impl ToolPolicy {
    pub const DEFAULT_MAX_FILE_BYTES: i64 = 64 * 1024;
    pub const DEFAULT_MAX_LIST_ENTRIES: i64 = 200;
    pub const DEFAULT_MAX_WRITE_BYTES: i64 = 64 * 1024;
    pub const DEFAULT_COMMAND_TIMEOUT_SECONDS: f64 = 30.0;

    pub fn new(
        root: PathBuf,
        max_file_bytes: i64,
        max_list_entries: i64,
        allow_writes: bool,
        allowed_commands: Vec<Vec<String>>,
        max_write_bytes: i64,
        command_timeout_seconds: f64,
    ) -> Result<Self, AgentError> {
        let mut policy = Self {
            root,
            allow_writes,
            allowed_commands,
            max_file_bytes,
            max_list_entries,
            max_write_bytes,
            command_timeout_seconds,
        };
        policy.post_init()?;
        Ok(policy)
    }

    /// Python's ``__post_init__``.
    pub fn post_init(&mut self) -> Result<(), AgentError> {
        // normalize and validate the root and positive limits.
        if self.root.is_symlink() {
            return Err(AgentError("root of workspace must not be symlink".into()));
        }
        self.root = self
            .root
            .canonicalize()
            .map_err(|_| AgentError("workspace root does not exist".into()))?;
        if !self.root.is_dir() {
            return Err(AgentError("workspace root must be a directoty".into()));
        }

        if self.max_file_bytes <= 0 {
            return Err(AgentError("max_file_bytes must be positive".into()));
        }
        if self.max_list_entries <= 0 {
            return Err(AgentError("max_list_entries must be positive".into()));
        }
        if self.max_write_bytes <= 0 {
            return Err(AgentError("max_write_bytes must be positive".into()));
        }
        if self.command_timeout_seconds <= 0.0 {
            return Err(AgentError(
                "command_timeout_seconds must be positive".into(),
            ));
        }
        Ok(())
    }
}

/// Run the Day 3 tools under one policy and approval callback.
pub struct Workspace {
    pub policy: ToolPolicy,
    /// Python default: ``None``.
    pub confirm_tool: Option<ConfirmTool>,
    /// Python default: ``ReceiptStore()``.
    pub receipt_store: ReceiptStore,
    observed: HashMap<PathBuf, String>,
    modified: BTreeSet<String>,
    next_call_number: i64,

    available_tools: HashSet<String>,
}

impl Workspace {
    pub fn new(
        policy: ToolPolicy,
        confirm_tool: Option<ConfirmTool>,
        receipt_store: ReceiptStore,
    ) -> Self {
        let available_tools = get_available_tools(&policy);
        Self {
            policy,
            confirm_tool,
            receipt_store,
            observed: HashMap::new(),
            modified: BTreeSet::new(),
            next_call_number: 1,
            available_tools,
        }
    }

    /// Return only the tools enabled by this policy.
    pub fn available_tools(&self) -> &HashSet<String> {
        &self.available_tools
    }

    /// Return the files changed by this workspace in sorted order.
    pub fn modified_files(&self) -> Vec<String> {
        self.modified.iter().cloned().collect()
    }

    /// Resolve one relative path without traversal or symlinks.
    pub fn resolve_path(&self, raw: &str, must_exist: bool) -> Result<PathBuf, AgentError> {
        if raw.trim().is_empty() || raw.contains('\0') {
            return Err(AgentError(
                "path must be non-empty and contain no NUL bytes".into(),
            ));
        }
        let relative = Path::new(raw);
        if relative.is_absolute() {
            return Err(AgentError("raw path must be relative".into()));
        }
        let inaccessible = |error| AgentError(format!("path is not accessible: {error}"));
        let mut resolved = self.policy.root.canonicalize().map_err(inaccessible)?;
        for component in relative.components() {
            if component == Component::CurDir {
                continue;
            }

            let name = component.as_os_str().to_string_lossy().to_string();
            if is_protected(&name) {
                return Err(AgentError("raw path is not accessible".into()));
            }

            resolved.push(component.as_os_str());
            match fs::symlink_metadata(&resolved) {
                Ok(metadata) => {
                    if metadata.file_type().is_symlink() {
                        return Err(AgentError("symlinks are not accessible".into()));
                    }
                    resolved = resolved.canonicalize().map_err(inaccessible)?;
                }
                Err(error) if error.kind() == ErrorKind::NotFound && !must_exist => {}
                Err(error) => return Err(inaccessible(error)),
            }
        }
        let relative = resolved
            .strip_prefix(&self.policy.root)
            .map_err(|_| AgentError("resolved path is outside the workspace root".into()))?;
        Ok(resolved)
    }

    /// List one directory, bounded by the policy.
    pub fn list_files(&mut self, raw: &str) -> Result<String, AgentError> {
        let resolved = self.resolve_path(raw, true)?;
        if !resolved.is_dir() {
            return Err(AgentError("path is not a directory".into()));
        }

        let mut entries = vec![];
        for e in fs::read_dir(&resolved).map_err(|e| AgentError(e.to_string()))? {
            let entry = e.map_err(|e| AgentError(e.to_string()))?;
            let path = entry.path();
            if path.is_symlink() {
                continue;
            }
            let Some(name) = path
                .file_name()
                .map(|name| name.to_string_lossy().to_string())
            else {
                continue;
            };
            if is_protected(&name) && name.starts_with(".") {
                continue;
            }
            let prefix = if path.is_dir() { "dir " } else { "file " };
            let relative = path
                .strip_prefix(&self.policy.root)
                .map_err(|e| AgentError(e.to_string()))?;
            entries.push((relative.to_string_lossy().to_string(), prefix));
        }

        entries.sort();
        let entries = entries[..entries.len().min(self.policy.max_list_entries as usize)]
            .iter()
            .map(|(name, prefix)| {
                let mut prefix = prefix.to_string();
                prefix.push_str(name);
                prefix
            })
            .collect::<Vec<_>>();

        let result = entries.join("\n");
        Ok(if result.trim().is_empty() {
            "(empty directory)".into()
        } else {
            result
        })
    }

    /// Read one bounded UTF-8 regular file.
    pub fn read_file(&mut self, raw: &str) -> Result<String, AgentError> {
        let resolved = self.resolve_path(raw, true)?;
        let metadata = resolved.metadata().map_err(|e| AgentError(e.to_string()))?;
        if metadata.is_dir() {
            return Err(AgentError("read_file path must be a regular file".into()));
        }
        if metadata.size() >= self.policy.max_file_bytes as u64 {
            return Err(AgentError(format!(
                "exceeds {} bytes",
                self.policy.max_file_bytes
            )));
        }
        let content = fs::read_to_string(&resolved)
            .map_err(|e| AgentError(format!("invalid UTF-8: {}", e)))?;
        let hash: String = sha2::Sha256::new()
            .chain(&content)
            .finalize()
            .iter()
            .map(|b| *b as char)
            .collect();

        self.observed.insert(resolved, hash);
        Ok(content)
    }

    /// Atomically create a file or replace one previously read unchanged.
    pub fn write_file(&mut self, raw: &str, content: &str) -> Result<String, AgentError> {
        todo!()
    }

    /// Replace one exact occurrence in a previously read unchanged file.
    pub fn edit_file(&mut self, raw: &str, old: &str, new: &str) -> Result<String, AgentError> {
        todo!()
    }

    /// Run one exact allowed argument vector without a shell.
    pub fn run_command(&mut self, argv: &[String]) -> Result<String, AgentError> {
        todo!()
    }

    /// Dispatch one action, approving and receipting effects once.
    pub fn execute(&mut self, action: &ToolAction, tool_call_id: Option<&str>) -> String {
        if !self.available_tools.contains(action.tool()) {
            return format!("error: tool is not enabled: {}", action.tool());
        }

        let result = match action {
            ToolAction::ListFiles { path } => self.list_files(path),
            ToolAction::ReadFile { path } => self.read_file(path),
            ToolAction::WriteFile { .. } => {
                todo!()
            }
            ToolAction::EditFile { .. } => {
                todo!()
            }
            ToolAction::RunCommand { .. } => {
                todo!()
            }
        };
        result.unwrap_or_else(|e| format!("error: {}", e))
    }
}

impl AgentWorkspace for Workspace {
    fn policy(&self) -> &ToolPolicy {
        &self.policy
    }

    fn available_tools(&self) -> &HashSet<String> {
        Workspace::available_tools(self)
    }

    fn modified_files(&self) -> Vec<String> {
        Workspace::modified_files(self)
    }

    fn execute(&mut self, action: &ToolAction, tool_call_id: Option<&str>) -> String {
        Workspace::execute(self, action, tool_call_id)
    }
}

fn get_available_tools(policy: &ToolPolicy) -> HashSet<String> {
    let mut tools = HashSet::from([LIST_FILES_TOOL_NAME.into(), READ_FILE_TOOL_NAME.into()]);

    if policy.allow_writes {
        tools.extend([WRITE_FILE_TOOL_NAME.into(), EDIT_FILE_TOOL_NAME.into()]);
    }

    if !policy.allowed_commands.is_empty() {
        tools.insert(RUN_COMMAND_TOOL_NAME.into());
    }

    tools
}
