// WARNING: Under review - generated by LLM.

//! Week 4, Day 3 learner surface for workspace effects.

use std::collections::{BTreeSet, HashMap, HashSet};
use std::fs;
use std::io::ErrorKind;
use std::os::unix::fs::MetadataExt;
use std::path::{Component, Path, PathBuf};
use std::process::Command;

use tempfile::NamedTempFile;

use crate::EffectReceipt;
use crate::protocol::{AgentError, AgentWorkspace, ToolAction};
use crate::protocol::{
    EDIT_FILE_TOOL_NAME, LIST_FILES_TOOL_NAME, READ_FILE_TOOL_NAME, RUN_COMMAND_TOOL_NAME,
    WRITE_FILE_TOOL_NAME,
};
use crate::receipts::ReceiptStore;
use crate::utils::{
    check_command_line, get_sha256_of_contents, get_sha256_of_file, read_content_of_file,
    run_command_with_timeout, to_agent_error, write_to_file,
};

fn is_protected(name: &str) -> bool {
    matches!(
        name.to_lowercase().as_str(),
        ".git"
            | ".env"
            | ".ssh"
            | ".aws"
            | "credentials"
            | "id_rsa"
            | "id_ed25519"
            | "id_dsa"
            | "id_ecdsa"
    ) || name.starts_with(".env.")
        || name.ends_with(".key")
        || name.ends_with(".pem")
}

/// One operator approval or a model-visible denial reason.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ApprovalDecision {
    pub approved: bool,
    /// Python default: `""`.
    pub reason: String,
}

impl ApprovalDecision {
    pub fn new(approved: bool, reason: String) -> Result<Self, AgentError> {
        let decision = Self { approved, reason };
        decision.post_init()?;
        Ok(decision)
    }

    /// Python's ``__post_init__``.
    pub fn post_init(&self) -> Result<(), AgentError> {
        // TODO: validate the decision and require a reason for denials.
        todo!()
    }
}

/// Python's ``bool | ApprovalDecision`` confirmation result.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ConfirmResult {
    Approved(bool),
    Decision(ApprovalDecision),
}

/// Python's ``Callable[[ToolAction], bool | ApprovalDecision]``.
pub type ConfirmTool = Box<dyn Fn(&ToolAction) -> ConfirmResult>;

/// Tools and limits authorized for one explicit workspace root.
#[derive(Debug, Clone, PartialEq)]
pub struct ToolPolicy {
    pub root: PathBuf,
    /// Python default: ``False``.
    pub allow_writes: bool,
    /// Python default: ``()``.
    pub allowed_commands: Vec<Vec<String>>,
    /// Python default: ``64 * 1024``.
    pub max_file_bytes: i64,
    /// Python default: ``200``.
    pub max_list_entries: i64,
    /// Python default: ``64 * 1024``.
    pub max_write_bytes: i64,
    /// Python default: ``30.0``.
    pub command_timeout_seconds: f64,
}

impl ToolPolicy {
    pub const DEFAULT_MAX_FILE_BYTES: i64 = 64 * 1024;
    pub const DEFAULT_MAX_LIST_ENTRIES: i64 = 200;
    pub const DEFAULT_MAX_WRITE_BYTES: i64 = 64 * 1024;
    pub const DEFAULT_COMMAND_TIMEOUT_SECONDS: f64 = 30.0;

    pub fn new(
        root: PathBuf,
        max_file_bytes: i64,
        max_list_entries: i64,
        allow_writes: bool,
        allowed_commands: Vec<Vec<String>>,
        max_write_bytes: i64,
        command_timeout_seconds: f64,
    ) -> Result<Self, AgentError> {
        let mut policy = Self {
            root,
            allow_writes,
            allowed_commands,
            max_file_bytes,
            max_list_entries,
            max_write_bytes,
            command_timeout_seconds,
        };
        policy.post_init()?;
        Ok(policy)
    }

    /// Python's ``__post_init__``.
    pub fn post_init(&mut self) -> Result<(), AgentError> {
        // normalize and validate the root and positive limits.
        if self.root.is_symlink() {
            return Err(AgentError("root of workspace must not be symlink".into()));
        }
        self.root = self
            .root
            .canonicalize()
            .map_err(|_| AgentError("workspace root does not exist".into()))?;
        if !self.root.is_dir() {
            return Err(AgentError("workspace root must be a directoty".into()));
        }

        for cmd in &self.allowed_commands {
            check_command_line(cmd)?;
        }

        if self.max_file_bytes <= 0 {
            return Err(AgentError(
                "max_file_bytes must be finite and positive".into(),
            ));
        }
        if self.max_list_entries <= 0 {
            return Err(AgentError(
                "max_list_entries must be finite and positive".into(),
            ));
        }
        if self.max_write_bytes <= 0 {
            return Err(AgentError(
                "max_write_bytes must be finite and positive".into(),
            ));
        }
        if self.command_timeout_seconds <= 0.0
            || self.command_timeout_seconds.is_nan()
            || self.command_timeout_seconds.is_infinite()
        {
            return Err(AgentError(
                "command_timeout_seconds must be finite and positive".into(),
            ));
        }
        Ok(())
    }
}

/// Run the Day 3 tools under one policy and approval callback.
pub struct Workspace {
    pub policy: ToolPolicy,
    /// Python default: ``None``.
    pub confirm_tool: Option<ConfirmTool>,
    /// Python default: ``ReceiptStore()``.
    pub receipt_store: ReceiptStore,
    /// observed sha256 of file; path must be resolved.
    observed: HashMap<String, String>,
    modified: BTreeSet<String>,
    next_tool_call_id: i64,
    available_tools: HashSet<String>,
}

impl Workspace {
    pub fn new(
        policy: ToolPolicy,
        confirm_tool: Option<ConfirmTool>,
        receipt_store: ReceiptStore,
    ) -> Self {
        let available_tools = get_available_tools(&policy);
        Self {
            policy,
            confirm_tool,
            receipt_store,
            observed: HashMap::new(),
            modified: BTreeSet::new(),
            next_tool_call_id: 1,
            available_tools,
        }
    }

    /// Return only the tools enabled by this policy.
    pub fn available_tools(&self) -> &HashSet<String> {
        &self.available_tools
    }

    /// Return the files changed by this workspace in sorted order.
    pub fn modified_files(&self) -> Vec<String> {
        self.modified.iter().cloned().collect()
    }

    /// Resolve one relative path without traversal or symlinks.
    pub fn resolve_path(
        &self,
        raw: &str,
        must_exist: bool,
    ) -> Result<(PathBuf, String), AgentError> {
        if raw.trim().is_empty() || raw.contains('\0') {
            return Err(AgentError(
                "path must be non-empty and contain no NUL bytes".into(),
            ));
        }
        let relative = Path::new(raw);
        if relative.is_absolute() {
            return Err(AgentError("raw path must be relative".into()));
        }
        let inaccessible = |error| AgentError(format!("path is not accessible: {error}"));
        let mut resolved = self.policy.root.canonicalize().map_err(inaccessible)?;
        for component in relative.components() {
            if component == Component::CurDir {
                continue;
            }

            let name = component.as_os_str().to_string_lossy().to_string();
            if is_protected(&name) {
                return Err(AgentError("raw path is not accessible".into()));
            }

            resolved.push(component.as_os_str());
            match fs::symlink_metadata(&resolved) {
                Ok(metadata) => {
                    if metadata.file_type().is_symlink() {
                        return Err(AgentError("symlinks are not accessible".into()));
                    }
                    resolved = resolved.canonicalize().map_err(inaccessible)?;
                }
                Err(error) if error.kind() == ErrorKind::NotFound && !must_exist => {}
                Err(error) => return Err(inaccessible(error)),
            }
        }
        let relative = self.relative_to_root(&resolved)?;
        Ok((resolved, relative))
    }

    fn relative_to_root(&self, resolved: &Path) -> Result<String, AgentError> {
        resolved
            .strip_prefix(&self.policy.root)
            .map(|p| p.to_string_lossy().to_string())
            .map_err(|_| AgentError("resolved path is outside the workspace root".into()))
    }

    /// List one directory, bounded by the policy.
    fn list_files(&mut self, action: &ToolAction) -> Result<String, AgentError> {
        let ToolAction::ListFiles { path: raw } = action else {
            return Err(AgentError("expected list_files action".into()));
        };
        let (resolved, _) = self.resolve_path(raw, true)?;
        if !resolved.is_dir() {
            return Err(AgentError("path is not a directory".into()));
        }

        let mut entries = vec![];
        for e in fs::read_dir(&resolved).map_err(|e| AgentError(e.to_string()))? {
            let entry = e.map_err(|e| AgentError(e.to_string()))?;
            let path = entry.path();
            if path.is_symlink() {
                continue;
            }
            let Some(name) = path
                .file_name()
                .map(|name| name.to_string_lossy().to_string())
            else {
                continue;
            };
            if is_protected(&name) && name.starts_with(".") {
                continue;
            }
            let prefix = if path.is_dir() { "dir " } else { "file " };
            let relative = self.relative_to_root(&path)?;
            entries.push((relative, prefix));
        }

        entries.sort();
        let entries = entries[..entries.len().min(self.policy.max_list_entries as usize)]
            .iter()
            .map(|(name, prefix)| {
                let mut prefix = prefix.to_string();
                prefix.push_str(name);
                prefix
            })
            .collect::<Vec<_>>();

        let result = entries.join("\n");
        Ok(if result.trim().is_empty() {
            "(empty directory)".into()
        } else {
            result
        })
    }

    /// Read one bounded UTF-8 regular file.
    fn read_file(&mut self, action: &ToolAction) -> Result<String, AgentError> {
        let ToolAction::ReadFile { path: raw } = action else {
            return Err(AgentError("expected read_file action".into()));
        };
        let (resolved, relative) = self.resolve_path(raw, true)?;
        let metadata = resolved.metadata().map_err(|e| AgentError(e.to_string()))?;
        if metadata.is_dir() {
            return Err(AgentError("read_file path must be a regular file".into()));
        }
        if metadata.size() >= self.policy.max_file_bytes as u64 {
            return Err(AgentError(format!(
                "exceeds {} bytes",
                self.policy.max_file_bytes
            )));
        }
        let content = read_content_of_file(&resolved)?;
        let hash = get_sha256_of_contents(&[content.as_bytes()]);

        self.observed.insert(relative, hash);
        Ok(content)
    }

    /// write_file: Atomically create a file or replace one previously read unchanged.
    ///
    /// edit_file: Replace one exact occurrence in a previously read unchanged file.
    fn write_or_edit_file(
        &mut self,
        action: &ToolAction,
        tool_call_id: String,
    ) -> Result<String, AgentError> {
        let (raw, old, new, verb) = match action {
            ToolAction::WriteFile { path, content } => {
                (path.as_str(), None, content.as_str(), "wrote")
            }
            ToolAction::EditFile { path, old, new } => {
                (path.as_str(), Some(old.as_str()), new.as_str(), "edited")
            }
            _ => return Err(AgentError("expected write_file or edit_file action".into())),
        };

        if let Some(old) = old
            && old.is_empty()
        {
            return Err(AgentError(
                "the old content to be edited cannot be empty".into(),
            ));
        }
        if new.len() >= self.policy.max_write_bytes as usize {
            return Err(AgentError(format!(
                "exceeds {} bytes",
                self.policy.max_write_bytes
            )));
        }

        let (absolute, relative) = self.resolve_path(raw, old.is_some())?;
        let exists = absolute.try_exists().map_err(to_agent_error)?;
        let observed = self.observed.get(&relative).map_or("", |v| v.as_str());
        let mut content = String::new();

        if !exists && !absolute.parent().is_some_and(|p| p.exists() && p.is_dir()) {
            return Err(AgentError(format!(
                "parent dir of write_file {:?} not exists",
                absolute
            )));
        }
        if exists {
            if observed.is_empty() {
                return Err(AgentError(
                    "read the existing file before changing it".into(),
                ));
            }

            content = read_content_of_file(&absolute)?;
            let current = get_sha256_of_contents(&[content.as_bytes()]);
            if current != observed {
                return Err(AgentError("file changed since it was read".into()));
            }
        }

        let contents_to_write = if let Some(old) = old {
            // old string occurs exactly once
            let Some(edit_pos) = content.find(old) else {
                return Err(AgentError("old content not found in the file".into()));
            };
            if let Some(last) = content.rfind(old)
                && last != edit_pos
            {
                return Err(AgentError("old content should occurs exactly once".into()));
            }
            vec![
                &content.as_bytes()[..edit_pos],
                new.as_bytes(),
                &content.as_bytes()[edit_pos + old.len()..],
            ]
        } else {
            vec![new.as_bytes()]
        };

        let temp_file = self.create_temporary_file(&absolute)?;
        write_to_file(temp_file.path(), &contents_to_write)?;

        self.confirm(action)?;

        if get_sha256_of_file(&absolute).unwrap_or("".into()) != observed {
            return Err(AgentError("file changed since it was read".into()));
        }

        fs::rename(&temp_file, &absolute).map_err(to_agent_error)?;

        let result = format!("{} {}", verb, relative);
        self.modified.insert(relative.clone());
        self.observed
            .insert(relative.clone(), get_sha256_of_contents(&contents_to_write));

        self.receipt_store.put(EffectReceipt::new(
            tool_call_id,
            action.clone(),
            "ok".into(),
            result.clone(),
            vec![relative],
        )?)?;

        Ok(result)
    }

    /// Run one exact allowed argument vector without a shell.
    fn run_command(
        &mut self,
        action: &ToolAction,
        tool_call_id: String,
    ) -> Result<String, AgentError> {
        const MAX_COMMAND_OUTPUT_CHARS: usize = 10000;

        let ToolAction::RunCommand { argv } = action else {
            return Err(AgentError("expected run_command action".into()));
        };

        check_command_line(argv)?;

        let mut not_found = true;
        for cmdline in &self.policy.allowed_commands {
            if argv == cmdline {
                not_found = false;
                break;
            }
        }
        if not_found {
            return Err(AgentError("command is not allowed".into()));
        }

        let mut cmd = Command::new(&argv[0]);
        cmd.current_dir(&self.policy.root);
        for arg in argv.iter().skip(1) {
            cmd.arg(arg);
        }

        self.confirm(action)?;

        let (output, timeout) = run_command_with_timeout(
            cmd,
            std::time::Duration::from_secs_f64(self.policy.command_timeout_seconds),
        )?;
        let success = output.status.success();

        let mut captured = output.stdout;
        captured.extend(output.stderr);
        captured.truncate(MAX_COMMAND_OUTPUT_CHARS);

        let result = format!(
            "status: {}\noutput:\n{}",
            if timeout {
                "timeout".into()
            } else {
                output.status.code().unwrap_or(-1).to_string()
            },
            String::from_utf8(captured).map_err(to_agent_error)?
        );

        self.receipt_store.put(EffectReceipt::new(
            tool_call_id,
            action.clone(),
            if !timeout && success { "ok" } else { "error" }.into(),
            result.clone(),
            vec![],
        )?)?;

        Ok(result)
    }

    /// Dispatch one action, approving and receipting effects once.
    pub fn execute(&mut self, action: &ToolAction, tool_call_id: Option<&str>) -> String {
        let error_to_string = |e| format!("error: {}", e);

        let tool_call_id = if is_effective_action(action) {
            let tool_call_id = tool_call_id.map_or(self.next_tool_call_id(), |id| id.to_string());
            if let Some(previous) = self.receipt_store.get(&tool_call_id) {
                if &previous.tool != action {
                    return error_to_string(AgentError(
                        "tool call id was already used for another action".into(),
                    ));
                }
                return previous.result.clone();
            }
            tool_call_id
        } else {
            String::new()
        };

        if !self.available_tools.contains(action.tool()) {
            return format!("error: tool is not enabled: {}", action.tool());
        }

        let result = match action {
            ToolAction::ListFiles { .. } => self.list_files(action),
            ToolAction::ReadFile { .. } => self.read_file(action),
            ToolAction::WriteFile { .. } | ToolAction::EditFile { .. } => {
                self.write_or_edit_file(action, tool_call_id)
            }
            ToolAction::RunCommand { .. } => self.run_command(action, tool_call_id),
        };
        result.unwrap_or_else(error_to_string)
    }

    fn next_tool_call_id(&mut self) -> String {
        let mut tool_call_id: String;
        loop {
            tool_call_id = format!("call-{}", self.next_tool_call_id);
            self.next_tool_call_id += 1;

            if self.receipt_store.get(&tool_call_id).is_none() {
                break;
            }
        }
        tool_call_id
    }

    fn confirm(&self, action: &ToolAction) -> Result<(), AgentError> {
        if let Some(confirm_tool) = self.confirm_tool.as_ref() {
            match confirm_tool(action) {
                ConfirmResult::Approved(false) => {
                    return Err(AgentError(format!(
                        "operator denied {} tool action",
                        action.tool()
                    )));
                }
                ConfirmResult::Decision(ApprovalDecision {
                    approved: false,
                    reason,
                }) => {
                    return Err(AgentError(format!(
                        "operator denied {} tool action: {}",
                        action.tool(),
                        reason
                    )));
                }
                _ => {}
            }
        }
        Ok(())
    }

    pub fn create_temporary_file(&self, near: &Path) -> Result<NamedTempFile, AgentError> {
        let parent = near.parent().unwrap_or(&self.policy.root);
        NamedTempFile::new_in(parent).map_err(to_agent_error)
    }
}

impl AgentWorkspace for Workspace {
    fn policy(&self) -> &ToolPolicy {
        &self.policy
    }

    fn available_tools(&self) -> &HashSet<String> {
        &self.available_tools
    }

    fn modified_files(&self) -> Vec<String> {
        Workspace::modified_files(self)
    }

    fn execute(&mut self, action: &ToolAction, tool_call_id: Option<&str>) -> String {
        Workspace::execute(self, action, tool_call_id)
    }
}

fn get_available_tools(policy: &ToolPolicy) -> HashSet<String> {
    let mut tools = HashSet::from([LIST_FILES_TOOL_NAME.into(), READ_FILE_TOOL_NAME.into()]);

    if policy.allow_writes {
        tools.extend([WRITE_FILE_TOOL_NAME.into(), EDIT_FILE_TOOL_NAME.into()]);
    }

    if !policy.allowed_commands.is_empty() {
        tools.insert(RUN_COMMAND_TOOL_NAME.into());
    }

    tools
}

fn is_effective_action(action: &ToolAction) -> bool {
    matches!(
        action,
        ToolAction::WriteFile { .. } | ToolAction::EditFile { .. } | ToolAction::RunCommand { .. }
    )
}
