// WARNING: Under review - generated by LLM.

//! Week 4, Day 5: compact old effect observations without losing evidence.

use crate::generation::Message;
use crate::protocol::AgentError;
use crate::receipts::EffectReceipt;

/// One model-visible transcript and the tokens reclaimed from it.
#[derive(Debug, Clone, PartialEq)]
pub struct CompactionResult {
    pub messages: Vec<Message>,
    pub compacted_interactions: i64,
    pub tokens_before: i64,
    pub tokens_after: i64,
    pub receipt_ids: Vec<String>,
}

impl CompactionResult {
    /// Return the exact token reduction reported by the supplied counter.
    pub fn saved_tokens(&self) -> i64 {
        todo!()
    }
}

/// Compact old completed effects when their exact receipt matches.
pub fn compact_completed_interactions(
    messages: &[Message],
    receipts: &[EffectReceipt],
    count_tokens: &dyn Fn(&[Message]) -> i64,
    keep_recent: i64,
    result_preview_chars: i64,
) -> Result<CompactionResult, AgentError> {
    todo!()
}
