// WARNING: Under review - generated by LLM.

//! Week 4 agent package.
//!
//! Port of `src/tiny_llm/agent/__init__.py`.

// The learner surface is a skeleton: every ported body is `todo!()`, so its
// parameters are unused and much of the API is not yet called anywhere.
#![allow(unused_variables, dead_code)]

pub mod branching;
pub mod checkpoint;
pub mod compaction;
pub mod evaluation;
pub mod evidence;
pub mod generation;
pub mod model_service;
pub mod r#loop;
pub mod protocol;
pub mod receipts;
pub mod steering;
pub mod workspace;

pub use crate::branching::{BranchOutcome, KvPrefixGenerator, PrefixReuse, run_branch, select_branch};
pub use crate::checkpoint::{AgentCheckpoint, ModelCheckpoint, create_checkpoint};
pub use crate::compaction::{CompactionResult, compact_completed_interactions};
pub use crate::evaluation::{
    EvaluationCase, EvaluationCheck, EvaluationReport, FileExpectation, ReceiptExpectation,
    ResultExpectation, evaluate_run,
};
pub use crate::evidence::{ArtifactRef, ArtifactStore, BoundedEvidenceWorkspace};
pub use crate::generation::{generate_response, initial_messages};
pub use crate::protocol::{AgentError, FinalAction, ToolAction, build_system_prompt, parse_action};
pub use crate::r#loop::{
    AgentEvent, AgentLimits, AgentRun, resume_agent, run_agent, run_to_checkpoint,
};
pub use crate::receipts::{EffectReceipt, ReceiptStore};
pub use crate::steering::{AgentStatus, inspect_checkpoint, resume_with_steering};
pub use crate::workspace::{ApprovalDecision, ToolPolicy, Workspace};
