// WARNING: Under review - generated by LLM.

//! Port of `src/tiny_llm/agent/protocol.py`.

use std::collections::{HashMap, HashSet};
use std::fmt;
use std::sync::LazyLock;

use crate::workspace::ToolPolicy;

use serde_json::{Map, Value};

/// A recoverable error that can be returned to the model.
///
/// Python models this as a subclass of ``ValueError``; Rust has no exceptions,
/// so every fallible function in this crate returns it inside a ``Result``.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AgentError(pub String);

impl fmt::Display for AgentError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::error::Error for AgentError {}

/// Week 4, Day 1: a model response that finishes the task.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct FinalAction {
    pub final_: String,
}

/// Week 4, Day 1: one validated tool request from the model.
#[derive(Debug, Clone, PartialEq)]
pub struct ToolAction {
    pub tool: String,
    /// Python's ``dict[str, Any]``: an arbitrary JSON object.
    pub arguments: Map<String, Value>,
}

/// Python's ``AgentAction = FinalAction | ToolAction``.
#[derive(Debug, Clone, PartialEq)]
pub enum AgentAction {
    Final(FinalAction),
    Tool(ToolAction),
}

/// The duck-typed workspace surface Python passes around as ``Any``.
///
/// ``run_agent`` documents it as ``available_tools`` (a set of tool names),
/// ``execute(action)`` (returning a result string), and ``modified_files`` (an
/// iterable of paths); ``build_system_prompt`` additionally reads ``policy``.
pub trait AgentWorkspace {
    /// The policy whose authorized tools the system prompt describes.
    fn policy(&self) -> &ToolPolicy;

    /// The tools this workspace accepts.
    fn available_tools(&self) -> &HashSet<String>;

    /// The files this workspace changed.
    fn modified_files(&self) -> Vec<String>;

    /// Dispatch one action and return its model-visible result.
    fn execute(
        &mut self,
        action: &ToolAction,
        tool_call_id: Option<&str>,
    ) -> Result<String, AgentError>;
}

/// Required and optional argument names for every Day 1 tool.
pub static TOOL_FIELDS: LazyLock<
    HashMap<&'static str, (HashSet<&'static str>, HashSet<&'static str>)>,
> = LazyLock::new(|| {
    HashMap::from([
        ("list_files", (HashSet::new(), HashSet::from(["path"]))),
        ("read_file", (HashSet::from(["path"]), HashSet::new())),
        (
            "write_file",
            (HashSet::from(["path", "content"]), HashSet::new()),
        ),
        (
            "edit_file",
            (HashSet::from(["path", "old", "new"]), HashSet::new()),
        ),
        ("run_command", (HashSet::from(["argv"]), HashSet::new())),
    ])
});

fn parse_tool_action(
    tool_value: &Map<String, Value>,
    available_tools: Option<&HashSet<String>>,
) -> Result<AgentAction, AgentError> {
    let Some(tool) = tool_value.get("tool").unwrap().as_str() else {
        return Err(AgentError(
            "invalid ToolAction: 'tool' must be a string".into(),
        ));
    };

    let Some((required, optional)) = TOOL_FIELDS.get(tool) else {
        return Err(AgentError(format!("unknown tool: '{tool}'")));
    };

    if available_tools.is_some() && !available_tools.unwrap().contains(tool) {
        return Err(AgentError(format!("not enabled tool: '{tool}'")));
    }

    let missing_required = required
        .iter()
        .filter(|&field| tool_value.get(*field).is_none())
        .map(|s| *s)
        .collect::<Vec<_>>();
    let extra = tool_value
        .keys()
        .filter(|&k| {
            !required.contains(k.as_str()) && !optional.contains(k.as_str()) && *k != "tool"
        })
        .map(|s| s.as_str())
        .collect::<Vec<_>>();
    
    if !missing_required.is_empty() {
        return Err(AgentError(format!(
            "missing fields for {}: {}",
            tool,
            missing_required.join(", ")
        )));
    }
    if !extra.is_empty() {
        return Err(AgentError(format!(
            "unexpected fields for {}: {}",
            tool,
            extra.join(", ")
        )));
    }

    Ok(AgentAction::Tool(ToolAction {
        tool: tool.to_string(),
        arguments: tool_value
            .iter()
            .filter(|(k, _)| *k != "tool")
            .map(|(k, v)| (k.clone(), v.clone()))
            .collect(),
    }))
}

/// Week 4, Day 1: strictly parse and validate exactly one JSON action.
pub fn parse_action(
    response: &str,
    available_tools: Option<&HashSet<String>>,
) -> Result<AgentAction, AgentError> {
    let value: Value =
        serde_json::from_str(response).map_err(|e| AgentError(format!("invalid JSON: {e}")))?;

    if value.get("final").is_some() {
        if let Some(final_) = value.get("final").and_then(|v| v.as_str()) {
            return Ok(AgentAction::Final(FinalAction {
                final_: final_.to_string(),
            }));
        } else {
            return Err(AgentError(
                "invalid FinalAction: 'final' must be a string".into(),
            ));
        }
    }

    if let Some(final_) = value.get("final") {
        return Ok(AgentAction::Final(FinalAction {
            final_: final_.to_string(),
        }));
    }

    if value.get("tool").is_some() {
        return parse_tool_action(value.as_object().unwrap(), available_tools);
    }

    Err(AgentError(
        "invalid action: must be FinalAction or ToolAction".into(),
    ))
}

/// Week 4, Day 1: describe only the tools authorized for this run.
pub fn build_system_prompt(workspace: &dyn AgentWorkspace) -> String {
    let mut lines = vec![
        r#"You are a coding agent. Inspect the workspace before editing it."#,
        r#"Reply with exactly one JSON object and no markdown."#,
        r#"Finish with: {"final":"brief summary"}"#,
        r#"Available actions:"#,
    ];

    let tools = workspace.available_tools();

    if tools.contains("read_file") {
        lines.push(r#"{"tool":"read_file","path":"README.md"}"#)
    }

    lines.join("\n")
}
