// WARNING: Under review - generated by LLM.

//! Week 4, Day 3 learner surface for workspace effects.

use std::collections::{HashMap, HashSet};
use std::path::PathBuf;

use crate::protocol::{AgentError, AgentWorkspace, ToolAction};
use crate::receipts::ReceiptStore;

/// One operator approval or a model-visible denial reason.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ApprovalDecision {
    pub approved: bool,
    /// Python default: `""`.
    pub reason: String,
}

impl ApprovalDecision {
    pub fn new(approved: bool, reason: String) -> Result<Self, AgentError> {
        let decision = Self { approved, reason };
        decision.post_init()?;
        Ok(decision)
    }

    /// Python's ``__post_init__``.
    pub fn post_init(&self) -> Result<(), AgentError> {
        // TODO: validate the decision and require a reason for denials.
        todo!()
    }
}

/// Python's ``bool | ApprovalDecision`` confirmation result.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ConfirmResult {
    Approved(bool),
    Decision(ApprovalDecision),
}

/// Python's ``Callable[[ToolAction], bool | ApprovalDecision]``.
pub type ConfirmTool = Box<dyn Fn(&ToolAction) -> ConfirmResult>;

/// Tools and limits authorized for one explicit workspace root.
#[derive(Debug, Clone, PartialEq)]
pub struct ToolPolicy {
    pub root: PathBuf,
    /// Python default: ``64 * 1024``.
    pub max_file_bytes: i64,
    /// Python default: ``200``.
    pub max_list_entries: i64,
    /// Python default: ``False``.
    pub allow_writes: bool,
    /// Python default: ``()``.
    pub allowed_commands: Vec<Vec<String>>,
    /// Python default: ``64 * 1024``.
    pub max_write_bytes: i64,
    /// Python default: ``30.0``.
    pub command_timeout_seconds: f64,
}

impl ToolPolicy {
    pub const DEFAULT_MAX_FILE_BYTES: i64 = 64 * 1024;
    pub const DEFAULT_MAX_LIST_ENTRIES: i64 = 200;
    pub const DEFAULT_ALLOW_WRITES: bool = false;
    pub const DEFAULT_MAX_WRITE_BYTES: i64 = 64 * 1024;
    pub const DEFAULT_COMMAND_TIMEOUT_SECONDS: f64 = 30.0;

    pub fn new(
        root: PathBuf,
        max_file_bytes: i64,
        max_list_entries: i64,
        allow_writes: bool,
        allowed_commands: Vec<Vec<String>>,
        max_write_bytes: i64,
        command_timeout_seconds: f64,
    ) -> Result<Self, AgentError> {
        let policy = Self {
            root,
            max_file_bytes,
            max_list_entries,
            allow_writes,
            allowed_commands,
            max_write_bytes,
            command_timeout_seconds,
        };
        policy.post_init()?;
        Ok(policy)
    }

    /// Python's ``__post_init__``.
    pub fn post_init(&self) -> Result<(), AgentError> {
        // TODO: normalize and validate the root and positive limits.
        todo!()
    }
}

/// Run the Day 3 tools under one policy and approval callback.
pub struct Workspace {
    pub policy: ToolPolicy,
    /// Python default: ``None``.
    pub confirm_tool: Option<ConfirmTool>,
    /// Python default: ``ReceiptStore()``.
    pub receipt_store: ReceiptStore,
    observed: HashMap<String, String>,
    modified: HashSet<String>,
    next_call_number: i64,
}

impl Workspace {
    pub fn new(
        policy: ToolPolicy,
        confirm_tool: Option<ConfirmTool>,
        receipt_store: ReceiptStore,
    ) -> Self {
        Self {
            policy,
            confirm_tool,
            receipt_store,
            observed: HashMap::new(),
            modified: HashSet::new(),
            next_call_number: 1,
        }
    }

    /// Return only the tools enabled by this policy.
    pub fn available_tools(&self) -> &HashSet<String> {
        todo!()
    }

    /// Return the files changed by this workspace in sorted order.
    pub fn modified_files(&self) -> Vec<String> {
        todo!()
    }

    /// Resolve one relative path without traversal or symlinks.
    pub fn resolve_path(&self, raw: &str, must_exist: bool) -> Result<PathBuf, AgentError> {
        todo!()
    }

    /// List one directory, bounded by the policy.
    pub fn list_files(&mut self, raw: &str) -> Result<String, AgentError> {
        todo!()
    }

    /// Read one bounded UTF-8 regular file.
    pub fn read_file(&mut self, raw: &str) -> Result<String, AgentError> {
        todo!()
    }

    /// Atomically create a file or replace one previously read unchanged.
    pub fn write_file(&mut self, raw: &str, content: &str) -> Result<String, AgentError> {
        todo!()
    }

    /// Replace one exact occurrence in a previously read unchanged file.
    pub fn edit_file(&mut self, raw: &str, old: &str, new: &str) -> Result<String, AgentError> {
        todo!()
    }

    /// Run one exact allowed argument vector without a shell.
    pub fn run_command(&mut self, argv: &[String]) -> Result<String, AgentError> {
        todo!()
    }

    /// Dispatch one action, approving and receipting effects once.
    pub fn execute(
        &mut self,
        action: &ToolAction,
        tool_call_id: Option<&str>,
    ) -> Result<String, AgentError> {
        todo!()
    }
}

impl AgentWorkspace for Workspace {
    fn policy(&self) -> &ToolPolicy {
        &self.policy
    }

    fn available_tools(&self) -> &HashSet<String> {
        Workspace::available_tools(self)
    }

    fn modified_files(&self) -> Vec<String> {
        Workspace::modified_files(self)
    }

    fn execute(
        &mut self,
        action: &ToolAction,
        tool_call_id: Option<&str>,
    ) -> Result<String, AgentError> {
        Workspace::execute(self, action, tool_call_id)
    }
}
